ddtelemetry/src/worker.rs

Separate the telemetry payload building from sending, in order to appease the borrow checker \[T]/ and remove boxing.

Refactor the telemetry worker

---

ddprof-ffi/src/vec.rs
ddtelemetry/src/worker.rs

Clippy found a potential unexpected deadlock related to unexpected late drops in match block.
This PR fixes it

Fix clippy errors - including clippy::significant_drop_in_scrutinee

---

.github/workflows/lint.yml
.github/workflows/test.yml
README.md

Alpine released a new version including rust 1.60. We no longer need to build with rust 1.56.
Build with newer version
N/A
CI

Bump Rust version to 1.60

---

.clang-format
examples/ffi/exporter.cpp
examples/ffi/profiles.c

Adds `.clang-format` with 100 char line length. Reformats the examples
accordingly.
Since Rust uses 100 character limit for ColumnLimit, may as well make
the C and C++ examples match.
Nope.
It's just a re-format, no need to test anything.

Add .clang-format with 100 line length

---

ddprof-ffi/src/exporter.rs
ddprof-ffi/src/tags.rs
ddprof-ffi/src/vec.rs
ddprof-profiles/src/lib.rs
ddtelemetry/src/worker.rs

This fixes or works around clippy lints that exist on nightly.
I didn't like having a broken CI job as well as a broken clippy checker if I ran it locally.
Nightly is annoying but helpful.
Regular tests should work.

Fix or work around clippy lints

---

ddprof-exporter/src/lib.rs
ddprof-exporter/tests/form.rs
ddprof-ffi/src/exporter.rs
examples/ffi/exporter.cpp

Drop the "V3" suffix from exporter APIs. Does not otherwise change the behavior in any way.
As discussed in <https://github.com/DataDog/libdatadog/pull/24#discussion_r921924120> having the "V3" suffix on APIs doesn't seem that useful because:
1. We're still iterating on APIs all the time. We just broke the API again by changing the prefixes to `ddog_` so it seems a bit too early to version things. We never supported more than a version at a time!
2. Since the datadog agent just proxies profiling requests, we probably don't need to support more than one API version at a time.
3. The new intake format (internally called v2.4, whereas the old v3 was renamed to v1.3) does not need extensive API changes, so it's quite possible that we can move profilers to use v2.4 without changing the …

Drop "V3" suffix from exporter APIs

---

ddprof-ffi/src/profiles.rs
ddprof-profiles/src/lib.rs

This PR implements and exposes a `ddprof_ffi_Profile_set_endpoint` function, that is used to lazily associate endpoints to spans.
The goal is to help profilers support endpoint profiling.

Add ddprof_ffi_Profile_set_endpoint

---

ddcommon/src/connector/uds.rs
ddprof-ffi/src/exporter.rs
profiling/src/exporter/mod.rs

We should probably do a pass on this at some point, but consumers of
the Rust API should not have to deal with a boxed error generally so
that we avoid allocations and retain information about errors. We
would still have boxed errors in a few cases, most likely:
1. The errors on FFI boundaries will need boxed for ABI stability.
2. Having multiple errors from different crates in the same function.
Although it's possible to make error types to serve this case, it
does take effort that's probably better spent elsewhere for now.
Anyway, in this case, there is only one error type and the boxing is
unnecessary for Rust callers.
I also changed some usages of `std::error::Error` to just `Error` because
it's already imported.
I also exported `socket_path_from_uri` in `exporter` to match …

Cleanup socket APIs for other Rust consumers

---

ddprof-ffi/src/profiles.rs

Renames `ddprof_ffi_Profile_set_endpoint` to `ddog_Profile_set_endpoint`.
This matches the renames we did earlier.
Nope.
Everything is the same except the name change.

Use ddog prefix for Profile_set_endpoint

---

Cargo.lock
ddcommon-ffi/src/vec.rs
ddprof-ffi/Cargo.toml
ddprof-ffi/src/exporter.rs
ddprof-ffi/src/profiles.rs
profiling/src/exporter/config.rs
profiling/src/exporter/mod.rs

You can't put the latter into the former, and the former can move
across thread boundaries while the latter can't (at least, I _think_
that's what the giant error message said).
I hit some of these errors while using `anyhow` in the PHP profiler.
Since ddcommon is using the crate anyway, it seemed like we could align
here.

Use anyhow::Result instead of Result<_, Box<dyn Error>>

---

ruby/lib/libdatadog.rb
ruby/lib/libdatadog/version.rb
ruby/spec/libdatadog_spec.rb

Fix issue with old rubygems not detecting musl linux properly.
Old versions of rubygems (for instance 3.0.3) don't properly detect alternative libc implementations on Linux; in particular for our case, they don't detect musl.
(For reference, Rubies older than 2.7 may have shipped with an affected version of rubygems).
In such cases, we fall back to use RbConfig::CONFIG['arch'] instead.
Why not use `RbConfig::CONFIG['arch']` always? Because `Gem::Platform.local.to_s` does some normalization we want in other situations -- for instance, it turns `x86_64-linux-gnu` to
`x86_64-linux`. So for now we only add this workaround in a specific situation where we actually know it is wrong.
See also https://github.com/rubygems/rubygems/pull/2922 and https://github.com/rubygems/rubygems/pull/4082
Fixes …

Fix issue with old rubygems not detecting musl linux properly

---

Cargo.lock
ddcommon-ffi/Cargo.toml
ddcommon/Cargo.toml
ddtelemetry/Cargo.toml
profiling-ffi/Cargo.toml
profiling/Cargo.toml

Bumps versions to 0.8.0 from 0.8.0-rc.1. Adjusts Cargo.lock accordingly.
I want to use a non-prerelease of libdatadog for the next PHP profiler release.
Nope.
No changes necessary.

Release v0.8.0

---

ddcommon/src/connector/conn_stream.rs
ddcommon/src/connector/errors.rs
ddcommon/src/connector/mod.rs
ddcommon/src/connector/named_pipe.rs
ddcommon/src/connector/uds.rs
profiling-ffi/src/exporter.rs
profiling/src/exporter/config.rs
profiling/src/exporter/mod.rs

This PR adds support for the  Windows Named Pipe.
The .NET tracer currently runs in environment (AAS) where traces are sent to the agent through windows named pipe. The customers that have their apps in that environment are waiting for the profiler to work there too.
Not on top of my head
* I build a custom version of libdatadog, linked it to the compiler.
* Implement support for named pipe in the profiler
* Setup the datadog agent to listen on windows named pipe by setting the environment variable `DD_APM_WINDOWS_PIPE_NAME` to `\\.\pipe\datadogpipe\mypipe`
* Run the application
I check the profiler log and I saw the agent url is the named pipe:
`[2022-08-23 22:01:41.691 | info | PId: 421300 | TId: 411900] Using agent endpoint windows:\\.\pipe\datadogpipe\mypipe`
And saw in the dashboard …

Add support for Windows Named Pipe

---

ruby/Rakefile
ruby/lib/libdatadog.rb
ruby/lib/libdatadog/version.rb
ruby/spec/libdatadog_spec.rb

* Update the needed versions and hashes to package libdatadog 0.8.0 for Ruby
* Updates a few hardcoded file names to the new names adopted for 0.8.0
I'm following along the checklist at
<https://github.com/DataDog/libdatadog/blob/main/ruby/README.md#releasing-a-new-version-to-rubygemsorg>.
Use latest release for Ruby profiling.
I've gone ahead and updated the Ruby profiler to use this version in https://github.com/DataDog/dd-trace-rb/tree/ivoanjo/upgrade-to-libdatadog-0.8.0 . I am able to run the Ruby profiler test suite both on macOS as well as on Linux with the new release.
To reproduce my results, you need to do the following:
* Check out this PR
* Build the packages locally: `cd ruby && bundle exec rake package`
* Check out dd-trace-rb
* Change to the branch I mentioned above
* Copy …

Package libdatadog 0.8.0 for Ruby

---

build-profiling-ffi.sh
profiling-ffi/datadog_profiling_with_rpath.pc.in

* Fix `build-profiling-ffi.sh` script not working with relative paths
* Fix incorrect placeholder for version
See individual commit messages for details.
* Check that `build-profiling-ffi.sh` still produces the same output as before, as well as working now with relative paths
* Check that `datadog_profiling_with_rpath.pc` gets templated correctly with the version

Fix `build-profiling-ffi.sh` script not working with relative paths + Fix incorrect placeholder for version

---

ddcommon-ffi/cbindgen.toml

This PR fixes the C/C++ macro in the common.h file.
This PR fixes the issue https://github.com/DataDog/libdatadog/issues/47 for old GCC version.
What I have done to validate the fix:
- Followed the steps from https://github.com/DataDog/libdatadog/issues/47 and checked that for this old version 4.9.2 the issue was fixed.
- Compiled the .NET profiler on Linux with Clang 11.
- Compiled a little C code which includes a modified version of `common.h` with a newer version of GCC (10.2.1)
- Compiled the .NET profiler with a modified version of `common.h` (what you have in the fix)

Fix compilation error for old version of GCC

---

ddcommon/src/tag.rs
profiling-ffi/src/exporter.rs
profiling/src/exporter/mod.rs

Change `Tag` to hold a `String` instead of `Cow<str>`.
I also implemented `AsRef<str>` for `Tag`. 
This originated from a lint on nightly which didn't like `Cow::to_owned`
being called, and instead callers should use `Cow::clone` or
`Cow::into_owned`. However, while inspecting the code with fresh eyes, we
saw that we're always holding a `Cow::Owned` variant, so just hold the
`String` instead.
Simultaneously, I got a crash report in Rust for the PHP profiler. I
don't support forking, and they forked. Anyway, for this particular
crash it's not much harder to support `fork` (well, it leaks
technically but works) than to disable everything on a fork. As part of
supporting fork, I need to fixup the `process_id` tag to have the new
pid after a fork, and `Tag::as_ref` will help with that.
I also …

Change Tag to hold a String instead of Cow<str>

---

.github/actions/cache/action.yaml
.github/workflows/lint.yml

Nightly builds that pull in latest lints daily, often cause us to chase broken tests.
In a few cases it turned out that the clippy checks were later removed - while we've lost time fixing code to keep the tests up to date. 
This PR introduces adds latest "stable" clippy to be used as reference against latest nightly - and allows other builds in the matrix to finish if one of them fails.
Additionally it improves the caching on lints, and should reduce their execution time to seconds, instead of minutes

fix nightly lints surprise build breakage

---

ruby/Rakefile
ruby/lib/libdatadog/version.rb

Package libdatadog 0.9.0 for Ruby.
Use latest libdatadog magic in Ruby.
I'm following along the checklist at
<https://github.com/DataDog/libdatadog/blob/main/ruby/README.md#releasing-a-new-version-to-rubygemsorg>
I have an open draft PR to integrate this release into Ruby: https://github.com/DataDog/dd-trace-rb/pull/2302 . The downstream Ruby integration does not pick up new releases automatically.
To test this locally, you'll need to download package the gem manually, and then install it and you'll be able to run the dd-trace-rb test suite using the branch in https://github.com/DataDog/dd-trace-rb/pull/2302 .

Package libdatadog 0.9.0 for Ruby

---

profiling-ffi/src/exporter.rs
profiling/src/exporter/mod.rs

After some discussion on the expected values for `profiling_library_name` on slack, I've decided to go ahead and document the current expectations alongside the API.
Avoid confusion over expected values for `profiling_library_name`.
(None)
(This is a documentation change only)

Improve ProfileExporter API docs

---

ddcommon/src/container_id.rs
ddtelemetry-ffi/Cargo.toml
ddtelemetry-ffi/cbindgen.toml
profiling-ffi/cbindgen.toml

Currently Cgroup path is rightfully hardcoded in the source, however this makes it impossible to perform end-to-end tests on stubbed values of the file, as `/proc/groups/self` file is not overridable on linux systems

Allow setting cgroup path for integration testing purposes

---

ddtelemetry-ffi/src/lib.rs

Add explicit MaybeError c drop fn

---

profiling/src/exporter/mod.rs

This PR adds AAS metadata as tags in the `event.json` file instead of adding them in the form body.
In a previous https://github.com/DataDog/libdatadog/pull/50, the metadata were added in the form body but with the 2.4 endpoint version, tags are added in the `event.json` file.
Same as the previous PR (https://github.com/DataDog/libdatadog/pull/50)

Add AAS metadata in event.json file

---

ddcommon-ffi/cbindgen.toml
ddcommon-ffi/src/tags.rs
ddcommon-ffi/src/vec.rs
examples/ffi/exporter.cpp
examples/ffi/profiles.c
profiling-ffi/cbindgen.toml
profiling-ffi/src/exporter.rs
profiling-ffi/src/profiles.rs

This PR updates the names used in the libdatadog API as discussed in the 1.0 discussion meeting.
In particular, the following concerns were addressed:
* Namespace names -- `ddog_` for common-ffi, `ddog_prof_` for profiling-ffi. This avoids having something like `ddog_Line` which is very specific to profiling be at the top of the namespace.
* Fixed inconsistency in destructors: we had `free`, `delete` and `drop`. We now use `drop` everywhere.
* Updated namespacing for nested things. E.g. the result of `ddog_prof_Exporter_new` is a `ddog_prof_Exporter_NewResult`.
* Used case to separate structs (CamelCase) from methods (snake_case)
One departure from what was discussed in the meeting is how containers/generics are named. I had proposed `ddog_VecTag` and `ddog_SliceU8` but cbindgen really …

Rename FFI types, functions and enums in preparation for 1.0

---

profiling/src/exporter/mod.rs
profiling/src/profile/mod.rs

Rename the field `endpoints_count` into `endpoint_counts`.
This field is used in the backend, but the name expected by the backend is not the one I used.
Did the same test for the previous PR: run a .NET application with the Tracer and check what's inside the HTTP request.

Change `endpoints_count` into `endpoint_counts`

---

ruby/Rakefile
ruby/lib/libdatadog/version.rb

Package libdatadog 1.0.1 for Ruby.
Use latest libdatadog version from Ruby.
The 1.0.0 release was never packaged, and I don't think it's worth doing so just for completeness. (The binaries are still up on GitHub, so this decision can be revisited if ever we change our minds).
I'm following along the checklist at
<https://github.com/DataDog/libdatadog/blob/main/ruby/README.md#releasing-a-new-version-to-rubygemsorg>
I have an open draft PR to integrate this release into the Ruby profiler: https://github.com/DataDog/dd-trace-rb/pull/2530 . The downstream Ruby integration does not pick up new releases automatically.
To test this locally, you'll need to download package the gem manually, and then …

Package libdatadog 1.0.1 for Ruby

---

Cargo.lock
profiling-ffi/Cargo.toml
profiling/Cargo.toml

This PR tweaks the optional features of the `chrono` crate to avoid pulling in the `time` crate.
We got warned by dependabot that the version of `time` pulled in by `chrono` is a deprecated version that should no longer be used.
Since we were not actually making use of any of the features provided by it, we can just remove it.
(N/A)
Validate that all tests still pass.

Remove unused optional `time` dependency

---

Cargo.lock
ddcommon-ffi/Cargo.toml
ddcommon-ffi/src/vec.rs
ddcommon/Cargo.toml
ddcommon/src/tag.rs
ddtelemetry-ffi/Cargo.toml
ddtelemetry/Cargo.toml
ddtelemetry/benches/ipc.rs
ddtelemetry/src/config.rs
ddtelemetry/src/fork.rs
ddtelemetry/src/ipc/platform/unix/mod.rs
ddtelemetry/src/metrics.rs
profiling-ffi/Cargo.toml
profiling-ffi/src/profiles.rs
profiling/Cargo.toml
profiling/src/exporter/config.rs
profiling/src/profile/mod.rs

- Fix `clippy::uninlined_format_args` lints.
- Fix unused import `std::path::Path` in `cfg(test)`.
- Converts `local_root_span_id` in `add_endpoint` and related functions to be `u64` instead of a string.
- Removes unnecessary `Cow<str>` for `str` in label.
- Bumps version to v2.0.0.
The profiling backend can now accept numeric labels. This PR converts "local root span id" related parameters to use numbers in the endpoint API.
This should have been multiple PRs. I'm sorry.
- Change `add_endpoint` to use `u64` instead of a string.
- Change your `local root span id` labels to use the `.num` variant instead of `.str`. Transmute from `u64` to `i64` as necessary. If they aren't changed, then `profile.add` will fail.
And then test as normal. Double-check that Code Hotspots and Endpoint Profiling …

Convert local root span id to u64, fix clippy lints

---

profiling-ffi/src/profiles.rs

Documents the expected result of the `ddog_prof_Profile_add` API.
While validating #80 on Ruby, I called `add` in a way that should've triggered an error, but saw none.
On closer inspection, I had no error handling for `add` because it wasn't clear to me that its result could indicate an error.
Thus, I decided to document that fact.
At some point we could change `add` to return an actual result, allowing us to pass the error message back to the caller, but for now I decided to just document it.
Documentation change only.

Minor: Document expected result of `ddog_prof_Profile_add`

---

profiling/src/profile/mod.rs

This enforces that only a single label on a sample may contain a key of "local root span id". This means a `Profile::add` can now return an error case where it wouldn't before if multiple labels with keys of "local root span id" are sent. This is inherited by the FFI equivalent function as well, which returns 0 for such cases.
I had a conversation with Ivo in #80 and continued over Slack in which he convinced me the code would be overall simpler if we did this. Aside from being non-sensical to have multiple local root span id labels, it's also an implementation optimization.
I like having Ivo on the team :)
Upgrade, and run tests as normal. Unless you are sending multiple labels with keys of "local root span id", then this will behave the same.

fix(profiling)!: ensure a single label per sample has key "local root span id"

---

ddcommon/src/azure_app_services.rs
ddcommon/src/container_id.rs
ddtelemetry/src/ipc/platform/unix/mod.rs
profiling/tests/wordpress.rs
tools/src/bin/dedup_headers.rs

Fixes some `clippy::uninlined_format_args` lints and also a `clippy::seek_to_start_instead_of_rewind` lint and that appeared on `stable` aka 1.67.0.
An unrelated PR started failing :)
Nope.
No change, regular tests apply.

fix: clippy lints from Rust v1.67.0 release

---

README.md

Links to the `CONTRIBUTING.md` file
I could not click, had to scroll back to the top and then click on the `CONTRIBUTING.md` 😉 
Clippy will be pleased in #99 
Go to https://github.com/DataDog/libdatadog/tree/florian/fix-readme#contributing and see that `CONTRIBUTING.md` is now linked, click on the link, see the contribution guide, profit 🚀

fix link to contribution guide

---

ddcommon-ffi/src/error.rs
ddcommon-ffi/src/lib.rs
ddcommon-ffi/src/tags.rs
examples/ffi/exporter.cpp
examples/ffi/profiles.c
profiling-ffi/README.md
profiling-ffi/cbindgen.toml
profiling-ffi/src/exporter.rs
profiling-ffi/src/profiles.rs

This extracts an FFI `Error` type aka `ddog_Error` and it contains an FFI Vec internally.
```rust
/// Please treat this as opaque; do not reach into it, and especially don't
/// write into it!
#[derive(Debug)]
#[repr(C)]
pub struct Error {
/// This is a String stuffed into the vec.
message: Vec<u8>,
}
```
Then, the FFI error types use this in their `Err` field, instead of `ddcommon_ffi::Vec<u8>`:
```rust
#[repr(C)]
pub enum SendResult {
HttpResponse(HttpStatus),
Err(Error),
}
```
The `*Result_drop` methods have been removed:
- ddog_prof_Exporter_NewResult_drop
- ddog_prof_Exporter_Request_BuildResult_drop
- ddog_prof_Exporter_SendResult_drop
- ddog_prof_Profile_AddResult_drop
- ddog_prof_Profile_SerializeResult_drop
- ddog_Vec_Tag_PushResult_drop
And these were added instead:
- …

refactor(profiling)!: create FFI Error type and remove `*Result_drop` methods

---

ruby/Rakefile
ruby/lib/libdatadog/version.rb

This PR includes the changes documented in the "Releasing a new version to rubygems.org" part of the README: <https://github.com/DataDog/libdatadog/tree/main/ruby#releasing-a-new-version-to-rubygemsorg>
Enable Ruby to use libdatadog v2.0.0.
(N/A)
This was locally checked with the Ruby profiler branch that already supports libdatadog 2.

Package libdatadog v2.0.0 for Ruby

---

ruby/Rakefile

This PR removes the now-unneeded "gem signout" steps during the Ruby release process.
In #85, we changed the way that we authenticate with rubygems.org when pushing a new libdatadog release.
I just did a release with this new code, and noticed that because we no longer log in, but just use a limited API key, the "gem signout" does not do anything and emits an error.
Here's what I saw when I ran `docker-compose run push_to_rubygems`:
```
... preparation of packages goes here...
ERROR:  You are not currently signed in.
Please input 'libdatadog ruby release key' from 'Profiling - Falcon' Datadog 1Password:
(...key...)
Pushing gem to https://rubygems.org...
You have enabled multi-factor authentication. Please enter OTP code.
Code:   (...) …
```

Remove unneeded "gem signout" step from Ruby release

---

trace-normalization/src/normalize_utils.rs
trace-normalization/src/normalizer.rs

Adds service tag and env tag normalization to the normalizer + associated unit tests.
This normalizer is modeled very closely after the existing agent trace normalizer, which can be found [here](https://github.com/DataDog/datadog-agent/blob/main/pkg/trace/agent/normalizer.go).
The next PR will cover:
- `normalize_trace`
- `normalize_chunk`
These two last functions in the normalizer are much shorter than `normalize`
The trace normalizer will be used in our serverless agentless POC, which will use it to normalize traces before being sent directly to the datadog trace intake.
See: [the serverless branch](https://github.com/DataDog/libdatadog/tree/serverless)
- Tags allow non ascii alpha characters, while metrics names don't
The changes …

Trace Normalizer: add service + env tag normalization

---

trace-normalization/src/normalizer.rs

This PR adds the public functions `normalize_trace` and `normalize_chunk` to the normalizer, as well as associated unit tests.
in the go agent trace normalizer, the `normalize_chunk` function takes in the chunk, and a pointer to the root span ([see here](https://github.com/DataDog/datadog-agent/blob/85f2ce92c3d71988a1cf4693a9b472b25dacdd49/pkg/trace/agent/normalizer.go#L148)). Because of the fact that in rust the root span will have been moved into the spans vec of the trace chunk itself, I've opted to pass the index of the root span within the trace chunk spans vec instead
unit tests cover these additions (unit tests are translated/copied from the go agent normalizer)

Trace Normalizer: add trace & trace chunk normalization

---

windows/build-artifacts.ps1
windows/libdatadog.csproj
windows/libdatadog.props

Add scripts and files to build windows artifacts: libraries and nuget package
The goal is to allow developers to build libdatadog locally on windows and also in CI.
None
Run the tests locally

Add scripts to builds artifacts on windows

---

.gitlab-ci.yml

Move downstream repository to apm-reliability
- This is required to fix CI
- This is to allow libdatadog to run benchmarks

Move downstream repository to apm-reliability

---

tools/sidecar_mockgen/src/lib.rs

On musl, apparently, the compiler inserts a _GLOBAL_OFFSET_TABLE_ symbol of size zero.
I suppose we can just generally ignore size 0 symbols? If you don't like that, I can also exclude it explicitly by name.

Fix sidecar_mockgen for musl

---

Cargo.lock
serverless/src/main.rs
trace-mini-agent/Cargo.toml
trace-mini-agent/src/config.rs
trace-mini-agent/src/env_verifier.rs
trace-mini-agent/src/lib.rs
trace-mini-agent/src/mini_agent.rs
trace-mini-agent/src/trace_processor.rs
trace-utils/src/trace_utils.rs

Add an `env_verifier` field to the trace mini agent. The mini agent calls `env_verifier.verify_environment()` in a tokio async task during initialization. This function makes an HTTP call to `http://metadata.google.internal`, the Google metadata server.
This metadata server is only accessible within a Google Cloud VM, and will include the following header in the response, indicating a google cloud function environment:
`Server: Metadata Server for Serverless`
If the metadata server is not accessible or the correct header is not returned, exit the mini agent process.
In the node/python tracer, we only check for the presence of K_SERVICE or FUNCTION_NAME environment variables (which google cloud functions set) before spinning up the mini-agent.
To prevent the use of the mini agent in …

Mini Agent: Verify GCP Env

---

Cargo.lock
trace-mini-agent/src/env_verifier.rs
trace-protobuf/Cargo.toml
trace-protobuf/build.rs

Fixed env_verifier unit test + protobuf gitlab build issues (failing on windows/centos static analysis)
build failures

Fix env_verifier + protobuf gitlab build issues

---

Cargo.lock
trace-mini-agent/Cargo.toml
trace-mini-agent/src/config.rs
trace-mini-agent/src/stats_flusher.rs
trace-mini-agent/src/trace_flusher.rs
trace-mini-agent/src/trace_processor.rs
trace-utils/src/stats_utils.rs
trace-utils/src/trace_utils.rs

Support `DD_SITE`, sending traces and trace stats to non-us1 intakes
Mini Agent mvp/closed beta with non-us1 customers
`config.rs` unit tests. Manually tested by sending traces and trace stats to each region (with the exception of `ddog-gov.com`), and verifying they show up in the UI

Mini Agent: Support DD_SITE

---

Cargo.lock
ddcommon-ffi/Cargo.toml
ddcommon/Cargo.toml
ddtelemetry-ffi/Cargo.toml
ddtelemetry/Cargo.toml
profiling-ffi/Cargo.toml
profiling/Cargo.toml

Bump libdatadog profiling package version to 2.2.0
Ship new features and bug fixes to profiles/tracers

Bump libdatadog to 2.2.0

---

.github/workflows/publish-serverless-agent.yml

Compressing with `upx "$filename" --ultra-brute` in a ubuntu-latest github workflow broke the executable and made it un-runnable. Using `--lzma` worked correctly however
Using lzma compression decreases binary size by 10KB.
Tested the workflow manually, verified the mini agent binary executes properly. Tested the --lzma compressed binary in Google Cloud Functions and found a negligible performance difference over 20 cold start invocations.

Mini Agent: use lzma upx compression when building for release

---

.github/labeler.yml
.github/workflows/pr-auto-labeler.yml

Automatically add label to PR in order to get the scope of the PR when listing all the PR.
This can be used later to improve release note (ex.: for profiling related release, only get PRs involved with `profiling`, `common`... labels)

Add PR automatic labeler

---

Cargo.lock
LICENSE-3rdparty.yml
ddtelemetry/Cargo.toml
ddtelemetry/src/config.rs
ddtelemetry/src/ipc/interface.rs
ddtelemetry/src/ipc/sidecar/config.rs
ipc/src/lib.rs
ipc/src/sequential.rs
spawn_worker/src/trampoline.c
spawn_worker/src/unix/spawn.rs

* This branch includes Pauls changes (#151, #152)
* Fix for Pauls PR about the sequential executor: Returning a future which instantly resolves instead of Future::Pending
* Fix for Pauls PR to exclude the memfd from being closed
* Close all the file descriptors in the intermediary forked process too (musl has an atexit handler which wreaks havoc *see below)
* Changed set_session_agent_url to not send a response (some tests were blocking in read(), waiting for the sidecar to reply)
* Temp files are controlled by the process spawning logic and can be removed by the spawned process.
* equeue_actions now can properly handle further updates after the initial flush, like a Lifecycle(Stop) event. Before that went mostly through thanks to the race condition that a stop immediately followed the …

Fixing all the outstanding issues with the sidecar

---

sidecar/src/unix.rs

Proposing datadog-ipc-helper. "spawned_worker" is not very useful for an user.

Use a better name for the sidecar process

---

.github/workflows/verify-proto-files.yml
trace-protobuf/src/pb.rs
trace-protobuf/src/pb/agent_payload.proto
trace-protobuf/src/pb/span.proto
trace-protobuf/src/pb/tracer_payload.proto

Agent proto files and those found in trace-protobuf are out of sync. This PR updates the protobuf files & remove an unnecessary line from the verify proto CI
autogenerated rust structs (from proto files) are unchanged, verified by running:
`cargo build --features generate-protobuf` in `trace-protobuf`

Update proto files

---

.gitlab-ci.yml

It seems that since there are no "real" jobs in gitlab pipeline, only a trigger for a downstream pipeline, gitsync does not push any status check to github (status checks are associated to "real" jobs). The workaround it to create an actual job whose status depends on status of downstream pipeline.

Report downstream gitlab pipeline failures to github

---

trace-mini-agent/src/config.rs

Let the trace + trace stats intake url prefix be configurable by the `DD_APM_DD_URL` environment variable. To be used for integration testing.
Setting `DD_APM_DD_URL=http://127.0.0.1:3333` will result in the following two endpoints being used:
```
http://127.0.0.1:3333/api/v0.2/traces
http://127.0.0.1:3333/api/v0.2/stats
```

Mini Agent: Support env var set custom trace & trace stats intake urls

---

spawn_worker/build.rs
tools/sidecar_mockgen/src/lib.rs

And force libm to be linked in trampoline, given that it's going to be used to link against rust code, which needs libm.
Allowing more targets to build the sidecar... Tried to compile it outside of our docker images with compilers in the wild...

Fix sidecar_mockgen when symbols are fully dynamic in source binary

---

ddcommon/src/connector/mod.rs
ddtelemetry/src/worker/http_client.rs
profiling/src/exporter/mod.rs

With many different telemetry workers (due to different services in sidecar), overhead can be significant on startup.

Put Connector::default() into lazy_static! to avoid repeated overhead of root cert fetching

---

Cargo.lock
trace-mini-agent/Cargo.toml
trace-mini-agent/src/config.rs
trace-mini-agent/src/env_verifier.rs
trace-mini-agent/src/mini_agent.rs
trace-mini-agent/src/trace_processor.rs
trace-utils/src/trace_utils.rs

Checks the azure function filesystem at specific paths for two files (host.json and function.json) to verify we're running in an azure function environment.
azure functions (consumption plan) support
Unit tested + manually tested with linux + windows azure functions.

Mini Agent: Verify azure function env w/ filesystem

---

trace-mini-agent/src/mini_agent.rs
trace-mini-agent/src/stats_processor.rs
trace-mini-agent/src/trace_processor.rs
trace-protobuf/build.rs
trace-protobuf/src/pb.rs

Support receiving traces from the dotnet tracer.
The dotnet tracer sends traces + trace stats through POST requests instead of PUT.
Add support trace deserialization of "null" fields

Mini Agent: Dotnet support

---

.gitlab-ci.yml

Add a tiny message pointing people in the right direction if something fails in GitLab CI.
I got confused by this, so might as well improve it so that I'm the last person to be confused :)
N/A
Validate that this message shows up when going to the "report_gitlab_CI_status" job in CI.

Minor: Add help message on CI failure

---

.gitlab-ci.yml

Fix a bug in YAML syntax introduced in #182.
Fix broken CI step.
HOW CAN YAML BE MORE ANNOYING THAN JSON.
Validate that GitLab CI pipeline step runs.

Fix bug in yaml syntax introduced in #182

---

ipc/tarpc/tarpc/examples/custom_transport.rs
ipc/tarpc/tarpc/src/context.rs
ipc/tarpc/tarpc/src/server.rs
ipc/tarpc/tarpc/src/server/limits/requests_per_channel.rs
ipc/tarpc/tarpc/src/server/testing.rs

This PR uses `rustup run nightly cargo fmt --all` to reformat the code in the main branch and hopefully fix up the failed CI jobs which are complaining about formatting.
For reference:
* https://gitlab.ddbuild.io/DataDog/apm-reliability/libddprof-build/-/jobs/288056193
* https://gitlab.ddbuild.io/DataDog/apm-reliability/libddprof-build/-/jobs/288056194
Bring `main` back to green.
Having blocking steps in CI for running the formatter seems a bit too heavy-handed...
Validate that CI is back to green.

Fix CI in main branch by running cargo fmt

---

profiling/src/profile/mod.rs

This PR fixes the error message which can be misleading when investigating issues.
If you create a profile with 2 samples types and add a sample with 3 sample types, you will get this error message:
```
expected 3 sample types, but sample had 2 sample types
```
But, it's not correct, we should have got:
```
expected 2 sample types, but sample had 3 sample types
```
N/A
N/A

profiling: fix sample types error message

---

Cargo.lock
ddcommon-ffi/Cargo.toml
ddcommon/Cargo.toml
ddtelemetry-ffi/Cargo.toml
ddtelemetry/Cargo.toml
profiling-ffi/Cargo.toml
profiling/Cargo.toml

Bump libdatadog version to 3.0.0 in preparation for release.
Release next version.
As we discussed via slack/in the previous weekly meeting, since #181 contains a very small backwards-incompatible change to `ddog_prof_Exporter_Request_build`, then since we're trying to strictly adhere to semver, I'm bumping the major version of the library.
Nevertheless, upgrading from 2.2.0 to 3.0.0 is really trivial.
Validate that CI is still green? Only the version really changes :)

Bump libdatadog to 3.0.0

---

Cargo.lock
ipc/Cargo.toml
trace-obfuscation/Cargo.toml

This PR gets rid of the `atty` dependency by upgrading our version of the `criterion` crate (used for microbenchmarks) from version 0.4 to 0.5.1.
We want to get rid of `atty` as it was flagged as dependabot as potentially problematic. In practice we probably wouldn't have been affected, but I see no reason not to upgrade `criterion`.
N/A
Validate that `cargo bench` still compiles and runs fine (which I did locally).

Get rid of atty dependency

---

.github/workflows/test-ruby.yml
ruby/Rakefile
ruby/docker-compose.yml
ruby/lib/libdatadog/version.rb

This PR includes the changes documented in the "Releasing a new version to rubygems.org" part of the README: <https://github.com/datadog/libdatadog/tree/main/ruby#releasing-a-new-version-to-rubygemsorg>
It also includes:
* A CI workaround for the Ruby 2.2 github action (this Ruby release is getting quite old so testing it is increasingly difficult)
* A tweak to make modern versions of git happy when running the release script
Enable Ruby to use libdatadog v3.0.0.
Ruby actually skipped libdatadog v2.1 and v2.2 because their changes either didn't impact Ruby, or added features that Ruby didn't need yet.
I've tested this release locally against the changes in …

Package libdatadog v3.0.0 for Ruby

---

ddcommon-ffi/src/vec.rs

Rust 1.71 was released, which means our `cargo +stable clippy ...` commands are now on a new version. Looks like this time there's just a single failing lint, `clippy::default-constructed-unit-structs`.
Ivo told me the main branch CI was broken.
Nope.
Existing tests are adquate.

style: fix clippy::default-constructed-unit-structs

---

ruby/gems.rb

In our Ruby packaging, we use the `standard` gem, which provides a code auto-formatter. This gem pulls in `standard-performance` as one of its dependencies.
Recently, version 1.1.1 of `standard-performance` was released, and this update was picked up and was breaking in CI.
I reported this issue upstream on
https://github.com/standardrb/standard-performance/issues/11 ; as well as forcing an earlier version to be used.
Now, 1.1.2 has been released and thus we can remove our workaround that was avoiding the problematic version.
Keep using the latest version of `standard` and its dependencies.
N/A
Validate that CI is still green!

Minor: Remove Ruby workaround for upstream issue

---

Cargo.lock
trace-mini-agent/Cargo.toml
trace-mini-agent/src/config.rs
trace-mini-agent/src/trace_processor.rs
trace-obfuscation/Cargo.toml
trace-obfuscation/benches/replace_trace_tags_bench.rs
trace-obfuscation/src/replacer.rs

Integrate the trace-obfuscation trace tag replacement into the mini agent.
Reads the `DD_APM_REPLACE_TAGS` env var for a list of JSON formatted replace rules, following [these docs](https://docs.datadoghq.com/tracing/configure_data_security/?tab=environmentvariable#scrub-sensitive-data-from-your-spans).
mini agent functionality

Mini Agent: Integrate tag replacement

---

.github/workflows/lint.yml
.github/workflows/test.yml
.gitlab-ci.yml

Uses the latest Rust version in Alpine.
Keeps up to date with the Rust version in Alpine
`cargo test` + CI

Bump Rust version to 1.69

---

sidecar-ffi/src/unix.rs
sidecar/src/agent_remote_config.rs
sidecar/src/lib.rs
sidecar/src/one_way_shared_memory.rs

Adds a trailing zero byte to keep C code happy. (Turns out PHPs json decoder is really unhappy if the last byte isn't a zero byte.)
And prepares work for being able to use this code for actual remote config (as in remote config from our backend).

Abstract OneWayShm out from AgentRemoteConfig

---

profiling/src/profile/pprof.rs

Removes an outdated comment.  The code is commented to state that we only use the "string" format for labels, but we actually use both (and even enforce the use of numeric labels in some cases https://github.com/DataDog/libdatadog/blob/20b50a9a8ed7f6a5427c25c88f6d9bd8270e2ccf/profiling/src/profile/mod.rs#L563 )
Comments should reflect reality
This only removes a comment, no semantic change to code

Fix outdated comment

---

profiling/src/profile/mod.rs

Increases type safety by using a first class type for various `PProfId` types, including `LocationId`, `MappingId` and `FunctionId`. Also does a bit of refactoring on the existing unique types as per PR comments.
Currently, Locations are identified by an `PProfId` value, which represents an index into a interning table.  This is error prone, since there are many PProfIds, generated by many different tables.  If we use the wrong one, we can get a panic, or nonsense values. If we store the index in a transparent type, the type system both documents and enforces the correct use of indicies.
As a side benefit, reduced the size of the index from `usize` to `u32`, saving 4 bytes per index.

Use unique types for PProfIds

---

profiling-replayer/Cargo.toml
profiling-replayer/src/main.rs

Adds memory tracking to the profiling-replayer, via a `-m` or `--mem` flag.
The first step towards optimizing memory is knowing how much we're actually using.
At least on mac, the reported memory usage seems quite noisy. For two consecuative runs:
```
Memory usage (kB)
Before adding samples:  102678
After adding samples:   104792  Delta: 2113
After serializing:      119209  Delta: 14417
...
Memory usage (kB)
Before adding samples:  101974
After adding samples:   105332  Delta: 3358
After serializing:      118603  Delta: 13271
```
run the profiler as before, but also pass the `-m` flag.

Feature(profiling-replayer): Implement memory tracking

---

ddtelemetry/examples/tm-worker-test.rs
ddtelemetry/src/data/metrics.rs
ddtelemetry/src/metrics.rs
ddtelemetry/src/worker/mod.rs
ipc/src/platform/unix/mem_handle.rs
sidecar/src/unix.rs

Also fixes that opened (as opposed to created) named shm handles are always unlinked. Oops.

Add sidecar metrics into their own namespace, fix seq id

---

profiling/src/profile/internal/endpoints.rs
profiling/src/profile/internal/mod.rs
profiling/src/profile/internal/sample.rs
profiling/src/profile/internal/upscaling.rs
profiling/src/profile/mod.rs

Moves internal datastructures out of the `profile/mod.rs` file into `profile/internal/<structure_name>.rs`.
This work was partially completed in #214, but some types were missed.  Collecting them too.

refactor: Move profiler internal types to the internal module

---

trace-mini-agent/src/trace_processor.rs
trace-utils/src/lib.rs
trace-utils/src/trace_test_utils.rs
trace-utils/src/trace_utils.rs

Refactor common `create_test_span function` into `trace-utils`
cleanliness
This PR only touches unit tests. Unit tests are 🟢

Refactor common unit test create_test_span function into trace-utils

---

ddcommon-ffi/src/slice.rs
ddcommon-ffi/src/vec.rs
ddcommon/src/cstr.rs
ddtelemetry/src/metrics.rs
ipc/src/platform/unix/mod.rs
ipc/tarpc/tarpc/src/client.rs
profiling/src/profile/mod.rs
sidecar/src/interface.rs
trace-obfuscation/benches/credit_cards_bench.rs

This fixes clippy lints that showed up on the recently released 1.72.0 toolchain.
CI was failing in another PR due to the new Rust release.
Nope.
Everything should work literally the same.

fix: warnings on new Rust 1.72.0 toolchain

---

profiling/src/exporter/mod.rs
profiling/src/profile/mod.rs

This tunes the initial buffer sizes for encoding the profiles into the serialized pprof format, and also when compressing  files for upload.
The goal is to reduce allocator fragmentation, pressure, and generally return more memory to the system. In a separate PR, Ivo recorded some RSS numbers before/after serialization, and noticed in that PR how it freed up dozens of KiB of memory. The thing is, that change only allocated ~1KiB of string data into a separate arena allocator. The entire difference is therefore about the memory allocation patterns, and not their sizes.
That PR is a bit more complex, and Ivo wasn't sure about shipping it. This PR is very simple, and has a similar effect by simplifying allocations in a different area.
None.
Just test as normal, but notice that your system …

perf(profiling): tune initial buffer sizes

---

ruby/Rakefile
ruby/lib/libdatadog/version.rb

<https://github.com/datadog/libdatadog/tree/main/ruby#releasing-a-new-version-to-rubygemsorg>
Enable Ruby to use libdatadog v4.0.0.
N/A
I've tested this release locally against the changes in https://github.com/datadog/dd-trace-rb/pull/3104 .
As a reminder, new libdatadog releases don't get automatically picked up by Ruby, so the PR that bumps the Ruby profiler will also test this release against all supported Ruby versions.
This PR actually touches code that publishes builds (updates the SHAs to match the new releases), but I don't think we need a review from security for this.

[PROF-8139] Package libdatadog v4.0.0 for Ruby

---

examples/ffi/exporter.cpp
examples/ffi/profiles.c
profiling-ffi/src/profiles.rs
profiling-replayer/src/main.rs
profiling-replayer/src/replayer.rs
profiling/examples/profiles.rs
profiling/src/profile/mod.rs

Changes the API for the profiler to take the timestamp explicitly
Currently, the client does the work of building a label with the timestamp, and adding it to the Labels on the sample.
libdatadog then finds that label, extracts the information, and removes it from the vector.  Making it a function argument is cleaner and clearer.

Profiler: Take timestamp as an explicit argument, rather than hiding in the label

---

Cargo.lock
Cargo.toml
README.md
ddcommon-ffi/Cargo.toml
ddcommon/Cargo.toml
ddtelemetry-ffi/Cargo.toml
ddtelemetry/Cargo.toml
profiling-ffi/Cargo.toml
profiling-replayer/Cargo.toml
profiling/Cargo.toml
tools/Cargo.toml
trace-normalization/Cargo.toml
trace-obfuscation/Cargo.toml
trace-protobuf/Cargo.toml
trace-utils/Cargo.toml

This adds `workspace.package` to the root `Cargo.toml`:
```rs
rust-version = "1.69"
edition = "2021"
version = "4.0.0"
license = "Apache-2.0"
```
This allows changing things in fewer places. I hope to make changing the minimum supported rust version (MSRV), edition, and libdatadog version easier.
Not every crate inherits these new properties. The serverless and sidecar crates, and some of their dependencies, have remained under their own versioning and control.
Regular tests should apply. This shouldn't change any behavior.

Use Cargo workspace properties and document MSRV

---

ddcommon-ffi/src/vec.rs
examples/ffi/exporter.cpp
examples/ffi/profiles.c
profiling-ffi/cbindgen.toml
profiling-ffi/src/profiles.rs

`ddog_prof_Profile_new` now returns a `ddog_prof_Profile_NewResult` instead of a `ddog_prof_Profile`.
Currently, this routine doesn't fail. In the future, it's expected to be possible to fail, so we want to get clients to be prepared for it since we're also shipping breaking changes in v5.0.0 already.
None.
Adapt to the above change and test as usual otherwise. Note that currently it cannot fail, but do not rely on that. Add proper error handling.

refactor!(profiling-ffi): ddog_prof_Profile_new can fail

---

sidecar-ffi/src/unix.rs

The versions were ... picked up if they were empty. Which sort of defeats the point.

Fix version in sidecar ffi for dependencies and integrations

---

profiling-ffi/src/profiles.rs
profiling-replayer/src/main.rs
profiling/examples/profiles.rs
profiling/src/internal/profile.rs

The `internal::profile` module has both public API, and private helper functions.  Seperates them out to make it easier to see the public API when reading the code.
It's nice when code is easier to read.  Had been working on this file, and kept wishing it was organized like this, so just did it.
I renamed `add` to `add_sample` to follow the naming scheme of the rest of the file.
This is a refactor, covered by existing tests.

Refactor: reorganize functions in internal/profile to clarify the public api

---

Cargo.lock
Cargo.toml

**What does this PR do?**
This PR bumps the libdatadog version to 5.0.0. This PR looks a bit different from previous PRs to bump libdatadog version [(here's the 4.0.0 PR as an example)](https://github.com/DataDog/libdatadog/pull/236) because in [this PR](https://github.com/DataDog/libdatadog/pull/247) we've centralized the version on the single `Cargo.toml` file.
Furthermore, we're going from 4.0.0 to 5.0.0 because there were a number of backwards-incompatible changes to the profiling APIs.
**Motivation:**
Release libdatadog 5.0.0.
**Additional Notes:**
If I haven't missed anything, the backwards incompatible API changes were the following:
* The value of the `end_timestamp_ns` label is now provided as a regular argument to `ddog_prof_Profile_add`
* The libdatadog 5 serializer outputs …

Bump libdatadog version to 5.0.0 in preparation for release

---

ruby/Rakefile
ruby/lib/libdatadog/version.rb

<https://github.com/datadog/libdatadog/tree/main/ruby#releasing-a-new-version-to-rubygemsorg>
(It's also exactly the same as [the v4.0.0 release PR](https://github.com/DataDog/libdatadog/pull/238)).
Enable Ruby to use libdatadog v5.0.0.
N/A
I've tested this release locally against the changes in https://github.com/DataDog/dd-trace-rb/pull/3169 .

[PROF-8289] Package libdatadog v5.0.0 for Ruby

---

.github/workflows/miri.yml
ddcommon/src/connector/mod.rs
ddtelemetry-ffi/src/lib.rs
ddtelemetry/src/worker/http_client.rs
ipc/src/platform/unix/platform_handle.rs
ipc/tarpc/tarpc/src/client.rs
ipc/tarpc/tarpc/src/lib.rs
ipc/tarpc/tarpc/src/server.rs
ipc/tarpc/tarpc/src/server/in_flight_requests.rs
ipc/tarpc/tarpc/src/server/limits/requests_per_channel.rs
ipc/tarpc/tarpc/src/transport/channel.rs
ipc/tarpc/tarpc/tests/service_functional.rs
ipc/tests/blocking_client.rs
ipc/tests/flock.rs
sidecar-ffi/tests/sidecar.rs
sidecar/src/setup/unix.rs
spawn_worker/tests/trampoline_unix.rs
tests/spawn_from_lib/tests/spawn_unix.rs
trace-mini-agent/src/env_verifier.rs
trace-mini-agent/src/http_utils.rs
trace-mini-agent/src/trace_processor.rs
trace-utils/src/trace_utils.rs

1. Runs Miri in CI on all of the library, not just profiling
2. Explicitly "ignores" the tests where Miri cannot currently run
Miri is great for catching bugs, and as much of the library as possible should take advantage of that.
1. Miri does not run on Tokio tests for now: https://github.com/tokio-rs/tokio/issues/3360
2. Miri cannot be directly disabled on doc-tests, so I had to use a slightly ugly patch there https://github.com/rust-lang/miri/issues/584#issuecomment-825798646
3. None of the issues I saw appeared to be bugs: they generally related to syscalls that Miri doesn't currently support.  We should investigate enabling these tests as Miri advances
Should just run in the CI

Run Miri everywhere

---

sidecar-ffi/src/unix.rs
sidecar-ffi/tests/sidecar.rs
sidecar/src/interface.rs

Telemetry data sent through the sidecar currently appears in the dashboard as a service without an environment, this PR fixes it by propagating the environment all the way from the PHP extension to the telemetry worker builder.
Fixing OSS vulnerability detection on ASM services.
This will be tested through https://github.com/DataDog/dd-trace-php/pull/2313

Sidecar: propagate environment to telemetry

---

sidecar/src/unix.rs

Fix https://github.com/DataDog/dd-trace-php/issues/2317: Disabled logging should close both stdout and stderr.

Fix daemonization of sidecar closing stderr properly

---

ipc/tarpc/tarpc/examples/pubsub.rs

Fix a small clippy lint
The tarpc code has been vendored because we forked it with minimal changes, and the fact that package managers didn't want us to depend on other github repositories to distribute libdatadog.
I wish we had a way to disable the clippy lint just for tarpc, without having to diverge further from upstream but [it looks like it's not possible](https://github.com/EmbarkStudios/rust-ecosystem/issues/22).

Fix clippy lint

---

.github/workflows/verify-proto-files.yml

In #275, I've attempted to add the `mainmatter/continue-on-error-comment` github action which replaces a CI error with a comment, so that it's less annoying when "Verify trace-protobuf" fails and we don't get a ugly red cross on every PR.
My first attempt didn't work! I missed that I needed to change the trigger for the verify action to be on pull requests, not on pushes.
This PR fixes that, and we should see the action comment show up as an example.
Fix #275.
N/A
See the comment that will show up!

Allow verify trace-protobuf to continue on error, try 2

---

.github/CODEOWNERS

In codewoners file, the last entry takes precedence so any entry before appearing before the wildcard is ignored, which is probably not the expected behaviour.

Fix codewoner ordering

---

profiling/src/exporter/mod.rs

Just fixes a small typo in the docs.
Noticed it while trying to use the library.
N/A

Fix typo in ProfileExporter docs

---

ipc/src/example_interface.rs
ipc/src/handles.rs
ipc/tarpc/tarpc/src/server/limits/requests_per_channel.rs
profiling/src/internal/profile.rs
profiling/src/pprof/mod.rs
profiling/src/pprof/test_utils.rs
sidecar/src/interface.rs
trace-normalization/src/normalizer.rs

This fixes a series of lints that now show up due to Rust 1.75's release.
I opened a PR for something else and notice the lints failed.
`cargo clippy --fix --lib` is pretty nice, but I still had to resolve two things by hand.
[PROF-8862](https://datadoghq.atlassian.net/browse/PROF-8286)
Everything should work the same. Locally, all tests still passed.
[PROF-8862]: https://datadoghq.atlassian.net/browse/PROF-8862?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

style: fix Rust 1.75 lints

---

trace-normalization/src/normalizer.rs
trace-obfuscation/benches/replace_trace_tags_bench.rs
trace-obfuscation/src/replacer.rs
trace-protobuf/build.rs
trace-protobuf/src/pb.rs
trace-protobuf/src/pb/span.proto
trace-utils/src/trace_test_utils.rs
trace-utils/src/trace_utils.rs

Updates the protobuf definition files and files using it to match the latest main in the Datadog Agent (again).
Annoying failure messages for every commit in every PR (again).

Update protobuf files for span links to avoid failure comments

---

sidecar/src/log.rs
sidecar/src/unix.rs

Fixes new clippy lint.
Clippy started failing due to a new Rust release.
None.
Nothing changed as `append(true)` already implies `write(true)`.

style: fix clippy::ineffective-open-options

---

Cargo.lock

Updates `h2` security alert [security/dependabot/16](https://github.com/DataDog/libdatadog/security/dependabot/16).
I got notified on a `git push` this was there.
I don't think we use this functionality at all.
As I don't think we use this functionality, and this update is a security fix only, nothing should change at all.

fix: security alert for h2

---

ruby/Rakefile
ruby/lib/libdatadog/version.rb

https://github.com/datadog/libdatadog/tree/main/ruby#releasing-a-new-version-to-rubygemsorg
(It's also exactly the same as the [v5.0.0 release PR](https://github.com/DataDog/libdatadog/pull/267)).
Enable Ruby to use libdatadog v6.0.0.
N/A
I've tested this release locally against the changes in https://github.com/DataDog/dd-trace-rb/pull/3455 .

[PROF-8944] Package libdatadog v6.0.0 for Ruby

---

.github/workflows/test.yml

Call the matching build telemetry step (instead of build-profiling-ffi)
N/A
NA
NA

Minor CI fix - build telemetry ffi

---

.github/workflows/lint.yml

The check on the 3rd party licenses was causing issues when the registry paths were different. This is a workaround where we ignore parts of the paths.
Fix 3rd party license check flakyness
Ignore differences due to path
```
registry/src/index.crates.io-6f17d22bba15001f/ring-0.16.20/LICENSE
```
NA
This is a CI change

3rd party license check

---

trace-protobuf/src/pb.rs
trace-protobuf/src/pb/stats.proto

Updates the protobuf definition files and files using it to match the latest main in the Datadog Agent.
Avoid failure comments for diffs in CI.

Update protobuf files for stats to avoid failure comments

---

Cargo.lock
LICENSE-3rdparty.yml
crashtracker/Cargo.toml
crashtracker/src/api.rs
crashtracker/src/crash_info.rs
crashtracker/src/lib.rs
crashtracker/src/receiver.rs
crashtracker/src/stacktrace.rs

Uses blazesym to resolve symbol addresses into names.  
Crash reports with names are better than crashreports with pointers.
This depends on an unreleased change in Blazesym.  We pin to a commit that has the change.  Once they release it, we can move to use that version. 
run `crashtracker::api::test_crash` and see that the the emitted crash report now includes 
after:
```
"stacktrace": [
{
"ip": "0xaaaab1b32350",
"module_base_address": null,
"names": [
{
"colno": 5,
"filename": "mod.rs",
"lineno": 66,
"name": "backtrace::backtrace::trace_unsynchronized"
}
],
"sp": "0xffffa5f758c0",
"symbol_address": "0xaaaab1b3231c"
},
{
"ip": "0xaaaab1b32438",
"module_base_address": null,
"names": [
{
"colno": 5,
"filename": "collectors.rs",
"lineno": 30,
"name": …
```

[crashtracker] Use blazesym to resolve stack trace names in the receiver 

---

tools/src/bin/dedup_headers.rs

Small change in dedup_headers, so that a pub const (translated as a #define) used in the definition of an enum will be in the same file than the enum.
```
pub const LOG_ONCE: isize = 1 << 3;
pub enum Log {
Deprecated = 3 | LOG_ONCE,
}
```

Also move #defines when deduplicating headers

---

crashtracker/src/api.rs
crashtracker/src/collectors.rs
crashtracker/src/crash_handler.rs
crashtracker/src/crash_info.rs
crashtracker/src/receiver.rs
profiling-ffi/src/crashtracker.rs

1. Adds a new config option to allow crashtracking to avoid collecting stack traces
2. Makes a best-effort attempt to send crash-reports, even when the signal handler failed to complete
signal handling in the context of a crash is inherently difficult: we're already in a crashing state, so signal handling operations themselves may also crash.  In particular, collecting the stacktrace is dangerous, as it may invoke non-signal-safe functionality.  This PR gives users of crashtracking two ways to handle this issue:
1. They can disable collecting stacktraces (likely controlled by an environment variable)
2. If the stack handler itself crashes, we can still make a best-effort attempt to send out the crash-report. Note that we do the most risks steps (collecting the stack trace) last to …

[Crashtracker] Make crashtracker more resilient to failing signal handlers

---

ruby/lib/libdatadog.rb
ruby/lib/libdatadog/version.rb
ruby/spec/libdatadog_spec.rb

This PR fixes platform detection not working correctly when the user's platform is `x86_64-linux-gnu`/`aarch64-linux-gnu`.
This manifested to a user as the following error:
> Profiling was requested but is not supported, profiling disabled: Your ddtrace installation is missing support for the Continuous Profiler because the `libdatadog` gem installed on your system is missing binaries for your platform variant. (Your platform: `x86_64-linux-gnu`) (Available binaries: `x86_64-linux`, `x86_64-linux-musl`)
In the past, rubygems did this normalization for us (we even had a comment mentioning it in the code!) but this was removed in https://github.com/rubygems/rubygems/pull/5852 for Rubygems 3.4+
I'm also bumping the `GEM_MAJOR_VERSION` in the `version.rb` file so I can release this fix as …

[PROF-9257] Fix incorrect platform detection for x86_64-linux-gnu/aarch64-linux-gnu

---

Cargo.lock
LICENSE-3rdparty.yml
sidecar-ffi/src/lib.rs
sidecar/Cargo.toml
sidecar/fixtures/installed.json
sidecar/src/interface.rs

Up to now this happened on the tracer side and could be quite expensive. We're moving it to the sidecar so that we can a) apply caching and b) not execute it in the request path of the tracer.
This brings considerable performance improvements in our benchmarks.

Add composer installed.json parsing in sidecar

---

Cargo.lock
LICENSE-3rdparty.yml
build-profiling-ffi.sh
cmake/DatadogConfig.cmake.in
ddtelemetry-ffi/Cargo.toml
ddtelemetry-ffi/src/builder.rs
ddtelemetry-ffi/src/builder/expanded.rs
ddtelemetry-ffi/src/builder/macros.rs
ddtelemetry-ffi/src/lib.rs
examples/ffi/CMakeLists.txt
examples/ffi/telemetry.c
profiling-ffi/Cargo.toml
profiling-ffi/src/lib.rs
windows/build-artifacts.ps1
windows/libdatadog.csproj

* Expose telemetry-ffi from profiling-ffi
* Add a feature flag to disable it if necessary
* Expand telemetry builder macros to generate declarations from them with cbindgen
* Add a telemetry C example

(profiling-ffi) Expose telemetry through profiling ffi

---

ddcommon-ffi/cbindgen.toml
examples/ffi/exporter.cpp
examples/ffi/telemetry_metrics.c

This PR introduces a new `DDOG_CHARSLICE_C_BARE` helper, as well as undoes the change to `DDOG_CHARSLICE_C` from
https://github.com/DataDog/libdatadog/pull/305/files#diff-5c00b9c49c81bf0d0a754e0bcc6e0add4fe849bf0ea4a4d1ebfac8f698150f0b
There are now two helpers: `DDOG_CHARSLICE_C` that includes the `(ddog_CharSlice)` cast and `DDOG_CHARSLICE_C_BARE` which doesn't.
In a nutshell @bwoebi explained to me that on Windows there's times where you need to use `(ddog_CharSlice) {.ptr = ..., .len = ...}` and others where you need to use `{.ptr = ..., .len = ...}` and cannot include the cast.
Thus in #305 we tweaked the helper to never have `(ddog_CharSlice)`, with the intention of using `(ddog_CharSlice) DDOG_CHARSLICE_C(...)` some times, and `DDOG_CHARSLICE_C(...)` the other times.
But... this …

Introduce `DDOG_CHARSLICE_C_BARE` and undo change to `DDOG_CHARSLICE_C` helper

---

.github/labeler.yml
.github/workflows/test.yml
Cargo.lock
build-data-pipeline-ffi.sh
cmake/DataPipelineConfig.cmake.in
data-pipeline-ffi/Cargo.toml
data-pipeline-ffi/cbindgen.toml
examples/ffi/data-pipeline/CMakeLists.txt
examples/ffi/data-pipeline/trace_exporter.c
windows/build-artifacts.ps1
windows/libdatadog.csproj

This PR fix the C code generation from Rust and add support to build the `data-pipeline` crate in CI.
For fun and profit

[data-pipeline] Fix ffi generation and Add CI build

---

bin_tests/src/bin/crashtracker_bin_test.rs
build-common/src/cbindgen.rs
crashtracker/src/crash_info.rs
examples/ffi/crashtracking.c
examples/ffi/exporter.cpp
profiling-ffi/cbindgen.toml
profiling-ffi/src/crashtracker.rs
profiling-ffi/src/exporter.rs
profiling/src/exporter/mod.rs

We have currently have an issue with different types sharing the same name in the C headers, but no being the same.
Cbindgen doesn't understand rust modules, so two types sharing the same name in different modules will be considered as the same for cbindgen.
The ffi currently manipulates two Endpoint types which are roughly equivalent
* ddcommon::Endpoint [code](https://github.com/DataDog/libdatadog/blob/9f4f3cf58f57763c9ef22c6930597c69d5e44ad2/ddcommon/src/lib.rs#L34), used as an opaque pointer in ffi for telemetry and the sidecar
* datadog_profiling_ffi::Endpoint [code](https://github.com/DataDog/libdatadog/blob/9f4f3cf58f57763c9ef22c6930597c69d5e44ad2/profiling-ffi/src/exporter.rs#L37) an repr(C) enum, which is passed through the ffi and eventually transformed into ddcommon::Endpoint …

Rename profiling-ffi Endpoint to ProfilingEndpoint/prof_Endpoint to remove confusion with ddcommon::Endpoint

---

ruby/Rakefile
ruby/spec/gem_packaging.rb

This PR adds an additional file permission validation step while building the libdatadog Ruby packages.
This is effectively the same as
https://github.com/datadog/dd-trace-rb/pull/3531 , and I'm adding it to avoid the same potential issue.
Avoid issue we ran into with `ddtrace` packaging.
N/A
Running `bundle exec rake package` will trigger the packaging of the Ruby packages, and you'll see the test running. To see it failing, `chmod` the `.rb` files to something other than 644.

[NO-TICKET] Add validation for Ruby gem file permissions

---

.github/workflows/diff-proto-files.sh
.github/workflows/nightly-verify-proto-files.yml
.github/workflows/verify-proto-files.yml

Changes the diff of tracing protobuf files against the Datadog agent to use a fixed tag, and adds a nightly job against `main` to catch changes.
This kept _failing_ and cluttering up PRs with unnecessary warnings. We still want to check that no bad differences are introduced, and keep track of upstream changes, hence the nightly job.
Nope.
Have been tested manually by triggering the actions.

Validate protobuf file diffs on PRs against a fixed tag and add nightly

---

spawn_worker/src/unix/spawn.rs

Fix a panic when spawning the sidecar worker.
Discovered while running a linux/amd64 build of dd-trace-php in a Docker container on a Mac M1 machine.
panic details:
```
thread '<unnamed>' panicked at 'No such file or directory (os error 2)', libdatadog/spawn_worker/src/unix/spawn.rs:441:21 stack backtrace:
0: rust_begin_unwind
at /rustc/eb26296b556cef10fb713a38f3d16b9886080f26/library/std/src/panicking.rs:593:5
1: core::panicking::panic_fmt
at /rustc/eb26296b556cef10fb713a38f3d16b9886080f26/library/core/src/panicking.rs:67:14
2: core::panicking::panic_display
at /rustc/eb26296b556cef10fb713a38f3d16b9886080f26/library/core/src/panicking.rs:150:5
3: spawn_worker::unix::spawn::SpawnWorker::do_spawn::{{closure}}
at /rustc/eb26296b556cef10fb713a38f3d16b9886080f26/library/core/src/panic.rs:56:9 …
```

Fix a panic when spawning the sidecar worker.

---

ddtelemetry/src/data/metrics.rs
ddtelemetry/src/metrics.rs
sidecar/src/interface.rs

This PR adds 2 Sidecar actions:
- `RegisterTelemetryMetric`: Register a new Telemetry metric
- `AddTelemetryMetricPoint`: Send a Telemetry metric point
This is required for the clients to send telemetry metrics (https://datadoghq.atlassian.net/browse/AIT-4125)
This is my first PR on libdatadog, and also the first time I write Rust code 😄 
This is tested by a test in a dd-trace-php PR (https://github.com/DataDog/dd-trace-php/pull/2577)

Add 2 Sidecar actions to register and push metrics

---

profiling/src/exporter/mod.rs
profiling/src/internal/profile.rs
profiling/src/internal/upscaling.rs
profiling/tests/form.rs

This removes redundant imports in the `profiling/` subdir.
Miri was complaining about these for me on nightly. 
It is probable other crates will have similar warnings. I only worked on `profiling/`'s.
Everything should compile and work as normal, this should be a net-zero change.

style(profiling): remove redundant imports

---

.github/workflows/verify-proto-files.yml
trace-protobuf/src/pb.rs
trace-protobuf/src/pb/stats.proto

Updates the protobuf stats.pb file with a new trace root field to match the Datadog Agent files.

Update protobuf files for stats for new trace root field

---

run-package-tests.ps1
tests/run-package-tests.ps1
tests/windows_package/windows_package.vcxproj
tests/windows_package/windows_package.vcxproj.filters

Add a project package check test.
We would like to validate that the generated Nuget package can be used to build a C++ (Visual Studio) project.
/!\ You must have VS, and MSBuild tools installed
- Create an `artifacts` folder and put the libdatadog `nupkg` file in it.
- Start a Powershell command line
- run the script `run-package-tests.ps` : `. .\tests\run-package-tests.ps1 -ArtifactsPath <path to the artifacts folder>

Add windows_package project

---

crashtracker/src/crash_handler.rs

Reworks the signal handler chaining code to properly handle cases where the signal was manually raised.
The example in `crashtracker.c` would fail to call the underlying handler in the case of a `raise(SEGV)` call, and then would continue past what ought to be a core-dump.  Now we don't do that anymore.
The POSIX signal infra is 🤯 
`crashtracking.c` now works the way its expected to.

[crashtracker] Chain signal handlers 

---

.github/actions/cache/action.yaml
.github/workflows/test.yml
build-profiling-ffi.sh
examples/ffi/CMakeLists.txt
profiling-ffi/.cargo/config.toml
windows/build-artifacts.ps1
windows/libdatadog.props

This PR fixes a linking with for Windows native libraries that link against the VC runtime statically that was introduced by [the PR adding telemetry.
](https://github.com/DataDog/libdatadog/pull/339)
The .NET profiler links against the VC runtime statically so it can be deployed easily everywhere (on windows) without the customers having to install additional stuffs (VC runtime for example).
The PR that introduced the telemetry in the datadog_profiling lib, brought some new dependencies. Now the .NET profiler is unable to successfully build on windows.
The build produces this linking error:
```
datadog_profiling.lib(windows.o) : error LNK2019: unresolved external symbol __imp_strncpy referenced in function get_os_release [D:\a\libdatadog\libdatadog\examples\ffi\build_static\telemetry_metr …
```

Fix linking issue on Windows

---

.github/actions/cache/action.yaml

Adds the `Cargo.lock` file as part of the CI cache hash key.
CentOS 7 cross builds are close to the limit of the runner size, and changes in locked versions, even though there have been no changes in the `Cargo.toml` files easily tips the build over.

Use Cargo.lock file as part of the CI cache hash

---

trace-protobuf/build.rs
trace-protobuf/src/pb.rs

Avoids serializing empty extra fields in the spans.
A lot of code that expects v0.4 MessagePack don't respond well to unknown fields being present, even if they are empty. This allows the current messages to be used for v0.4 as well as v0.7 without adding the extra fields.

Don't serialize empty extra fields in spans

---

.github/workflows/test.yml

Removes an unused tools cache directory on the GitHub runner to make more space for cross compilation. Roughly 10GB is reclaimed.
Cross compilation is living close to the limit of the available disk space on the GitHub runner and keeps failing intermittently.
Thanks to @morrisonlevi that pointed me to this [discussion](https://github.com/orgs/community/discussions/25678#discussioncomment-5242449)
CI all the things...

Remove unused tools cache to make more space for cross

---

crashtracker/libdatadog-crashtracking-receiver.c

This just modifies a line in the crashtracker_receiver example application so that it uses the currect enum.
"Dive" by Tycho.  Oh wait, I thought it said "inspiration."  Well whatever.
This is mostly just for documentation/example.
This doesn't change the behavior of crashtracker in any way.

nit:  use correct type in crashtracker example

---

profiling-ffi/src/profiles.rs
profiling-replayer/src/main.rs
profiling/src/internal/profile.rs

Adds a `.into` method to the FFI error types to auto convert from Rust Error types, and then uses that to make cleaner error handling possible in the FFI functions.
The old way had cruft and was hard to read.  This is nicer.

[profiling] Refactor FFI implementation to simplify error handling

---

crashtracker/src/crash_info.rs
examples/ffi/crashinfo.cpp
profiling-ffi/src/crashtracker/crash_info.rs

Adds an API to set the timestamp for a crashinfo object
We didn't have one, and .Net needed it.

[crashtracking] Add set_timestamp API

---

ddtelemetry/src/config.rs
ddtelemetry/src/worker/builder.rs
ddtelemetry/src/worker/mod.rs
ddtelemetry/src/worker/scheduler.rs
sidecar/src/interface.rs

AppInstance is apparently cloned each time when extracted from the Shared<ManualFuture<AppInstance>>.
Not having the guard telemetry_metrics HashTable in an Arc<> will cause the "already inserted" checks to always fail. And thus leak memory.
Also allow the telemetry worker to have a mode where it's continuing execution after a start-stop cycle, otherwise it won't send any more metrics afterwards.

Fix leaking metrics in the sidecar

---

tools/sidecar_mockgen/README.md
tools/sidecar_mockgen/src/lib.rs

On mac symbol sizes are not known and underscore prefixed.
This allows the sidecar to not crash when built as a shared php extension.

Fix sidecar_mockgen for mac

---

.github/workflows/test.yml
serverless/src/main.rs
trace-mini-agent/src/env_verifier.rs

Fixes a test in the `datadog-trace-mini-agent` that failed spuriously.
Flaky tests are bad™
Only setting the timeout to 0 ms is not enough, and there was a race in the test between the dns lookup and the timeout that intermittently failed the test (most likely on Windows).

Make verify timeout test in datadog-trace-mini-agent trigger timeout

---

data-pipeline-ffi/src/trace_exporter.rs
data-pipeline/src/trace_exporter.rs

Just some minor changes to the TraceExporter.
- Added some tests around the `From` trait implementations for `TracerTags`. These were already tested indirectly. 
- Tweaked the unit tests to test the end result of calling the builder rather than the values of the builder struct fields.
- Changed `no_proxy` to `use_proxy` to be (possibly) clearer and added necessary default trait impl for the builder.
- Made the TracerTag fields on `TraceExporterBuilder` non-optional since they weren't actually optional. 
I incorrectly started to work on TraceExporter for APMSP-1020 before I was informed we should be implementing that ticket in the sidecar's trace export logic for now. (We'll address implementing in TraceExporter later). 
Unit tests are in place

Minor adjustments to the data-pipeline/TraceExporter

---

ddcommon-ffi/src/error.rs
ddtelemetry-ffi/src/builder.rs
ddtelemetry-ffi/src/builder/expanded.rs
ddtelemetry-ffi/src/lib.rs
ddtelemetry-ffi/src/worker_handle.rs
examples/ffi/telemetry.c
examples/ffi/telemetry_metrics.c
sidecar-ffi/src/lib.rs
sidecar-ffi/tests/sidecar.rs

Moves the `MaybeError` type from the `ddtelemetry-ffi` crate to the `ddcommon-ffi` crate, and changes it to use the `ddcommon-ffi::Error` type.
It's a nice convenience type that we want to usein the `data-pipeline-ffi`, and I don't understand why it didn't use the `ddcommon-ffi::Error` type.

Move MaybeError from ddtelemetry-ffi to ddcommon-ffi

---

spawn_worker/src/unix/spawn.rs

Assigning `argv.items[]` directly does not update `argv.ptrs[]`, causing an use-after-free.

Fix use-after-free in non-fdexec spawn_worker config

---

bin_tests/src/bin/crashtracker_bin_test.rs
crashtracker/src/api.rs
crashtracker/src/collectors.rs
crashtracker/src/configuration.rs
crashtracker/src/crash_handler.rs
crashtracker/src/lib.rs
crashtracker/src/receiver.rs
crashtracker/src/telemetry.rs
examples/ffi/crashtracking.c
profiling-ffi/src/crashtracker/datatypes.rs

Combines the "should we collect stack traces" and "should we symbolize them" into one enum
The current setup confused @ivoanjo. Hopefully this is clearer.
Naming things is hard. Feel free to suggest better names.

[crashtracker] Simplify the stack collection options

---

crashtracker/libdatadog-crashtracking-receiver.c
examples/ffi/crashtracking.c
examples/ffi/profiles.c

Fixes the format to work with non null terminated strings
It was wrong before

[crashtracker] fix fprintf formal string in receiver binary

---

bin_tests/src/bin/crashtracker_bin_test.rs
crashtracker/src/api.rs
crashtracker/src/configuration.rs
crashtracker/src/receiver.rs
crashtracker/src/telemetry.rs
profiling-ffi/src/crashtracker/datatypes.rs

Allows the client to specify which files to record, rather than hard coding it.
Previously, we had hardcoded to use `/proc/meminfo` and `/proc/cpuinfo` as the additional files.  The client may not want these, or may want others.  Give them the choice.

[crashtracker] Take a user defined list of additional files

---

.codecov.yml
.github/workflows/coverage.yml

This PR adds a new workflow file to generate code coverage reports and upload the results to codecov. Once the first report is uploaded each PR will have a comment showing the diff with the previous state. The diff will present changes in the following components:
- crashtracker
- data-pipeline
- data-pipeline-ffi
- ddcommon
- ddcommon-ffi
- ddtelemetry
- ipc
- profiling
- profiling-ffi
- serverless
- sidecar
- sidecar-ffi
- spawn_worker
- trace-mini-agent
- trace-normalization
- trace-obfuscation
- trace-protobuf
- trace-utils

Add code coverage workflow.

---

Cargo.lock
Cargo.toml

This PR bumps the libdatadog version to 9.0.0 in preparation for release.
We're going from 8.0.0 to 9.0.0 because of backwards incompatable changes in the crashtracker api.
Release libdatadog 9.0.0.

Bump libdatadog version to 9.0.0 in preparation for release

---

.github/PULL_REQUEST_TEMPLATE.md

This makes the change which was done in early April for many other public repos at Datadog.  There is no longer an owner for this workflow, so the checkbox does nothing.
Conformance with internal policies and guidelines
I think this is an important part of the overall workflow and release process, but given that such an escalation has no owner, the checkbox is even more toothless than it was before.
Try to leak a credential and see what happens.  (kidding)

[ASEC-131] Remove reference to nonexisting team

---

ruby/Rakefile
ruby/lib/libdatadog/version.rb

This PR includes the changes documented in the "Releasing a new version to rubygems.org" part of the README: https://github.com/datadog/libdatadog/tree/main/ruby#releasing-a-new-version-to-rubygemsorg
(It's also very similar to the v7.0.0 release PR).
It also includes a tiny paper cut fix: it disables the Rake `build` task which is the default way to package a Ruby gem, since we have our own custom packaging steps in the `Rakefile`.
Enable Ruby to use libdatadog v9.0.0.
We ended up not packaging the previous release (v8) for Ruby, so we're directly jumping from v7 to v9.
I've tested this release locally using the changes in https://github.com/DataDog/dd-trace-rb/pull/3627 .
As a reminder, new libdatadog releases don't get automatically picked up by dd-trace-rb, so the PR that bumps the …

[PROF-9742] Package libdatadog v9.0.0 for Ruby

---

.config/nextest.toml
.github/workflows/coverage.yml
.github/workflows/miri.yml
.github/workflows/test.yml
README.md
crashtracker/src/api.rs
ddcommon-ffi/src/slice.rs
ddcommon-ffi/src/vec.rs
ddtelemetry-ffi/src/lib.rs
ddtelemetry/src/config.rs
ddtelemetry/src/metrics.rs
ipc/src/platform/unix/mod.rs
profiling-ffi/src/exporter.rs
profiling-ffi/src/profiles.rs
profiling/src/api.rs
profiling/src/collections/identifiable/mod.rs
profiling/src/internal/observation/observations.rs
profiling/src/internal/observation/trimmed_observation.rs
profiling/src/internal/profile.rs
profiling/src/pprof/proto.rs
sidecar-ffi/tests/sidecar.rs
sidecar/src/log.rs
spawn_worker/src/unix/fork.rs

This PR does the following:
* Adds the `nextest` test runner and configuration to run _single threaded_ tests separately.
* Adds test result reporting as [checks to the PR](https://github.com/DataDog/libdatadog/actions/runs/9001508636#summary-24727897494)
* Renames the modules for single threaded tests to `single_threaded_tests`, so they can be easily run separately with `nextest`.
* Removes the use of `ignore` to separate out single threaded tests.
* Adds a `skip_root_tests` module name for tests (that were previously ignored 🤷🏼‍♂️) that can't run as `root` on GitLab CI.
* Changes the module name for most other tests to `tests` for consistency and easy skipping when building with `cross`, which doesn't support `nextest`.
* Tests were using `skip` as a way to separate out different test …

Run tests with nextest and publish results

---

profiling/src/internal/profile.rs
profiling/src/internal/upscaling.rs

Propagates errors from unwrap/expect calls instead of panicking right away. 
These might help reducing crashes from our profilers. 
`cargo test`

[PROF-9744] Propagate errors from expect calls

---

.github/workflows/weekly-verify-proto-files.yml

Moves the nightly validation of the protobuf files against Datadog agent `master` to a weekly cadence.
Changes to the protobuf files can't be reflected in `libdatadog` until there is a stable tag that the PR validation can compare against, and the Datadog agent doesn't release that often, so we don't need to be reminded every night about it.

Move nightly Datadog agent protobuf validation to weekly

---

crashtracker/src/crash_info.rs
crashtracker/src/stacktrace.rs

Skips serializing unset fields in the crashtracker
Currently, we serialize empty fields as `null`, which leads to much larger serialized jsons than necessary.  Not doing this saves bytes on the wire, and makes things easier to read.
Using the `crashtracking.c` test example.  In this case the change is not huge, but its more noticeable in larger examples.
Before: 
```json
{
"additional_stacktraces": {},
"counters": {
"not_profiling": 0,
"serializing": 0,
"collecting_sample": 0,
"unwinding": 0
},
"files": {},
"metadata": {
"profiling_library_name": "crashtracking-test",
"profiling_library_version": "12.34.56",
"family": "crashtracking-test",
"tags": []
},
"os_info": {
"os_type": "Macos",
"version": {
"Semantic": [
13,
6,
6
]
},
"edition": null, …
```

[crashtracker] Don't serialize unset fields

---

crashtracker/src/api.rs
crashtracker/src/collectors.rs
crashtracker/src/configuration.rs
crashtracker/src/crash_handler.rs
crashtracker/src/receiver.rs

Restores the option to collect symbols in process that was removed in https://github.com/DataDog/libdatadog/pull/401
I removed it because I thought nobody was using it. Turns out Python was.  Putting it back in.
Modified `crashtracker.c` to use the new enum, and got this output
```json
{
"counters": {
"unwinding": 0,
"not_profiling": 0,
"collecting_sample": 0,
"serializing": 0
},
"metadata": {
"profiling_library_name": "crashtracking-test",
"profiling_library_version": "12.34.56",
"family": "crashtracking-test",
"tags": []
},
"os_info": {
"os_type": "Macos",
"version": {
"Semantic": [
13,
6,
6
]
},
"edition": null,
"codename": null,
"bitness": "X64",
"architecture": "arm64"
},
"siginfo": {
"signum": 11,
"signame": "SIGSEGV"
},
"stacktrace": [
{ …
```

[crashtracker] Add option to collect symbols in process

---

sidecar/src/log.rs
sidecar/src/service/runtime_info.rs

Fixing max() in max_level_hint().
And properly dropping the telemetry worker:
When the runtime is shutdown with pending apps, it will send Stop, but never actually shutdown the telemetry instances. This regressed with d1fb3bc934e4b51b2ba1cb45818717351ad43b0. Now we simply drop the telemetry handle, which implicitly stops the worker as well causes the worker to be joined properly.
At least this led to the occasional deadlocked sidecar.

Fix telemetry shutdown and log max filter

---

data-pipeline/src/trace_exporter.rs
sidecar/src/self_telemetry.rs
sidecar/src/service/tracing/trace_flusher.rs
trace-mini-agent/src/trace_flusher.rs
trace-mini-agent/src/trace_processor.rs
trace-utils/src/lib.rs
trace-utils/src/send_data.rs
trace-utils/src/trace_utils.rs
trace-utils/src/tracer_header_tags.rs

This PR splits the `tracer_utils` into smaller parts and collects metrics for:
* trace_api.requests.
* trace_api.errors.
* trace_api.responses.
These metrics are then sent by the "self telemetry" worker of the sidecar.

Collect some of the `trace_api.*` metrics in the trace flusher

---

.github/CODEOWNERS

Gives co-ownership of the sidecar to @DataDog/libdatadog-apm and @DataDog/libdatadog-php 
Sidecar does not currently have any code ownership.

Make PHP and common components teams co-owners of the sidecar

---

.github/workflows/test.yml

The same error was discovered and fixed by in https://github.com/nextest-rs/nextest/issues/1493
Remove hack.

Update cargo nextest and remove the compile fix

---

sidecar-ffi/src/lib.rs
sidecar/src/service/blocking.rs

Replace the `SidecarTransport` type alias by a real struct that handles reconnection.
This is handled in the Rust code so that sidecar's clients (like the PHP tracer) can use the SidecarTransport in a thread safe way.
In the PHP tracer, the reconnection was previously done in the C code, but was not thread safe.

Allow the SidecarTransport to recreate its underlying transport

---

trace-utils/src/trace_utils.rs

There's an interesting tidbit of information in the documentation of dedup_by:
> The elements are passed in opposite order from their order in the slice, so if same_bucket(a, b) returns true, a is removed.
So, we were adding the data to a.tracer_payloads ... and then a gets dropped. Awesome, we just successfully dropped everything but one value.
On top of that, have a size restriction for the possible payload size, to ensure we'll never exceed it.

Fix coalescing send data

---

profiling/src/collections/identifiable/string_id.rs
profiling/src/internal/profile.rs
profiling/src/internal/upscaling.rs

Resolves a TODO. Use `internal::Label` instead of `pprof::Label` to make it easier to fuzz test. Even though `pprof::Label` can also derive `bolero_generator::TypeGenerator` guarded by `cfg(test)`, it would be best to keep internal things internal.
Also, this lets us use `pprof::Label` only when returning pprof.
TODO
`cargo nextest run`

[profiling] use internal Label instead of pprof::Label

---

profiling/src/internal/profile.rs

`sample_types` has a constant length. Save some bytes by using Boxed slice instead of Vec.

Use Box<[ValueType]> instead of Vec<ValueType>

---

sidecar/src/self_telemetry.rs
sidecar/src/service/tracing/trace_flusher.rs
trace-mini-agent/src/trace_processor.rs
trace-utils/Cargo.toml
trace-utils/src/send_data.rs
trace-utils/src/trace_utils.rs
trace-utils/src/tracer_header_tags.rs

Adds support for sending the following metrics:
- trace_api.bytes
- trace_chunks_sent
- trace_chunks_dropped
Aside from the introduction of those new metrics a small refactor has been done on send_data.rs in order to address some technical debt from previous PRs. This changes can be summarized in:
- Limit visibility of `SendData` fields.
- Add default trait implementation for `SendDataResult`.
- Add tests for both `TraceHeaderTags` and `SendData`.
In order to turn the sidecar on by default for PHP there is the need to support those metrics.

Add metrics

---

sidecar-ffi/src/lib.rs
sidecar/src/service/blocking.rs
sidecar/src/service/sidecar_interface.rs
sidecar/src/service/sidecar_server.rs

ShmHandle.size() is an upper bound of the size rather than the actual size. This confuses the TraceFlusher and will thus flush for every single request.

Transmit size of data in send_trace_v04_shm

---

sidecar-ffi/src/lib.rs
sidecar/src/service/blocking.rs
sidecar/src/service/sidecar_interface.rs
sidecar/src/service/sidecar_server.rs
sidecar/src/service/tracing/trace_flusher.rs
sidecar/src/service/tracing/trace_send_data.rs

It's important for reliability in testing; also parametric tests do actually rely on that being available.

Add explicit synchronous flush capability to sidecar

---

Cargo.lock
trace-mini-agent/Cargo.toml

Bumps Serverless Mini Agent Version to 0.4.0.
`mini_agent_version` span tag should reflect the current version of the package: https://github.com/DataDog/libdatadog/blob/78551812d4ab0940e29e863b866e29fd9ab20e45/trace-mini-agent/src/config.rs#L65
Setting correctly for upcoming release of version 0.4.0.
Build mini agent locally
Deploy Azure Function with mini agent binary in root path
Set DD_MINI_AGENT_PATH to /home/site/wwwroot/datadog-serverless-trace-mini-agent

[Serverless Mini Agent] Bump Serverless Mini Agent Version to 0.4.0

---

examples/ffi/crashinfo.cpp

Explicitly uses `<string>` as a header for `crashinfo.cpp`.
Windows CI was failing.  https://github.com/DataDog/libdatadog/actions/runs/9402609405/job/25900083549 This looked like it might fix the error 

Explicitly use the <string> header in crashinfo.cpp

---

data-pipeline/src/trace_exporter.rs
sidecar/src/service/sidecar_server.rs
trace-mini-agent/src/trace_processor.rs
trace-utils/Cargo.toml
trace-utils/src/trace_utils.rs

Turns out the agent ignores the root_span_tags for v0.7 anyway. This is useful to coalesce chunks with common data, allowing us to actually save us from doing redundant requests. As it was currently, the agentful trace sender always sent one trace per request, instead of merging them.
We also skip normalization and rely on the agent to do it, for sake of consistency with other tracers and reduce the potentially duplicated work across tracer and agent. We may change that back in future, but for now we've determined it to be the easiest way to work, also with respect to normalization-unaware testing.

Skip normalization & obfuscation and coalesce instead

---

trace-utils/src/trace_utils.rs

normalize_trace is what's actually normalizing values of spans.
normalize_chunk just moves (and that's wanted) values from spans to chunks.

Fix the wrong thing being not normalized

---

bin_tests/src/bin/crashtracker_bin_test.rs
crashtracker/src/api.rs
crashtracker/src/configuration.rs
crashtracker/src/crash_handler.rs
crashtracker/src/receiver.rs
crashtracker/src/telemetry.rs
profiling-ffi/src/crashtracker/datatypes.rs

Adds a `wait_for_receiver` flag to the collector config.
In some cases, the client may wish the collector to wait until the receiver has uploaded before finishing crashing, e.g. to keep the pod alive, or to allow out-of-process symbolization.  In other cases, they may wish the process to die immediately.  This lets the client decide. 

[crashtracker] Add a 'wait_for_receiver' param, and use it in both the stdin and unix socket cases

---

crashtracker/src/receiver.rs
ipc/src/sequential.rs
ipc/tarpc/tarpc/src/client.rs
ipc/tarpc/tarpc/src/context.rs
ipc/tarpc/tarpc/src/server.rs
ipc/tarpc/tarpc/src/server/limits/channels_per_key.rs
ipc/tarpc/tarpc/src/trace.rs
profiling-ffi/src/profiles.rs
sidecar-ffi/src/lib.rs
sidecar/src/service/serialized_tracer_header_tags.rs

Removes redundant imports. For example, `TryFrom`, `TryInto`, and `Unpin` are all part of the 2021 prelude and do not need to be imported.
Some commands will warn about these, was annoying having them in my terminal output.
Nope.
Should only be a style change, everything should work as before (no change in testing).

style: avoid redundant imports

---

Cargo.toml

Switches from `debug = 1` to `debug = "line-tables-only"`.
Was looking to try and shrink the builds for PHP (and libdatadog by extension) and noticed that since we're on Rust 1.71 now, we can make this small change.
For more information about `1` vs `line-tables-only`, see: https://blog.rust-lang.org/2023/06/01/Rust-1.70.0.html#named-levels-of-debug-information.
Everything should be the same.

build: use `debug = "line-tables-only"`

---

.github/workflows/verify-proto-files.yml
trace-protobuf/src/pb.rs
trace-protobuf/src/pb/stats.proto

Updates protobuf files to match Datadog Agent.

Update protobuf files for stats for new trilean type

---

ipc/src/platform/unix/channel.rs
ipc/src/platform/unix/channel/async_channel.rs
ipc/src/platform/unix/channel/metadata.rs
ipc/src/platform/unix/message.rs

This has effectively been never working - it probably got added in long times past, before unidirectional sending was added. There's no ack, and thus it would simply leak and stay unclosed forever.
And the functionality is simply not needed. It's not like linux would close file descriptions as long as they're referenced in sendmsg buffers.

Drop fd acking in sidecar transport

---

.github/workflows/lint.yml
profiling-ffi/src/lib.rs
spawn_worker/src/win32.rs

Run clippy on windows, it is currently done in [gitlab](https://gitlab.ddbuild.io/DataDog/apm-reliability/libddprof-build/-/blob/main/.gitlab-ci.yml?ref_type=heads#L156). This allows us to remove the gitlab job to run clippy only once.
We need to run clippy on windows to check windows specific code

Run clippy on windows in CI

---

profiling/src/internal/profile/fuzz_tests.rs

[profiling] Turn off slow fuzz tests for miri

---

trace-utils/src/trace_utils.rs

This comment should have been removed in #471

Remove unnecessary TODO comment from trace_utils.rs

---

Cargo.lock
LICENSE-3rdparty.yml
trace-protobuf/Cargo.toml
trace-protobuf/build.rs
trace-protobuf/src/lib.rs
trace-protobuf/src/pb.rs
trace-protobuf/src/pb_test.rs

It skips the serialization of the field `Span.error` if the value is 0 as it's done by tracers (at least [.net](https://github.com/DataDog/dd-trace-dotnet/blob/f4ba8212dc62f8a61e947086202ba21f2fdd0bb2/tracer/src/Datadog.Trace/Agent/MessagePack/SpanMessagePackFormatter.cs#L199) and [PHP](https://github.com/DataDog/dd-trace-php/blob/master/ext/serializer.c#L1360-L1362))

Skip serialization of field Span.error if equals to 0

---

Cargo.lock
trace-protobuf/Cargo.toml
trace-protobuf/build.rs
trace-protobuf/src/pb.rs
trace-utils/src/stats_utils.rs

Adds `#[serde(default)]` for `peer_tags` and `is_trace_root` to prevent errors when stats payloads do not include these fields.
https://datadoghq.atlassian.net/browse/SVLS-4933
Deserialization errors when sending trace stats from Azure Functions and Google Cloud Functions.
```
2024-06-17T17:56:38Z   [Information]   [2024-06-17T17:56:37Z ERROR datadog_trace_mini_agent::http_utils] Error deserializing trace stats from request body: Error deserializing stats from request body: missing field `PeerTags`
```
```
2024-06-17T18:58:42Z   [Information]   [2024-06-17T18:58:42Z ERROR datadog_trace_mini_agent::http_utils] Error deserializing trace stats from request body: Error deserializing stats from request body: missing field `IsTraceRoot`
```
- Build mini agent locally
- Deploy Azure Function or …

[Serverless Mini Agent] Add Default Values for peer_tags and is_trace_root when Generating Trace Metrics

---

Cargo.lock
trace-mini-agent/Cargo.toml

Bumps Serverless Mini Agent Version to 0.4.2.
Setting correctly for upcoming release of version 0.4.2.
- Build mini agent locally
- Deploy Azure Function or Google Cloud Function with mini agent binary in root path
- Set `DD_MINI_AGENT_PATH`
- Azure: `/home/site/wwwroot/datadog-serverless-trace-mini-agent`
- Google: `/workspace/datadog-serverless-trace-mini-agent`

[Serverless Mini Agent] Bump Serverless Mini Agent Version to 0.4.2

---

data-pipeline/src/trace_exporter.rs
sidecar/src/service/sidecar_server.rs
sidecar/src/tracer.rs
trace-mini-agent/src/trace_processor.rs
trace-utils/src/lib.rs
trace-utils/src/send_data/mod.rs
trace-utils/src/test_utils.rs
trace-utils/src/trace_utils.rs
trace-utils/src/tracer_payload.rs

Add support for sending v0.4 encoded traces to the agent.

Add support for sending v0.4 traces.

---

ddcommon/src/entity_id/mod.rs
ddcommon/src/entity_id/unix/mod.rs
ddcommon/src/lib.rs

Implement the [new container origin spec ](https://datadoghq.atlassian.net/wiki/spaces/CONTP/pages/3731783774/New+Origin+Detection+Spec+for+Traces+and+DogStatsD) by:
- Changing `cid` prefix to `ci`
- Supporting the External env variable

[APMSP-1229] Implement new origin detection spec

---

README.md

Adds `cbindgen` and its required version to the readme to the requirements section.
Building C headers requires `cbindgen` which is not mentioned in the readme.
Ubuntu package of `cbindgen` is of an old version which does not work, producing cryptic errors.
None
N/A

DEBUG-2510 Document cbindgen dependency

---

ruby/Rakefile
ruby/lib/libdatadog/version.rb

This PR includes the changes documented in the "Releasing a new version to rubygems.org" part of the README: https://github.com/datadog/libdatadog/tree/main/ruby#releasing-a-new-version-to-rubygemsorg
(It's also very similar to the v9.0.0 release PR).
Enable Ruby to use libdatadog v10.0.0.
N/A
I've tested this release locally using the changes in DataDog/dd-trace-rb#3753 .

[PROF-10099] Package libdatadog v10.0.0 for Ruby

---

sidecar/src/config.rs

Broken by ce2afd981e994d9f3aa5b4c12e35cab9facee4e3, since when parse_uri starts returning a bogus uri, with the path put in the authority in hexadecimal form and the actual path empty. Sidestep that mess by not using parse_uri.

Fix sidecar logging

---

.github/workflows/test.yml
Cargo.lock
LICENSE-3rdparty.yml
ddcommon/Cargo.toml
ddcommon/src/connector/conn_stream.rs
ddcommon/src/connector/mod.rs
tools/docker/Dockerfile.build
trace-utils/Cargo.toml
trace-utils/src/stats_utils.rs

We were running into symbol issues with older rustls versions, see https://github.com/briansmith/ring/issues/1808.
Note that the new rustls version requires nasm to be installed on windows, so we install it in CI.

Bump rustls version to 0.23

---

Cargo.lock
Cargo.toml
ruby/Rakefile
ruby/lib/libdatadog/version.rb

Bump version numbers to v11.0.0
New release for ddprof
NA
NA

Bump version number to v11.0.0

---

ddsketch/src/lib.rs

Adds `DDSketch.count() -> f64` function which returns the number of points currently in the sketch.
For testing behavior like stats computation or datastreams, being able to assert that the bucketing into sketches works as intended would be helpful.
`cargo test`

[ddsketch] add DDSketch.count() -> f64 to return number of points in the sketch

---

crashtracker/src/crash_handler.rs

What it says on the tin.
Left a debug statement in by accident. 

[crashtracker] Remove debug print statement

---

trace-normalization/Cargo.toml

Fixes failures like this in dd-trace-php: https://app.circleci.com/pipelines/github/DataDog/dd-trace-php/16600/workflows/31d2931c-8a5b-449c-bc12-d911585b2ddb/jobs/4698215

Make bench file not need by pecl package

---

ruby/Rakefile

https://github.com/datadog/libdatadog/tree/main/ruby#releasing-a-new-version-to-rubygemsorg
The v11 version bump PR (#529) had already bumped the version itself, so I just needed to add the hashes.
Enable Ruby to use libdatadog v11.0.0.
N/A
I've tested this release locally using the changes in https://github.com/DataDog/dd-trace-rb/pull/3799 .

[PROF-10208] Package libdatadog v11.0.0 for Ruby

---

ddtelemetry/src/data/payloads.rs

Fixes app-started telemetry messages that don't include the "configuration" key. This key is required by the schema.
Failing system tests: https://github.com/DataDog/system-tests/pull/2785
System tests started failing once https://github.com/DataDog/dd-trace-php/pull/2757 was merged and telemetry messages were actually sent.

Tel v2 schema for app-started payload requires 'configuration'

---

crashtracker/src/receiver.rs
ddcommon/src/tag.rs
ddsketch/src/lib.rs
ipc/Cargo.toml
ipc/src/platform/mem_handle.rs
ipc/tarpc/tarpc/src/client.rs
ipc/tarpc/tarpc/src/serde_transport.rs
profiling/src/collections/string_table/mod.rs
profiling/src/collections/string_table/wordpress_test_data.rs
profiling/src/internal/profile/mod.rs
profiling/src/pprof/sliced_proto.rs
sidecar-ffi/Cargo.toml
sidecar/Cargo.toml
sidecar/src/service/tracing/trace_flusher.rs
spawn_worker/Cargo.toml
tests/spawn_from_lib/tests/spawn.rs
trace-mini-agent/src/http_utils.rs
trace-normalization/src/normalizer.rs

Most of the changes are one of the following
1. Indentation for lists in docs -> fixed by adding a new line and/or spaces
3. [Automatic checking of cfgs at compile-time](https://blog.rust-lang.org/2024/05/06/check-cfg.html) -> fixed by adding `check-cfg` under `[lints.rust.unexpected_cfgs]` in `Cargo.toml`
4. `allow(dead_code)`
Unblock CI for pending PRs

Fixes to make clippy version 1.80 happy

---

ddcommon-ffi/src/endpoint.rs
examples/ffi/crashtracking.c
profiling-ffi/cbindgen.toml
profiling-ffi/src/crashtracker/collector/datatypes.rs

Uses the `ddcommon::Endpoint` rather than the `profiling-ffi::exporter::Endpoint`.
We're trying to decouple the crashtracker and the profiler, this removes one of the final remaining links.
This is a breaking change for users of the API. 
Eventually, the `profiling-ffi` endpoint type itself should probably be unified with this. 
Compile and run the modified example file.
[PROF-10245]
[PROF-10245]: https://datadoghq.atlassian.net/browse/PROF-10245?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[crashtracker] Use common Endpoint to further decouple from profiler

---

Cargo.lock
serverless/src/main.rs
trace-mini-agent/Cargo.toml
trace-mini-agent/src/config.rs
trace-mini-agent/src/env_verifier.rs
trace-mini-agent/src/trace_processor.rs
trace-utils/src/trace_utils.rs

Adds `_dd.mini_agent_version` span tag to all spans from Azure Functions, Google Cloud Functions, and Azure Spring Apps.
https://datadoghq.atlassian.net/browse/SVLS-5167
Previously there was an `aas.environment.mini_agent_version` span tag added for Azure Functions. This tag is being replaced for a span tag that will be applied in all relevant environments: Azure Functions, Google Cloud Functions, and Azure Spring Apps.
Set `DD_MINI_AGENT_VERSION` environment variable to the package version of `datadog-serverless-trace-mini-agent`. Then reference this environment variable in the packages that are run from `datadog-serverless-trace-mini-agent`.
Set the version of `datadog-trace-mini-agent` to match the version of libdatadog so the Serverless Mini Agent version is only managed in a single …

[Serverless Mini Agent] Add _dd.mini_agent_version tag to all spans for Azure Functions, Google Cloud Functions, and Azure Spring Apps

---

Cargo.lock
serverless/Cargo.toml

Bumps Serverless Mini Agent Version to 0.6.0.
Upcoming release of version 0.6.0.
- Build mini agent locally
- Azure Functions
* Deploy Azure Function or Google Cloud Function with mini agent binary in root path
* Set `DD_MINI_AGENT_PATH`
- Azure: `/home/site/wwwroot/datadog-serverless-trace-mini-agent`
- Google: `/workspace/datadog-serverless-trace-mini-agent`
- Spring Apps
* Build an Azure Spring App with persistent storage
* ssh into the Azure Spring App instance and upload the Datadog Java Tracer and Serverless Mini Agent
* Add -javaagent:/persistent/dd-java-agent.jar to the JVM options
* Set DD_TRACE_TRACER_METRICS_ENABLED to true
* Start the Serverless Mini Agent

[Serverless Mini Agent] Bump Serverless Mini Agent Version to 0.6.0

---

Cargo.lock
sidecar/Cargo.toml
sidecar/src/setup/windows.rs
sidecar/src/windows.rs

This avoids permission conflicts with other processes sharing the same Session ID on Windows.

Use the Windows User ID as sidecar identifier instead of the Session ID

---

sidecar/src/config.rs
sidecar/src/entry.rs
sidecar/src/unix.rs

Support loading the appsec helper in sidecar

Support loading appsec helper in sidecar

---

sidecar-ffi/tests/sidecar.rs
spawn_worker/src/unix/fork.rs

Fix CI after update to rust 1.80.

Fix sidecar tests testing handling of closed file descriptors

---

spawn_worker/src/trampoline.c

The appsec helper library has a call to dlopen() during constructors that may fail. Without clearing it, a call to dlerror() after a successful call to dlsym() will return the previous error message.
man 3 dlsym() says:
> The correct way to distinguish an error from a symbol whose value is NULL is to
> call  dlerror(3)  to clear any old error conditions, then call dlsym(), and then call dlerror(3) again, saving its
> return value into a variable, and check whether this saved value is not NULL.

Fix error check in trampoline.c

---

ruby/spec/gem_packaging.rb

This PR adds a check during packaging of Ruby releases that all symbols exported in the libdatadog shared library are correctly prefixed.
This allows us to catch any new unprefixed symbols, and thus we're able to rely on libdatadog not exporting symbols that would clash with other libraries that may be loaded in the same Ruby VM.
N/A
You can observe the new check running with `docker-compose run push_to_rubygems`.
This is safe to call as it'll stop asking for credentials before actually publishing anything to rubygems.

[NO-TICKET] Validate that all public symbols are prefixed in Ruby releases

---

trace-mini-agent/src/stats_processor.rs
trace-utils/src/stats_utils.rs

Prevents seemingly unnecessary errors if a Serverless stats payload happens to not have any stats.
The payload definition in the go protobuf code seems to indicate that stats are allowed to be empty. And [that code](https://github.com/DataDog/datadog-agent/blob/main/pkg/trace/api/api.go#L525-L535) (`firstService` closure) is defensive about this possibility. Furthermore our `datadog.trace_agent.receiver.stats_buckets` metric has a minimum value of 0 so this apparently does happen and is handled as such by our systems.
The serverless agent is generating a bunch of noise when it receives these kinds of "empty" stats payloads from the node tracer.
Added a unit test to confirm that we are able to create stats payloads with these empty stats objects (and empty stats of stats... our naming is a …

[SVLS-5049] It is okay to have a stats payload without stats

---

Cargo.lock
serverless/Cargo.toml

Bumps serverless mini agent version up.
Releasing this new version
Here are the [changes since v0.6.0](https://github.com/DataDog/libdatadog/compare/sls-v0.6.0...aleksandr.pasechnik/sls-v0.6.1-pre-release?expand=1)
In addition to unit tests, this code was deployed to a test Azure Function.

[Serverless Mini Agent] bump version to 0.6.1

---

crashtracker/Cargo.toml
crashtracker/src/bin/crashtracker_receiver.rs

Builds a static binary for the crashtracker
Request from Node.
The binary is statically linked, and hence much larger than the dynamically linked C binary we currently generate.  If possible, using that one will save binary size.

[crashtracker] Build static binary

---

benchmark/run_benchmarks_ci.sh
trace-normalization/benches/normalization_utils.rs
trace-obfuscation/benches/benchmarks/credit_cards_bench.rs
trace-obfuscation/benches/benchmarks/redis_obfuscation_bench.rs
trace-obfuscation/benches/benchmarks/replace_trace_tags_bench.rs
trace-obfuscation/benches/benchmarks/sql_obfuscation_bench.rs
trace-utils/benches/deserialization.rs

This PR tries to stabilize the criterion micro benchmarks results. The reason why the benchmark result comment is so full of changes is that the batching and how the benchmarks are run has changed compared to `main`.
There is soo much noise in the results that they trigger false positives on almost every PR.
I have run the the benchmarks repeatedly on a separate PR #577 (that has no code changes), and only occasionally will there be a change in a benchmark result.

Stabilize criterion benchmark results

---

trace-normalization/src/normalize_utils.rs

This changes the in place normalization to directly manipulate the underlying `Vec` instance.
While working on stabilizing the benchmark results I looked at what allocated things on the heap, and came across this small change.
Nope.
The benchmarks and tests should cover it.

Normalize directly in the same String instance

---

ddtelemetry/src/worker/http_client.rs
tools/docker/Dockerfile.build

Otherwise we see spurious race conditions where the file is opened twice and one thread is overwriting to the start of the file.
And lock cbindgen version for CI.

Use append() for writing telemetry lock to file

---

ddcommon-ffi/src/endpoint.rs
ddcommon-ffi/src/slice.rs
ddcommon/src/lib.rs
sidecar-ffi/src/lib.rs
sidecar/src/agent_remote_config.rs
sidecar/src/config.rs
sidecar/src/dogstatsd.rs
sidecar/src/service/blocking.rs
sidecar/src/service/session_info.rs
sidecar/src/service/sidecar_interface.rs
sidecar/src/service/sidecar_server.rs
trace-utils/src/send_data/mod.rs
trace-utils/src/trace_utils.rs

I've decided to put it into Endpoint, as it has to be used at basically any place Endpoint is used.

Support x-datadog-test-session-token for parallel tests with the test agent

---

crashtracker-ffi/src/demangler/mod.rs

Skips the demangling test under miri.  It appears that miri changes the behavior of symbolic `demangle()` in a way that breaks the placement of the `*` character in the demangled function name.  Strictly speaking, the test is reflecting a novel incorrectness introduced in `demangle()` as the produced name is not just syntactically, but also semantically distinct from the original.
For discussion, here's the original prototype of the function as specified in the test.  It comes from a real internal function in C++.
```
bool
_M_futex_wait_until_steady(
unsigned *__addr,
unsigned __val,
bool __has_timeout,
chrono::seconds __s,
chrono::nanoseconds __ns);
```
And then here's the result:
```
bool
_M_futex_wait_until_steady(
unsigned __addr,                           // Hey, this is a value type …
```

Skip the demangle test under miri

---

ipc/src/platform/unix/channel/async_channel.rs

UnixStream::poll_read_ready may return Poll::Ready(Ok(())), which incidentally, when returned by an AsyncRead::poll_read function without further modification of buf, means that the channel was closed. The intended meaning is "immediately available", and thus we need to re-read.
This only can happen when epoll() is resumed between a recvmsg() call and the poll_ready_ready function being invoked, which may only happen in a multithreaded environment, which we recently switched to.
This PR reminded me why race conditions are so much fun.

Retry when poll_read_ready immediately succeeds in AsyncChannel

---

ipc/src/platform/unix/mem_handle.rs
spawn_worker/Cargo.toml
spawn_worker/src/unix/spawn.rs

WSL is a "Linux" environment, but it does not support the memfd_create syscall. Thus we fall back to other strategies here.

Implement fallback for when memfd is not available on Linux

---

crashtracker/src/receiver.rs

Rust stdlib UnixListener is not async by default unlike the tokio one. It did apparently not fail during manual testing, but CI showed it sometimes failing.
Explicitly making it set_nonblocking(true).

Fix accidental blocking socket in crashtracking

---

.github/workflows/miri.yml

This PR tells `proptest` to only run one test case when we are running the tests under `miri`.
Running `miri` is slow.
Watch the running time for `miri`.

Only run one proptest case when using miri

---

ddcommon/src/entity_id/unix/container_id.rs
ddcommon/src/entity_id/unix/mod.rs

Improve the miri job runtime by skipping some slow tests.

Improve miri job runtime

---

sidecar/src/entry.rs
spawn_worker/src/unix/spawn.rs

- Sidecar will leak some global structures, using LSAN there would either require an extensive suppressions list. For now we just opt to disable it. This avoids false positives in our testing we have to manually detect and ignore.
- Using an invalid log file should simply avoid sending it to the sidecar completely instead of failing there again, preventing two log messages for the same issue.
- Use _exit(0) instead of regular exit(0) when daemonizing to avoid sideeffects from atexit() handlers inherited from forking.

Fix log file and disable LSAN usage in sidecar

---

ruby/Rakefile
ruby/lib/libdatadog/version.rb

The ruby gem for libdatadog was still only setup for version 11. This PR prepares the release for version 12.
Keep things up to date.
N/A
We'll trigger the gem release process once this gets merged and will soon push a PR in dd-trace-rb to make it use the new gem.

[ruby] Prepare gem release for version 12

---

Cargo.lock
data-pipeline/Cargo.toml
data-pipeline/benches/main.rs
data-pipeline/benches/span_concentrator.rs
data-pipeline/benches/span_concentrator_bench.rs
data-pipeline/src/span_concentrator/aggregation.rs
data-pipeline/src/span_concentrator/mod.rs

Add benchmark to concentrator to allow future otpimizations
The concentrator is lacking some optimizations, this will make it easier to evaluate improvement.

Add benchmark for SpanConcentrator

---

remote-config/src/fetch/test_server.rs
tools/sidecar_mockgen/src/lib.rs

Looks like php may be built with certain optimizations causing some symbols to be resolved as ifunc. The object crate is not recognizing these as definition, but for our purposes, it is one.
Fixes part of Datadog/dd-trace-php#2831.

Consider ifunc symbols also defined

---

trace-utils/src/send_data/retry_strategy.rs

It has been observed that some of the send_data retry strategy logic can be flaky on the macOS github actions runners. This PR adds more time to the retry observation tolerances for these tests. Also, a bit more info was added to the relevant test assertions when a failure does occur. 
@bwoebi

improve assert failure message for send_data retry tests and increase tolerance for time measurements

---

.github/workflows/lint.yml
.github/workflows/test.yml
.github/workflows/verify-proto-files.yml
Cargo.toml
README.md
crashtracker-ffi/src/collector/spans.rs
tools/docker/Dockerfile.build

Upgrade minimum Rust version to 1.76.0.
Necessary for changes in https://github.com/DataDog/libdatadog/pull/606.
Other PRs related to Rust version upgrade:
* https://github.com/DataDog/benchmarking-platform/pull/96
* https://github.com/DataDog/libddprof-build/pull/49

Upgrade to Rust 1.76.0

---

data-pipeline/src/lib.rs
data-pipeline/src/trace_exporter.rs

Require docs on all public things in data-pipeline. Add docs for anywhere this wasn't already true.
Docs are valuable for us and for others working in this repository. 
N/A

Require docs on all public things in data-pipeline

---

builder/Cargo.toml
examples/ffi/crashinfo.cpp
examples/ffi/crashtracking.c
profiling-ffi/Cargo.toml

Ensure `ddog_crasht_demangle` is exported. Currently, it's not compiling/linking at all.
Since https://github.com/DataDog/libdatadog/pull/551, `ddog_crasht_demangle` is not exported anymore (not in v11 nor v12).
Added a call to `ddog_crasht_demangle` in the example.
+
Downloaded the artifacts and checked that the symbol is part of the library
```
╭─greg@DESKTOP-DQNLFF9 ~/repos/libdatadog/tmp  ‹gleocadie/add-crashtracking-feature-for-windows›
╰─➤  nm lib/libdatadog_profiling.so | grep ddog_crasht_demangle
00000000004f8710 T ddog_crasht_demangle
```
Add a test to check the exported functions.

Fix missing symbol `ddog_crasht_demangle`

---

.github/workflows/test.yml
windows/build-artifacts.ps1
windows/libdatadog.csproj

Since https://github.com/DataDog/libdatadog/pull/551, crashtracker has its own header `crashtracker.h`. This header is not part of the nuget package and prevent compilation on windows.
Make sure we can compile in Visual Studio.
Waiting for https://github.com/DataDog/libdatadog/pull/611
Downloaded the nuget package (from the gitlab job) and checked that :
- `crashtracker.h` is present
- `ddog_crasht_demangle` symbol is present

[Profiling/Build] Add crashtracking feature for windows (event it's not ready yet)

---

dogstatsd/README.md

Adds a readme with unstable disclaimer for dogstatsd crate.
Clarify intended usage of crate.

Adds Readme for dogstatsd Crate

---

.github/workflows/test.yml
builder/build/arch/apple.rs
builder/build/arch/linux.rs
builder/build/arch/musl.rs
builder/build/arch/windows.rs
builder/build/profiling.rs

Update the `SONAME` in the `libdatadog_profiling.so` file.
Fix CI.
Cargo produces the `libdatadog_profiling_ffi.so` then late renames it into `libdatadog_profiling.so`. But the `SONAME` in `libdatadog_profiling.so` is `libdatadog_profiling_ffi.so` (same as the original).
So when building the symbolizer (for example) and linking against `libdatadog_profiling.so`, the linker will register `libdatadog_profiling_ffi.so` as `NEEDED`
But it's not its name anymore, so we have to patch `libdatadog_profiling.so` to change its `SONAME` into `libdatadog_profiling.so`.

Fix CI failure: update `libdatadog_profiling.so` `SONAME`

---

build-profiling-ffi.sh

Enable the demangler feature when building artifacts on Gitlab.
Since https://github.com/DataDog/libdatadog/pull/551, `ddog_crasht_demangle` is not include in the sofile. A fix was provided for github which uses the new builder. But in GitLab we still rely on the `build-profiling.sh` shell script.
🤷‍♂️ 
download the artifact from gitlab and check the presence of `ddog_crasht_demangle`

[Gitlab] Fix build in Gitlab

---

build-profiling-ffi.sh

Fix `SONAME` for artifacts produced in Gitlab.
Since in GitLab we do not use the new builder, we have to update the `build-profiling.sh` shell script in order to port this [change](https://github.com/DataDog/libdatadog/pull/624).
🤷 
Download the artifact from Gitlab and run `readelf -d libdatadog_profiling.so`

Fix SONAME for artifact produced in Gitlab

---

Cargo.lock
Cargo.toml

Bump the version from 12 to 13.
Publish a new release of libdatadog.

Bump to v13 for release

---

Cargo.lock
serverless/Cargo.toml
serverless/src/main.rs
trace-mini-agent/src/config.rs
trace-mini-agent/src/mini_agent.rs
trace-mini-agent/src/trace_processor.rs

Starts a DogStatsD server when running the Serverless Mini Agent.
Allow runtime metrics and custom metrics to be sent from Azure Spring Apps and Azure Functions.
- https://datadoghq.atlassian.net/browse/SVLS-5177
- https://datadoghq.atlassian.net/browse/SVLS-5521
- Updated `main` method of Serverless to be asynchronous.
- Allow custom DogStatsD port with `DD_DOGSTATSD_PORT`
- Allow DogStatsD to be disabled with `DD_USE_DOGSTATSD`
* Build mini agent and deploy to Azure Spring App and Azure Function
* Confirm runtime metrics are sent successfully to Datadog

[Serverless Mini Agent] Use DogStatsD in Serverless

---

Cargo.lock
serverless/Cargo.toml

Bumps Serverless Mini Agent Version to 0.7.0.
Upcoming release of version 0.7.0.

Bump datadog-serverless-trace-mini-agent version to 0.7.0

---

dogstatsd/src/datadog.rs
dogstatsd/src/flusher.rs
dogstatsd/tests/integration_test.rs
serverless/src/main.rs

We had implemented this in the [Lambda Extension](https://github.com/DataDog/datadog-lambda-extension/pull/381/files/ef7ec6cdeac9fc8b066de42be4498175d567fbfb), but it didn't land in time.
Customer is asking for it and we'll need it for anyone using a VPC without privatelink.

feat: Support DD_HTTP_PROXY and DD_HTTPS_PROXY

---

.github/workflows/publish-serverless-agent.yml

Installs protoc for Serverless Release.
Follows changes in https://github.com/DataDog/libdatadog/pull/606 to install protoc.
Needed for upcoming release of 0.7.0.

[Serverless Mini Agent] Install Protoc for Serverless Release

---

Cargo.lock
serverless/Cargo.toml

Bumps Serverless Mini Agent Version to 0.7.1.
Upcoming release of version 0.7.1.

[Serverless Mini Agent] Bump datadog-serverless-trace-mini-agent version to 0.7.1

---

.github/workflows/publish-serverless-agent.yml

Upload zipped binaries at end of Github Workflow to release Serverless Mini Agent instead of generating a Github release.
Github Action returns 403 forbidden error when creating a release.
Updates `upload-artifact` and `download-artifact` actions to use `v4` to resolve warnings.
Pushed a test tag and confirmed that the generated binaries in the zip file worked successfully.

[Serverless Mini Agent] Upload Serverless Binaries Instead of Generating Release

---

Cargo.lock
serverless/Cargo.toml

Bumps Serverless Mini Agent Version to 0.7.2.
Upcoming release of version 0.7.2.

[Serverless Mini Agent] Bump datadog-serverless-trace-mini-agent version to 0.7.2

---

sidecar/src/service/sidecar_server.rs

There was async access happening to sessions, causing sessions being re-created after them being destroyed (and with default config, too).
Moving get_app() around, into the flushing logic to cleanly separate session access from async context.

Fix leaking sessions

---

Cargo.toml

Removes the `default-members` section of the `Cargo.toml` that was added to avoid the `builder` doing work, but now that `builder` doesn't have a default feature it probably doesn't add that much overhead.
It's easy to miss adding a new crate in both places and then the crate is not included in `workspace` level commands.

Remove Cargo.toml default-members since builder has no default feature

---

data-pipeline/src/stats_exporter.rs

The token cancellation test is flaky in the coverage pipeline. I fixed this by increasing the delay for the force flush to complete.

Fix token cancellation flakiness

---

sidecar/src/watchdog.rs

If the sidecar hangs, it can cause every process trying to write to it to be much slower.
Better kill it once in doubt.

Implement deadlock watchdog for sidecar

---

builder/build/arch/linux.rs
builder/build/arch/musl.rs

Actively waiting for spawned children in the builder in order to avoid concurrency problems.
Letting child process on their own could lead to issues if the parent process finish before them or another subsequent command is added that operates on the same resources.

[APMSP-1391] Wait for spawned children

---

crashtracker-ffi/src/crash_info/datatypes.rs
crashtracker/src/crash_info/stacktrace.rs
examples/ffi/crashinfo.cpp

Add Pdb enum to the `Normalized` data structure.
Crashtracker will be soon available on Windows. In order to provide useful information for remote symbolication, we add Pdb enum + needed information (guid and age). We reuse the `build_id` field for the guid.
Same as crashtracking on linux + manual tests.

[Crashtracking] Add PDB info to crash info

---

dogstatsd/src/aggregator.rs
dogstatsd/src/dogstatsd.rs
dogstatsd/src/metric.rs

Disables miri for dogstatsd.
Also uses `collect` instead of `for_each` + `push` which Levi thinks could avoid `memcpy`s.
dogstatsd tests were really slow under miri in CI, like 20,000 times slower (higher than normal for miri).

test: ignore dogstatsd tests under miri

---

Cargo.lock
Cargo.toml

Bump the version from 13 to 13.1
Publish a new release of libdatadog.

Bump to v13.1 for release

---

ipc/src/platform/unix/mem_handle.rs
ipc/src/platform/unix/mem_handle_macos.rs
ipc/src/platform/windows/mem_handle.rs
remote-config/src/fetch/fetcher.rs
remote-config/src/fetch/multitarget.rs
remote-config/src/parse.rs
remote-config/src/path.rs
sidecar-ffi/src/lib.rs
sidecar/src/one_way_shared_memory.rs
sidecar/src/shm_remote_config.rs
spawn_worker/src/trampoline.c

Adds some ASM constants, some functions to work with RC shared memory paths (rather than only ConfigInvariants and Targets, which are more difficult to pass around), and an in-memory notification mechanism.
In support of https://github.com/DataDog/dd-trace-php/pull/2864

Support for remote config in the appsec helper

---

sidecar/src/service/sidecar_server.rs
trace-utils/src/msgpack_decoder/v04/decoder/mod.rs
trace-utils/src/tracer_payload.rs

The incoming buffer may be much larger than the actual contained data. The decoder knows where the payload starts and ends, but the sidecar send_trace_v04 method does not.
This ensures proper trace coalescing, leading to less individual http requests.

Fix the trace payload size hint

---

remote-config/src/fetch/fetcher.rs

These need to be in a big-endian bitset, so we send that.

Use the correct format for capability submission

---

.github/workflows/all-checks.yml

Allows merging of a PR even if Coverage fails
Strange behavior with code coverage and library paths in CI leads to failures that are not related to the PRs.

Make coverage success optional in CI

---

ddcommon/src/tag.rs
remote-config/examples/remote_config_fetch.rs
remote-config/src/fetch/fetcher.rs
remote-config/src/fetch/shared.rs
remote-config/src/lib.rs
sidecar-ffi/src/lib.rs
sidecar/src/service/remote_configs.rs
sidecar/src/service/sidecar_server.rs
sidecar/src/shm_remote_config.rs

As pointed out by DataDog/system-tests#3212, we need to send git metadata to the RC client.
This allows sending it.

Allow sending tags via RC

---

.github/workflows/publish-serverless-agent.yml

Zip Serverless binaries and create a Github release with the proper permissions.
Revert changes made in the below PR to only upload the binaries to Github. By adding the proper Github job permissions we can create a Github release and automatically attach the binaries to the release.
https://github.com/DataDog/libdatadog/pull/634
Pushed a test tag and confirmed that the generated binaries in the zip file worked successfully.

[Serverless Mini Agent] Add Zipping of Serverless Binaries with Proper Github Permissions

---

ruby/README.md
ruby/Rakefile
ruby/lib/libdatadog/version.rb

**What does this PR do?**
https://github.com/datadog/libdatadog/tree/main/ruby#releasing-a-new-version-to-rubygemsorg
**Motivation:**
Enable Ruby to use libdatadog v13.1.0.
**Additional Notes:**
We ended up not releasing 13.0 for Ruby. I don't see any reason to backfill so I've skipped ahead.
**How to test the change?**
I've tested this release locally using the changes in https://github.com/datadog/dd-trace-rb/pull/3997 .

[PROF-10603] Package libdatadog v13.1.0 for Ruby

---

trace-mini-agent/src/config.rs
trace-mini-agent/src/env_verifier.rs
trace-mini-agent/src/trace_processor.rs
trace-utils/src/trace_utils.rs

Adds `azurespringapp.name` and `azurespringapp.hostname` span tags to spans from Azure Spring apps.
Add span tags for Azure Spring apps to facilitate billing.
https://datadoghq.atlassian.net/browse/SVLS-5643
Remove `functionname` span tag for Azure Spring apps.

[Serverless Mini Agent] Add Span Tags for Azure Spring Apps

---

Cargo.lock
serverless/Cargo.toml

Bumps Serverless Mini Agent Version to 0.8.0.
Upcoming release of version 0.8.0.

[Serverless Mini Agent] Bump datadog-serverless-trace-mini-agent version to 0.8.0

---

Cargo.lock
dogstatsd/Cargo.toml

This PR upgrades the libdatadog dependencies coming in from the "saluki-backport" repository: datadog-protos and ddsketch-agent.
These unlock the upgrade of tonic to 0.12.3 which will solve the following security advisory:
https://github.com/DataDog/libdatadog/security/dependabot/22 .
Get rid of outdated dependencies.
The upgrade of stuff from "saluki-backport" brings other changes; I'll sync with @duncanpharvey to make sure this is good to go.
Not sure -- hopefully existing test coverage is enough? I'll sync on this with @duncanpharvey as well.

[NO-TICKET] Upgrade "datadog-protos"/"ddketch-agent" to unlock tonic 0.12.3

---

.github/workflows/all-checks.yml
.github/workflows/coverage.yml

Code coverage started to malfunction due to some compatibility issue between current Rust  and llvm-cov/nextest versions. This PR bumps llvm-cov and nextest to bring back code coverage.

Enable code coverage.

---

dogstatsd/src/datadog.rs
dogstatsd/src/flusher.rs
dogstatsd/tests/integration_test.rs
serverless/src/main.rs
trace-mini-agent/src/config.rs

In my earlier PR I made two mistakes:
1. With bleary newborn-parent eyes I didn't realize it was DD_PROXY_HTTPS, I had inverted it.
2. I had hoped that I could simply use the linux native HTTPS_PROXY env var, but our customer is correct and we'll need support for both.
These env vars are enforced _in priority order_ as per the [docs](https://docs.datadoghq.com/agent/configuration/proxy/?tab=linux):
1. DD_PROXY_HTTPS
2. HTTPS_PROXY
3. yaml config file (not used here)
This PR adds support for this for both dogstatsd and the trace mini agent.
I've verified both configs are still valid and work.
Traces:
Metrics:
(and logs, but that's not part of libdatadog)
finishing what I started

feat: Prefer DD_PROXY_HTTPS over HTTPS_PROXY

---

crashtracker/src/crash_info/stacktrace.rs

Use ELF virtual address instead of file offset for normarlized addresses.
When computing normalized address, use elf virtual addresses instead of file offsets because file offset alone is not enough to perform symbolization with split debug information.
`file_offset` should probably be renamed, this will be addressed in a later PR.

[PROF-10680] Use ELF virtual address instead of file offset

---

trace-obfuscation/benches/benchmarks/credit_cards_bench.rs

Tells the `credit_cards_bench` to not inline the `is_credit_card` method to try to stabilize results a bit.
The results fluctuate due to _external_ factors like dependency changes that seem to affect the benchmarking harness and the inlining decisions.
The benchmark results will differ from `main` since this PR affects the generated code, but hopefully (and according to my tests), it should stabilize them a bit going forward.

Stabilize credit_cards_bench inlining

---

builder/build/arch/apple.rs
ipc/src/platform/unix/mem_handle_macos.rs
sidecar/src/service/sidecar_server.rs

Implements some small changes proposed by clippy.
We should be clippy clean.
Existing tests should be sufficient.

Resolve clippy warnings

---

trace-obfuscation/src/credit_cards.rs

Use a fixed size array (we know that credit card numbers are at most 16 digits long) instead of a dynamic `Vec`.
While looking at benchmark fluctuations, I saw that the code seemed to do unnecessary operations. Why not optimize it?

Optimize is_card_number to use array

---

spawn_worker/src/trampoline.c
trace-utils/Cargo.toml

It worked when DD_SPAWN_WORKER_USE_EXEC=1 was set, but not generally. Having a /proc/<pid>/X path will tell gdb exactly where to find it, instead of a /proc/self/fd/X which is pointing into gdbs own process from the perspective of gdb.
This also prevented sidecar core dumps from being opened with gdb, which was rather ugly.
(Also updates the Cargo.toml of trace-utils to include the required hyper runtime, otherwise the server feature will fail to compile...)

Allow attaching to the sidecar via gdb

---

.github/workflows/stale.yml
.github/workflows/test.yml

Introduce the stale action for PRs.
- PRs with no activity for 90 days will be marked with a `stale` label and a comment will be added to the PR
- After being stale for 14 days the PR will be automatically closed
- Issues are not included in this (but can be later, if we want)
- Branches will not be auto-deleted (but they can be, if we want)
- You can avoid this action on a PR with the `keep-open` label
Good repository hygiene suggested by @hoolioh  
`stale` and `keep-open` labels have been added to the repo.
I don't think we can really test the action until it is merged into main.

add stale PR GH workflow

---

data-pipeline/src/trace_exporter.rs

Several fixes to sampling:
- Single-span sampling should not be made based on priority but based on sampling mechanism
- Analyzed tag is `_dd1.sr.eausr`
- Use const for keys

[APMSP-1458] Fix single-span sampling

---

tools/sidecar_mockgen/src/lib.rs

It turns out recent clang version will include shared library functions as weak symbols. We don't want shared libarary functions in our output. Ignore them.

Ignore weak symbols in mockgen

---

crashtracker/src/collector/crash_handler.rs

Some downstream PRs are affected by the too-small default altstack size used in crashtracking.  This is supposed to be a harmless fix.
I think creating a configurable stack size is irrelevant, since we should probably not have an overly-dynamic use of the stack.   Please chime in if you have a strong feeling on an ideal altstack size.
In particular, I think reviewers should check whether they feel like we should be pinned on a multiple of page size, or if we should use a number of bytes which we then round up to the nearest page (e.g., if the CPU MMU has a different page size configured, which may make this value really big).

Bump crashtracking altstack size

---

bin_tests/tests/crashtracker_bin_test.rs
crashtracker-ffi/src/crash_info/datatypes.rs
crashtracker/src/collector/crash_handler.rs
crashtracker/src/collector/emitters.rs
crashtracker/src/crash_info/mod.rs
crashtracker/src/crash_info/telemetry.rs

While investigating a customer crash, I found that I dearly missed having the address that caused a segfault.
E.g. given this code:
```c
char *potato = 0x1234;
fprintf(stderr, "Value of potato is %c\n", *potato);
```
...I want to know that the crash was triggered when 0x1234 was dereferenced, as this information may be key in debugging the issue.
We already get this information in our signal handler, so this PR just adds the needed piping to report it to datadog.
Improve debugging of crashes reported by crashtracker.
I added the `faulting_address` as a tag, similar to `siginfo` and `signame`. We may want to send it as some other thing; no strong opinions there.
I was able to test this with the Ruby profiler. I've been trying to update the tests but there's still some failing and I'm kinda …

[PROF-10656] Add faulting_address to crashtracker reports

---

Cargo.lock
dogstatsd/Cargo.toml
dogstatsd/src/dogstatsd.rs
dogstatsd/src/metric.rs
serverless/Cargo.toml
serverless/src/main.rs

Fixes two issues that prevent DogStatsD metrics from being submitted in some environments.
* Increases buffer size from 1KB to 8KB
* Updates DogStatsD regex to account for container ids
* Lazily initialize static regex for dogstatsd metrics
https://datadoghq.atlassian.net/browse/SVLS-5799
Some DogStatsD messages in Azure Spring App environments were larger than 1KB, causing them to be truncated. These messages also include container ids with the pattern `c:*`.
[DogStatsD protocol v1.2](https://docs.datadoghq.com/developers/dogstatsd/datagram_shell/?tab=metrics#dogstatsd-protocol-v12)
```
DEBUG Received message: datadog.dogstatsd.client.metrics:0|c|#env:dev,service:azure-spring-app,client:java,client_version:4.4.2,client_transport:udp|c:b9ee8edd7d87cbbcf378f30f8d303dd71e8899006fb4ea6369a774 …
```

Increase DogStatsD Buffer Size and Pattern Match Container Ids

---

Cargo.lock
crashtracker/src/crash_info/stacktrace.rs
examples/ffi/symbolizer.cpp
symbolizer-ffi/Cargo.toml
symbolizer-ffi/src/blazesym.h

Seems like a prudent thing to do
Plus this upgrade happens when trying to cargo update, so why not?

Updates blazesym to 0.1.0rc1

---

.github/workflows/test.yml

Addresses https://github.com/actions/runner-images/issues/10721 deprecating macos-12 images.

chore(ci): stop using macos-12 in github actions

---

crashtracker/src/collector/api.rs
crashtracker/src/collector/crash_handler.rs

In my last crashtracking PR, I split up the configuration for _using_ and _enabling_ the altstack.  However, since this was really tricky to test, it wasn't tested, so of course there was a typo (`use` is unused and `create` implies both)
Fixing crashtracking
Tests are implemented now for all variants
* use, but do not create
* create and use
* do not use, but create (paradox!)
* do not use, do not create

[crashtracking] fix SA_ONSTACK

---

Cargo.lock
Cargo.toml
ddcommon/Cargo.toml

Release a fixup due to an interface bug in crashtracking.  Other PRs have no public interface changes, so making this a minor release.

Bump to v14.1.0

---

ruby/Rakefile
ruby/lib/libdatadog/version.rb

Fixes an issue where libdatadog 14.1.0 hadn't been released yet for Ruby

v14.1.0 release for Ruby

---

docs/RFCs/0004-crashtracker-prevent-hangs.md

Adds an RFC mitigating an open issue from #696  
We want to limit the potential impact of crashtracking on users. 
This is a documentation only change

[crashtracker] RFC to mitigate hangs

---

data-pipeline-ffi/src/trace_exporter.rs
data-pipeline/examples/send-traces-with-stats.rs
data-pipeline/src/stats_exporter.rs
data-pipeline/src/trace_exporter.rs

- Add `Datadog-Meta-...` headers to stats
- Add `git_commit_sha` to TraceExporter meta for ClientStatsPayload
- Add `interpreter_vendor` to TraceExporter meta
- Rename the `version` field to `app_version` to be more explicit
This PR can be reviewed commit-by-commit
These headers are required by design doc

[APMSP-1512] Add metadata headers for stats

---

trace-utils/src/trace_utils.rs

Update namespace for span tags Azure Spring Apps and Google Cloud Functions v1.
Make sure span tags from each of these products have a namespace with a consistent naming pattern prior to GA.
https://datadoghq.atlassian.net/browse/SVLS-5915
https://datadoghq.atlassian.net/browse/SVLS-5918
* Azure Spring Apps: `azurespringapp` -> `asa`
* Google Cloud Functions v1: `gcrfx`

[Serverless Mini Agent] Update Namespace for Span Tags from Azure Spring Apps and Google Cloud Functions v1

---

crashtracker/src/collector/api.rs

This patch adds a test without changing any functionality.  During development of a recent crashtracking fix, I had a C-language repro for this situation which I'd test against the FFI.  Now that the dust has settled a bit and we're doing some more feature work with crashtracking, it's time to add a regression test for this condition.
This was the most significant defect end-users have experienced for crashtracking to date.  We should check it explicitly.

[crashtracking] Add explicit test for extra children

---

data-pipeline/src/trace_exporter.rs
sidecar/src/service/sidecar_server.rs
trace-mini-agent/src/trace_flusher.rs
trace-mini-agent/src/trace_processor.rs
trace-utils/Cargo.toml
trace-utils/src/send_data/mod.rs
trace-utils/src/test_utils/datadog_test_agent.rs
trace-utils/src/test_utils/mod.rs
trace-utils/src/trace_utils.rs
trace-utils/tests/test_send_data.rs

This PR tries to clean a bit the proxy handling by creating a new function to send requests through a proxy passed as a parameter rather than holding the proxy url in each SendData structure.
Decouple SendData from proxy handling so future planned work on SendData will be easier.

Refactor proxy handling.

---

crashtracker/src/collector/api.rs

This test seems to run well normally, but crashes in the coverage CI step.  This is a regression test that should run locally on major architectural changes to crashtracking, but I think it's OK to skip it for now
unblock CI

Ignore flaky crashtracking test

---

crashtracker/Cargo.toml
symbolizer-ffi/Cargo.toml
symbolizer-ffi/src/blazesym.h

Update blazesym to 0.2.0-rc.2
0.2.0-rc.2 contains [fix](https://github.com/libbpf/blazesym/pull/824) from @gleocadie to read build id in permissionless env.

Update blazesym to 0.2.0-rc.2

---

trace-utils/benches/deserialization.rs

Previously, we were performing benchmarks for msgpack deserialization on 2 spans which is both unrealistic, and contributed to variance in benchmarks. This PR changes the payload to approximately 10mb of data (~40k spans). 
The benchmark report for this PR can be ignored since the baseline was for just 2 spans.

increase the volume of traces for deserialization benchmarks

---

docs/RFCs/0005-crashtracker-structured-log-format.md

Fixes a link in the RFC to point at the right file.
Oops!
Click the new link, see it works.

[crashtracker] Fixup link in RFC

---

Cargo.lock
crashtracker/Cargo.toml
crashtracker/src/crash_info/mod.rs
crashtracker/src/lib.rs
crashtracker/src/rfc5_crash_info/error_data.rs
crashtracker/src/rfc5_crash_info/metadata.rs
crashtracker/src/rfc5_crash_info/mod.rs
crashtracker/src/rfc5_crash_info/os_info.rs
crashtracker/src/rfc5_crash_info/proc_info.rs
crashtracker/src/rfc5_crash_info/sig_info.rs
crashtracker/src/rfc5_crash_info/spans.rs
crashtracker/src/rfc5_crash_info/stacktrace.rs

* Adds a new datatype which implements RFC 0005.
* Adds a translation from the old to the new data-format.
* the `file://` output type now outputs RFC0005 format as well as the old format.
This is step 1 in implementing the RFC.
This is step 1 of a multi-step program to move crashtracker over to RFC5.  
For now, both dataformats will co-exist.
Future PRs will switch various parts of the API over to use the new format.
Once this is done, we can retire the old format.

[crashtracker] Implement RFC 0005

---

.github/workflows/fuzz.yml

Reduces the time per fuzz test from 1min -> 30s for PRs.
The "profiling" fuzz tests take 18 min.  This is over our desired 10min CI budget.
This lowers coverage.  We should add a nightly job that runs the latest main for longer to get coverage back.

[chore] Reduce fuzz time to 30s for PRs

---

live-debugger-ffi/src/send_data.rs
live-debugger/src/debugger_defs.rs
sidecar-ffi/src/lib.rs
sidecar/src/service/blocking.rs
sidecar/src/service/debugger_diagnostics_bookkeeper.rs
sidecar/src/service/mod.rs
sidecar/src/service/sidecar_interface.rs
sidecar/src/service/sidecar_server.rs

We were sending too much data and that made our backend sad.
Sending less data so that our backend can be happy again.
This avoids sending multiple diagnostics for individual runtime ids.

Deduplicate Debugger diagnostics in sidecar

---

trace-utils/src/send_data/mod.rs

Set the `Datadog-Send-Real-Http-Status` header to indicate to the agent that we are able to handle 429 responses and will appropriately back off and retry. Due to legacy compatibility reasons the default behavior of the trace agent for trace payloads is to always respond with a `200` status code even if the trace-agent detects it is overwhelmed and will drop the payload. By setting this header the trace-agent will instead respond with a 429 giving us an opportunity to retry and decrease the likelihood of lost data.
We have retry logic but we aren't using it :(
This change is well covered by the unit tests

Add header so we get real http status codes from the trace agent (APMSP-1418)

---

sidecar/src/service/sidecar_server.rs

This lead down to a path where the Stop action was actually enqueued without being ever causing a removal of the Application instances.

Handle case where the applictaion is stopped without other telemetry sent

---

tests/windows_package/windows_package.vcxproj
windows/libdatadog.csproj
windows/libdatadog.props

Update nuget package to be able to link .NET profiler dynamically against libdatadog.
The package contained the dll but not the `lib` required to link dynamically in VS. The other `lib` file was used to link statically.
The package is tested in gitlab CI. If the build is green, it means the linking was correct.
I also download the nuget packages and tested it on my machine.

Allow dynamic linking on Windows

---

bin_tests/src/lib.rs
crashtracker/src/collector/crash_handler.rs
crashtracker/src/crash_info/telemetry.rs
data-pipeline/examples/send-traces-with-stats.rs
data-pipeline/src/span_concentrator/mod.rs
ddtelemetry/examples/tm-metrics-worker-test.rs
ddtelemetry/examples/tm-ping.rs
ddtelemetry/examples/tm-send-sketch.rs
ddtelemetry/examples/tm-worker-test.rs
ddtelemetry/src/metrics.rs
ddtelemetry/src/worker/mod.rs
dogstatsd/src/aggregator.rs
sidecar/src/service/blocking.rs
trace-mini-agent/src/stats_processor.rs
trace-mini-agent/src/trace_processor.rs
trace-normalization/src/normalize_utils.rs
trace-normalization/src/normalizer.rs

Small fixup: prefer `elapsed()` to `Instant::now().duration_since(...)`
Its cleaner and neater.
Existing test suite

[chore] Use elapsed() if possible when calculating durations

---

build-profiling-ffi.sh
windows/build-artifacts.ps1

With this change, we will start shipping the data-pipeline code in the shipped artifacts.
I also made some refactor to make it easier to make such changes in future so we don't make mistake like `cbindgen,datadog-profiling-ffi/ddtelemetry-ffi` was included multiple times in past at https://github.com/DataDog/libdatadog/blob/c6ad4ff82852ed6d39fd618a602020b6ba623ed6/build-profiling-ffi.sh#L141
data-pipeline integration in .NET SDK requires data-pipeline stuff as per https://github.com/DataDog/dd-trace-dotnet/pull/6314, hence we need to start shipping the code so integrations can use it 
on mac
```
❯ ./build-profiling-ffi.sh bin
<truncated>
Building for features: cbindgen,crashtracker-collector,crashtracker-receiver,data-pipeline-ffi,datadog-profiling-ffi/ddtelemetry-ffi,datadog-profiling-ffi …
```

chore: enable data-pipeline feature in shipped artifacts

---

crashtracker/src/collector/api.rs
crashtracker/src/lib.rs
crashtracker/src/rfc5_crash_info/error_data.rs
crashtracker/src/rfc5_crash_info/metadata.rs
crashtracker/src/rfc5_crash_info/mod.rs
crashtracker/src/rfc5_crash_info/proc_info.rs
crashtracker/src/rfc5_crash_info/sig_info.rs
crashtracker/src/rfc5_crash_info/stacktrace.rs
crashtracker/src/rfc5_crash_info/telemetry.rs
crashtracker/src/rfc5_crash_info/test_utils.rs

What it says on the tin
A format we can't actually upload isn't that useful.
Some fields are duplicated from the `CrashInfo` into telemetry headers, but I think there is value in posting precisely the RFC5 struct, and in having searchable telemetry headers.
Added a version of the additional telemetry test, with additional checks.

[crashtracker] Implement telemetry for RFC5

---

Cargo.lock
data-pipeline/Cargo.toml
data-pipeline/src/health_metrics.rs
data-pipeline/src/trace_exporter.rs

Moves TraceExporter to use trace utils send data functionality.
We want access to the retry functionality of trace utils as well as to start supporting TinyBytes so we have good performance here
There are a number of things to do after this is merged that have been commented out explicitly so that we can unblock others working in this area. (e.g. client stats)
Covered with unit and integration tests for now

Initial move to use SendData in trace exporter (APMSP-1586)

---

.github/workflows/test.yml
crashtracker-ffi/src/crash_info/datatypes.rs
crashtracker-ffi/src/crash_info/mod.rs
examples/ffi/crashinfo.cpp

When calling `ddog_crasht_CrashInfo_upload_to_endpoint`, if the `ProcInfo`  is not set, the process crashes with panic
```
thread '<unnamed>' panicked at crashtracker/src/rfc5_crash_info/mod.rs:74:41:
```
Fix a bug and missing API.
The `crashinfo` example runs in CI.
Added calls to `ddog_crasht_CrashInfo_set_procinfo` to fix the crash

fix(crashtracker) : Fix crash when sending crashinfo

---

Cargo.lock
Cargo.toml

Bumps the version to 14.3.0 in preparation for release
We want to get the fix in #754 out as fast as possible

Bump version to 14.3.0 in preperation for release

---

crashtracker/src/collector/crash_handler.rs

Addresses some PR comments I'd made on #754 754
David was so fast he merged before I posted the comments.

[crashtracker] Small style improvements to 754

---

tinybytes/src/bytes_string.rs

`BytesString` derives Hash from `Bytes` which hashes the string as a &[u8].
BytesString also implements `Borrow<str>` which requires both types to have the same hash.
The issue is that `[u8]` and `str` do not have compatible hash functions, so BytesString should use `str` hash implementation.
This PR also adds:
- From trait for `String` and `'static str` to avoid utf8 checks
- `AsRef<str>` trait useful when dealing with generic functions
- Use `Self` type to match `Bytes` style
Hash is required to handle `meta` hashmap in spans

[APMSP-1583] Fix hash in BytesString

---

alloc/src/chain.rs
data-pipeline/src/trace_exporter.rs
sidecar/src/service/debugger_diagnostics_bookkeeper.rs
sidecar/src/service/session_info.rs
trace-mini-agent/src/config.rs
trace-protobuf/src/pb_test.rs
trace-utils/src/stats_utils.rs
trace-utils/src/trace_utils.rs

1. Fixes a warning `dangling_pointers_from_temporaries`.
2. Skips some tests on miri for MacOS.
3. Fixes a test that doesn't fail for the right reason when running locally (because it can't figure out the cloud env it's running in, because it's not in a cloud env).
I was trying out the Rust 2024 edition which required a new nightly. There's now a warning for `dangling_pointers_from_temporaries`. This could be a false positive but I am not certain. It
seems prudent to fix it and figure out whether it's truly dangling later, if we have time.
The other fixes are just annoyances that happen when developing locally on a Mac.
Here's the warning:
```
warning: a dangling pointer will be produced because the temporary `UnsafeCell<ChainNodePtr<A>>` will be dropped
--> alloc/src/chain.rs:293:30
| …
```

fix(alloc): potentially dangling temporary

---

crashtracker/src/crash_info/telemetry.rs
crashtracker/src/rfc5_crash_info/telemetry.rs
ddtelemetry/examples/tm-ping.rs
ddtelemetry/examples/tm-send-sketch.rs
ddtelemetry/src/data/common.rs
ddtelemetry/src/worker/mod.rs

Adds the `origin` field, [defined in the backend](https://github.com/DataDog/dd-go/blob/prod/trace/apps/tracer-telemetry-intake/telemetry-payload/header.go#L88) but not currently implemented in libdatadog.
#727 We'd like to use this field in the crashtracker.
* I put placeholder values in for the different uses.  LMK if I should change them?
* The `ddcommon` request builder currently just sets "unknown".  I could plumb through an option to set a value, but this might be a breaking change.  Thoughts?

[telemetry] Add missing origin field

---

builder/src/builder.rs
builder/src/crashtracker.rs

Fix cmake target directory during the artifact generation.
The builder could fail on certain scenarios.
Builder can be triggered by:
`cargo run --bin release --features profiling,telemetry,symbolizer,crashtracker,data-pipeline --release -- --out <path>`
After that it can be checked that all required artifacts should be in the desired output path

Fix builder cmake target directory.

---

ddtelemetry/src/data/payloads.rs

Removes `skip_serializing` field on the telemetry Log struct fields 
As it turns out, bincode (the encoding format used in the sidecar rpc format) does not support encoding of serde fields using skip_serializing_if https://docs.rs/bincode/2.0.0-alpha.1/bincode/serde/index.html#known-issues so sending logs through the sidecar would fail

Fixes log struct not being able to be sent through the sidecar RPC

---

data-pipeline-ffi/cbindgen.toml
data-pipeline-ffi/src/error.rs
data-pipeline-ffi/src/lib.rs
data-pipeline-ffi/src/trace_exporter.rs
data-pipeline/src/trace_exporter/agent_response.rs
data-pipeline/src/trace_exporter/error.rs
data-pipeline/src/trace_exporter/mod.rs
ddcommon-ffi/src/option.rs
dogstatsd-client/src/lib.rs
examples/ffi/trace_exporter.c
trace-utils/src/send_data/mod.rs
trace-utils/src/send_data/send_data_result.rs

This PR tries to improve the FFI for the trace exporter API by:
* Use a builder approach by encapsulating configuration in a new structure.
* Forward agent responses by introducing a new data type called `Rates` which can be queried to get the sampling rate for a specific service name. The value will be passed to the library user by a new output parameter in `ddog_trace_exporter_send`.
* Improve error handling in the API by returning a new data type called `ddog_TraceExporterError` which contains new error codes and debug information.

Refator API for Trace Exporter FFI

---

ddtelemetry/src/worker/mod.rs

For to push these changes before merging https://github.com/DataDog/libdatadog/pull/515

Avoid using lock unnecessarily

---

Cargo.toml
README.md

Documents the restrictions that the PHP project imposes on bumping the MSRV.
I've been wanting to do this for a while, but wasn't unsure if Remi Collet would be comfortable with me putting this in the docs. I asked him on an issue the last time we bumped MSRV, and he said that's okay.
Alpine Linux released a new version, so that's specifically what prompted to open the PR _right now_.
No changes are made, this is just documentation.

doc: restrictions on bumping MSRV

---

ddsketch/build.rs
trace-protobuf/build.rs

Add a build directive to stop re-running build.rs on crates compiling proto definitions when we don't need to
Currently, the `build.rs` are re-run everytime, which prevents caching of crates depending on `ddsketch` and `trace-protobuf`.
This makes incremental re-build take longer than necessary.

Fix protobuf build-rs scripts re-executing and trashing incremental compilation cache

---

ddcommon-ffi/src/option.rs
ddtelemetry-ffi/src/lib.rs
profiling-ffi/src/exporter.rs
sidecar-ffi/tests/sidecar.rs

* Add warning on unused ffi::Option
* Add unwrap_none method to assert the MaybeError is none in unit tests
* Call to unwrap_none on MaybeError in tests
The return values from these functions usually called from C, but also used in unit-tests was dropped without checking that there are no errors.
Now, ignoring a MaybeErr should produce a warning when building tests

[ffi][tests] Check that ffi::MaybeErr is None in tests invoking ffi functions 

---

data-pipeline/src/trace_exporter/mod.rs
trace-utils/src/msgpack_decoder/v04/decoder/mod.rs
trace-utils/src/msgpack_decoder/v04/decoder/span.rs
trace-utils/src/msgpack_decoder/v04/decoder/span_link.rs
trace-utils/src/msgpack_decoder/v04/number.rs

Align the v0.4 msgpack decoder with the [pb definition for spans](https://github.com/DataDog/libdatadog/blob/fd011c1ad237ee29d1f52d51452f6da7124edc9e/trace-protobuf/src/pb.rs) to have "default if null" behavior for all top level span fields. 
Decoding errors encountered while integrating with .NET SDK
Also adjusted some decoding tests so we no longer have to ignore miri for them
Unit tests added

Support "default if null" behavior for msgpack decoding of v04

---

crashtracker-ffi/src/collector/counters.rs
crashtracker-ffi/src/collector/datatypes.rs
crashtracker-ffi/src/collector/mod.rs
crashtracker-ffi/src/collector/spans.rs
crashtracker-ffi/src/demangler/mod.rs
crashtracker-ffi/src/receiver.rs
crashtracker/src/shared/configuration.rs
ddcommon-ffi/src/result.rs
examples/ffi/crashtracking.c

Uses the macros introduced in #752 throught the rest of crashtracker
Just look at how much nicer the code is.

[crashtracker] Refactor: Use the new FFI helper macros to cleanup the code

---

ddcommon/src/entity_id/mod.rs
ddcommon/src/entity_id/unix/mod.rs

Remove unused container id testing logic
The logic is dead-code and uses `static mut` to replace default values, which I don't think would be the right approach to do these tests anyway.

Remove unused container id testing logic

---

Cargo.lock
data-pipeline-ffi/Cargo.toml
data-pipeline-ffi/src/trace_exporter.rs
data-pipeline/src/trace_exporter/mod.rs

Allow sending empty arrays due to some tracers send this kind of payloads to check agent's availability.
Ensure compatibility with that feature.

Allow send empty arrays through the trace exporter

---

trace-mini-agent/src/http_utils.rs
trace-mini-agent/src/mini_agent.rs
trace-mini-agent/src/stats_flusher.rs
trace-mini-agent/src/stats_processor.rs
trace-mini-agent/src/trace_flusher.rs
trace-mini-agent/src/trace_processor.rs

Changes logs that were `info` to be `debug`
Info is too noisy for customers.
Also [DataDog/datadog-lambda-extension#496](https://github.com/DataDog/datadog-lambda-extension/issues/496)
n/a
n/a

[trace-mini-agent] change logs from `info` to `debug`

---

ddcommon/Cargo.toml
ddcommon/src/entity_id/mod.rs
ddcommon/src/entity_id/unix/mod.rs

Add back set_cgroup_file function. This adds a static variable used to override the default cgroup path.
This code was removed in #795, but this function is unfortunately directly imported and used in ddtrace-php here https://github.com/DataDog/dd-trace-php/blob/0926c77c3b8e0d41dd79774f89cd5f3dbbf2a03c/components-rs/lib.rs#L46-L49 so we cannot remove it.
They also use this feature in their tests

[fix] Add back set_cgroup_file function.

---

ddcommon/Cargo.toml

Unpins `cc` crate
Cannot build downstream when depending on `ddcommon`
Just unpinning setting the minimum to what the pin was.
Checks

[ddcommon] unpin `cc` crate

---

Cargo.lock
dogstatsd/Cargo.toml

Use saluki instead of saluki-backport as a dependency in dogstatsd.
A slightly modified version of [saluki](https://github.com/DataDog/saluki) was created in [saluki-backport](https://github.com/DataDog/saluki-backport) to be compatible with Rust 1.76.0. Now that we're upgrading to Rust 1.78.0 we can use the original saluki project again.
https://datadoghq.atlassian.net/browse/SVLS-5527
saluki originally forked for https://github.com/DataDog/libdatadog/pull/606

[dogstatsd] Use Saluki as a dependency

---

crashtracker-ffi/src/crash_info/sig_info.rs

I had this very interesting issue:
```
./components-rs/common.h:1174:18: error: expected ';' at end of declaration list
1174 |   ddog_CharSlice si_addr;
|                  ^
/usr/include/aarch64-linux-gnu/bits/types/siginfo_t.h:138:27: note: expanded from macro 'si_addr'
138 | #define si_addr         _sifields._sigfault.si_addr
|                                  ^
```
Essentially, the si_* fields are redefined by libc headers, making usage of these keywords fail compilation. Renaming it to fix the compilation issue.

Fix generated cbindgen compilation for crashtracker FFI

---

crashtracker/src/crash_info/telemetry.rs
crashtracker/src/rfc5_crash_info/telemetry.rs

Adds `api_version` and `request_type` headers to the telemetry messages sent by crashtracking.
Those headers are actually marked as required in the specification. I'm not actually sure _why_ it has worked until now (maybe the agent is adding them?) but it messes up with some tests.

[Crashtracking] Add missing telemetry headers

---

data-pipeline-ffi/src/error.rs
data-pipeline/src/trace_exporter/error.rs
data-pipeline/src/trace_exporter/mod.rs

Old API agent’s versions could send an empty response.  That means  there won’t be a  sampling rate announced so there’s the need of handling that specific case in the trace exporter instead of a returning a generic IO error. This way the tracer can apply its own heuristic in that case.
Support older agent's API versions.

Add new error in order to handle empty agent responses.

---

crashtracker/src/receiver/entry_points.rs
crashtracker/src/receiver/mod.rs
crashtracker/src/receiver/receive_report.rs

Splits the code into cleaner files.
I want to support the new RFC5 format, and this separates out the code that will need to change. 

[crashtracker] Refactor receiver code into seperate files.

---

bin_tests/src/lib.rs

When bin_tests generate binaries check if `$CARGO_TARGET_DIR` is set, and the target directory is not the default `target/`. If this is the case then use this as the root of the artifact location.
bin_tests fail when attempting to execute them inside a linux docker container that has $CARGO_TARGET_DIR set in order to avoid build conflicts with the host OS.  

APMSP-1711 check CARGO_TARGET_DIR when calculating artifact location for bin tests

---

Cargo.lock
dogstatsd/Cargo.toml
dogstatsd/src/datadog.rs
dogstatsd/src/flusher.rs
dogstatsd/tests/integration_test.rs
serverless/src/main.rs

Adds structure to the dogstatsd `Flusher::new` api, including a better name for the old `site` parameter and a type for it.
The old `site` parameter for `Flusher::new` was misleading since it wasn't supposed to be the `DD_SITE` value but instead the URL prefix for that `DD_SITE`'s api for intake.
Ran the test suite.

chore: [SVLS-5992] clearer dogstatsd Flusher API

---

Cargo.lock
Cargo.toml
build-profiling-ffi.sh

* Bump workspace version to 15.0.0
* Build configuration-ffi by default with the profiling artifacts so we can distribute it in the next release
The major version increase is necessary because of some breaking changes in the crashtracker APIs.

Prepare 15.0.0 release

---

serverless/src/main.rs
trace-utils/src/test_utils/mod.rs
trace-utils/src/trace_utils.rs

Renames `_dd.mini_agent_version` tag to `_dd.serverless_compat_version`.
Moving away from calling this solution the "Serverless Mini Agent" to calling it the "Serverless Compatibility Layer" instead.
https://datadoghq.atlassian.net/browse/SVLS-6117
https://datadoghq.atlassian.net/wiki/spaces/SLS/pages/2977497119/Serverless+Mini+Agent#Testing

Rename Mini Agent Version tag to Serverless Compat Version

---

bin_tests/src/bin/crashtracker_bin_test.rs
bin_tests/tests/crashtracker_bin_test.rs
crashtracker-ffi/src/crash_info/builder.rs
crashtracker-ffi/src/crash_info/metadata.rs
crashtracker/src/collector/api.rs
crashtracker/src/collector/counters.rs
crashtracker/src/collector/crash_handler.rs
crashtracker/src/collector/emitters.rs
crashtracker/src/collector/spans.rs
crashtracker/src/receiver/entry_points.rs
crashtracker/src/receiver/mod.rs
crashtracker/src/receiver/receive_report.rs
crashtracker/src/rfc5_crash_info/builder.rs
crashtracker/src/rfc5_crash_info/metadata.rs
crashtracker/src/rfc5_crash_info/sig_info.rs
crashtracker/src/rfc5_crash_info/telemetry.rs

Modifies the crashtracker receiver and emitter to speak RFC5, rather than the old ad-hoc format.
This is the last step before fully tearing out the old format
Existing tests

[crashtracker] Receiver speaks RFC5

---

.gitignore
README.md
local-linux.Dockerfile

Add an ubuntu docker image that can be used for local development, testing, debugging of linux-only functionality on non-linux hosts. 
We plan on adding an integration test to `trace-utils` that is linux-only in a follow-up PR.  
As mentioned in the dockerfile this image is not intended to overlap or interfere with other images we maintain for CI or releasing. It's exists to reduce the feedback loop for debugging linux-only tests for those of us on macOS. 
The readme has been updated with instructions on how to use the image.

Add a docker image that can be used for local linux dev

---

dogstatsd/src/aggregator.rs
dogstatsd/src/datadog.rs
dogstatsd/src/metric.rs

avoid sending duplicates tags as resources when they are not prefixed with `dd.internal.resource`

resources are only dd.internal.resource tags

---

dogstatsd/src/metric.rs

Allow tags that are not a pair key:value to be passed. Use an empty string as value and do not serialize a column with empty string in that case

fix: support tag that are not key-value pairs

---

Cargo.lock
data-pipeline/tests/test_fetch_info.rs
trace-utils/Cargo.toml
trace-utils/src/test_utils/datadog_test_agent.rs
trace-utils/tests/test_send_data.rs

Add an integration test to validate `SendData` can communicate with the agent via UDS
There shouldn't be anything in `SendData` that behaves differently when using UDS, but since it's the preferred way to communicate with the agent we should have at least one integration test for it. 
The next step is to introduce similar integration tests that compare snapshots via the test-agent for `data-pipeline::TraceExporter` which will also cover `SendData`. But as long as we have other code using `SendData` it makes sense to keep these tests as well. 
The test is marked with `#[cfg(unix)]` because it's extremely difficult, if not impossible, to communicate via UDS with a macOS host and a linux container. Thankfully, [there is a linux docker image](https://github.com/DataDog/libdatadog/pull/828) …

Add integration test to send_data to cover UDS transport with agent

---

windows/build-artifacts.ps1
windows/libdatadog.csproj

Adds Windows build of the `library_config` crate
Making it work in .NET
The paths will need to be adjusted for Windows but this will be done in another PR (likely https://github.com/DataDog/libdatadog/pull/840)
Just check the `library-config.h` file is present in the Windows build artifact from the Gitlab CI.

fix(library_config): Add Windows build support

---

trace-utils/src/trace_utils.rs
trace-utils/src/tracer_payload.rs
trace-utils/tests/test_send_data.rs

Removes a condition where we return an error to the API client if the trace payload is empty
dotnet sends an empty trace payload as a liveliness check. When we return the error, it causes ddtrace-dotnet to leak file descriptors as per [this issue](https://github.com/DataDog/datadog-lambda-extension/issues/533).
Note that 1024 file descriptors is the maximum allowed for Lambda, and afterwards the function is killed (hence the spikey graph)
Here's a screenshot with this fix and without:
I believe this change was simply good error handling, and not necessarily an intentional behavior change. We still should investigate the high fd use here for dotnet, and I'm working with that team to identify why we're using so many.
My smoke tests should be sufficient, I'm happy to show you the result or …

fix: tolerate empty trace payload body

---

profiling-replayer/src/main.rs

Adds an option `--print-stacks` which prints out the stack samples. Very verbose, meant for exploring or debugging profiles.
I wanted to see the stacks without having to upload to Datadog.
This is just a utility that isn't used for prod or shipping code in any way.
No changes.

feat(profiling-replayer): add the ability to print stacks

---

cmake/DatadogConfig.cmake.in

Updates cmake config to be used with cmake builds. dd-trace-py would like to use this. See pending PR which basically hard-coded this change https://github.com/DataDog/dd-trace-py/pull/12073/files#diff-26c9bef493aa48c10dd1e6cc3b1f87e8ac4b9c0034a66ad3d6228d8f0be5e655R120-R166

profiling: update DatadogConfig cmake to be used for windows builds

---

crashtracker-ffi/cbindgen.toml
crashtracker-ffi/src/crash_info/builder.rs
crashtracker-ffi/src/crash_info/sig_info.rs
crashtracker-ffi/src/crash_info/stackframe.rs
crashtracker-ffi/src/crash_info/stacktrace.rs
crashtracker-ffi/src/demangler/datatypes.rs
crashtracker-ffi/src/demangler/mod.rs
crashtracker/src/crash_info/stacktrace.rs
ddcommon-ffi/src/string.rs
ddcommon-ffi/src/utils.rs
examples/ffi/crashinfo.cpp
profiling-ffi/cbindgen.toml
profiling-ffi/src/string_storage.rs

This PR tries to improve a bit the crashtracker ffi APIs.
The goal is to simplify the crashtracker ffi API and adding code in the `crashinfo.cpp` example.
- When passing an address, instead of asking for a string, pass a `usize` (expecting it to be 64bit on x86_64, and 32bit on x86 architecture) and build a `0x`-prefixed string from it.
- *Experimental* : 
`ddog_crasht_CrashInfoBuilder_with_stack` adds the callstack of the crashing threads but only the callstack.
If we want to add the crashing thread (`ThreadData`), we have to duplicate the callstack and make one calls to `ddog_crasht_CrashInfoBuilder_with_stack` and `ddog_crasht_CrashInfoBuilder_with_thread`.
Instead, we check the `crashed` field, and call into `with_stack` to add a duplicate of the callstack thread (if it's true) and …

[crashtracking] Little improvements to the FFI api

---

Cargo.lock
Cargo.toml

* Bump workspace version to 16.0.0
The major version increase is necessary because of some breaking changes in the crashtracker APIs.

Prepare for 16.0.0 release

---

data-pipeline/src/telemetry/mod.rs
data-pipeline/src/trace_exporter/mod.rs

Makes the `runtime_id` property configurable by library clients.

Make runtime configurable

---

library-config-ffi/src/lib.rs
library-config/src/lib.rs

* Add Target enum with platform detection
* expose path dependending on target for wasm intergation
The crate library-config fails to compile on WASM due to missing const definitions.

[library-configuration] Expose config file path for wasm dependencies

---

data-pipeline-ffi/src/trace_exporter.rs
data-pipeline/src/trace_exporter/mod.rs

Add a new method to enable telemetry metrics in the trace exporter.

Add function in order to enable telemetry metrics.

---

library-config/src/lib.rs

Invert the path returned by `Configurator::local_stable_configuration_path` and `Configurator::fleet_stable_configuration_path` because they were wrong

[library-configuration] Fix fleet and local path inversion

---

crashtracker/src/lib.rs
crashtracker/src/receiver/entry_points.rs
crashtracker/src/receiver/mod.rs
remote-config/src/fetch/multitarget.rs
sidecar-ffi/src/lib.rs
sidecar-ffi/tests/sidecar.rs
sidecar/src/entry.rs
sidecar/src/log.rs
sidecar/src/service/blocking.rs
sidecar/src/service/sidecar_interface.rs
sidecar/src/service/sidecar_server.rs
sidecar/src/service/tracing/trace_flusher.rs
tinybytes/src/bytes_string.rs

- This includes back-propagating crashtracker logs (i.e. doing the main crashtracker accept+dispatch loop directly in the sidecar).
- Relaxes .unwrap() calls with `if let` to avoid spurious panics.
- forked processes have the same session id than their parent. Do not reset the primary session on fork.

Enhance logging and add fork handling for sessions

---

ruby/README.md
ruby/Rakefile
ruby/lib/libdatadog/version.rb

https://github.com/datadog/libdatadog/tree/main/ruby#releasing-a-new-version-to-rubygemsorg
Enable Ruby to use libdatadog v16.0.1. Of particular interest, this includes improvements to crashtracking and the managed string table needed by https://github.com/DataDog/dd-trace-rb/pull/4331 .
N/A
I've tested this release locally using the changes in https://github.com/DataDog/dd-trace-rb/pull/4353 .

[PROF-11306] Package libdatadog v16.0.1 for Ruby

---

data-pipeline-ffi/src/trace_exporter.rs
data-pipeline/src/telemetry/mod.rs

Waits for the task completion so the enqueued metrics are properly flushed.

Wait for telemetry client to finish so the metrics are flushed.

---

library-config/src/lib.rs

* Add custom deserializer for the configuration map to not error on unknown keys

[library-config] Skip error on unknown config key

---

Cargo.toml

Changes the `opt-level` of the `bench` profile to get more stable benchmark results.
The benchmark results are sensitive to strange things like changing the version number of the main project. This has been consistently repeated in a test PR #874. As to the reason why, I can only speculate that optimizing for size can change the placement of code and or fields in unexpected ways. This behavior goes away with the settings in this PR.
Nope
Was validate in PR #878

Stabilize benchmarks using opt-level

---

remote-config/src/fetch/multitarget.rs

This would eventually lead to a panic in debug builds due to `0u - 1`.

Fix possible race confition when adding, then removing remote config services

---

tinybytes/src/bytes_string.rs
trace-utils/src/span/v04/span.rs

tracestate, attributes and flags are optional. Following the existing pattern, when these have a default value, serialization ignores them.
> [!IMPORTANT]  
>Ideally, we should have them optional marked in the models itself, so we can get all the typeness but for now following the existing approach.
Failing .NET tests
Use local agent to check the serialized payload.
eg
```
[
[
{
"service": "data-pipeline-test",
"name": "test-name-1",
"resource": "test-resource-2",
"type": "",
"trace_id": 1,
"span_id": 1,
"start": 1739884373314738000,
"duration": 11000000,
"metrics": {
"_dd.measured": 1.0,
"_sampling_priority_v1": 1.0
},
"span_links": [
{
"trace_id": 1,
"trace_id_high": 0,
"span_id": 0
}
]
},
....
```

fix: skip serialization of optional properties in a span link

---

data-pipeline-ffi/src/error.rs
data-pipeline/src/trace_exporter/error.rs
data-pipeline/src/trace_exporter/mod.rs

Currently, we are not using the logic that involves parsing TCP, UDS, or Windows named pipe schemes, which breaks the detection of the connector, specifically for Windows named pipes.
This change introduces the use of ddcommon::parse_uri and also improves the error message returned when URL parsing fails.
Also, this PR follows commit conventions.
Windows named pipeline is broken in data pipeline.
1. Setup a real agent on Windows box. (test agent doesn't support Windows named pipes, the support will be added later)
2. update datadog.yml with following config
```
apm_config:
windows_pipe_name: foo
```
3. Use "windows:\\.\pipe\foo" as agent url.

fix(data-pipeline): use ddcommon::parse_uri for input URL parsing

---

.devcontainer/devcontainer.json
README.md

- ensures consistent development setup
- includes necessary dependencies and configurations
- allows step-in for things like how container id is generated since the whole workspace is inside a container
I went with minimal setup and targeting only one OS, but this can be extended with multiple container (debian, alpine etc)
I have been using it locally by keeping in my stashes, but this is general problem since we are all (or almost) on osx and want to test and debug how the libraries behave on linux. 
none.
Follow the readme.

feat: add dev container for consistent development environment

---

ipc/src/platform/unix/channel.rs
ipc/src/platform/unix/channel/async_channel.rs
ipc/src/platform/windows/channel/async_channel.rs
ipc/src/sequential.rs
ipc/tarpc/tarpc/src/server.rs
ipc/tarpc/tarpc/src/server/in_flight_requests.rs
ipc/tarpc/tarpc/src/server/incoming.rs
ipc/tarpc/tarpc/src/server/tokio.rs
sidecar/Cargo.toml
sidecar/src/service/sidecar_server.rs

Without this change file descriptions were not sent when send_with_fd was interrupted by a signal, causing the connection to become broken.
Also use statm for memory tracking in sidecar (we don't need full accuracy for the watchdog).

Handle EINTR in blocking ipc sender

---

.github/CODEOWNERS

Adds serverless as a code owner for dogstatsd
AJ asked me to do this.
Probably should have done this while they still had a PR open, so we can see that it works.

ci: add serverless as code owners for dogstatsd

---

profiling-ffi/src/profiles.rs
profiling-replayer/src/replayer.rs
profiling/examples/profiles.rs
profiling/src/api.rs
profiling/src/internal/observation/observations.rs
profiling/src/internal/observation/timestamped_observations.rs
profiling/src/internal/observation/trimmed_observation.rs
profiling/src/internal/profile/fuzz_tests.rs
profiling/src/internal/profile/mod.rs
profiling/tests/wordpress.rs

Uses a slice instead of a Vec to avoid unnecessary allocations and copies
Fewer allocations are better.

perf(profiling): don't unnecessarily copy sample values

---

ddcommon-ffi/src/cstr.rs

Fix the `ffi::Cstr` and `ffi::Cstring` types.
These types are used to pass rust CString across API boundaries, but there is a bug because of off by one errors in the lenghts which sometimes include the nul terminator and sometimes don't.

fix: nul terminator missing on ffi::Cstr

---

Cargo.lock
trace-mini-agent/Cargo.toml
trace-utils/Cargo.toml
trace-utils/src/send_with_retry/mod.rs
trace-utils/src/stats_utils.rs

* Add a new feature "mini_agent" on trace_utils and do not use it bydefault. This is going to be used to progressively separate code used by only the mini agent from common code=
* Hide flate2 usage under the compression flag
* Hide hyper-proxy dependency under the proxy feature flag

refactor(trace-utils): make flate2 and and hyper-proxy dependencies optionnal 

---

dogstatsd/src/datadog.rs
dogstatsd/src/flusher.rs
dogstatsd/tests/integration_test.rs
serverless/src/main.rs

The original idea was to make retries happen from the users of this lib, but now that we've added compression this adds the overhead of re-compressing the request on each retry. This PR changes the behavior to retry in the request client instead.
Saves CPU time

Push retry strategy into client

---

dogstatsd/src/constants.rs
dogstatsd/src/metric.rs

Optimizes how `parse` is implemented.
Previously, the vector allocation would be undefined, from data that can be counted beforehand.
This reduces allocations and conditions on the loop.
- Saves around 2-3ms.
- Dedup doesnt work, we are not fixing that here.
- Changes MAX_TAGS to `100`, as per our internal docs – needs to be re-reviewed in a future PR tho.
Tested manually on a project using this method.

[dogstatsd] optimize `parse` function in `SortedTags`

---

dogstatsd/src/metric.rs
live-debugger/src/expr_eval.rs
sidecar/src/log.rs
trace-obfuscation/src/obfuscate.rs
trace-obfuscation/src/replacer.rs

This skips some slow tests on miri.
It also converts a test to use `&str` instead of `String` to speed up the miri run for that test (rather than skipping it).
The miri job is slow again.
It's still a bit slow after making this change, but it shaved off a few minutes and these were the "SLOW" tests.
Just regular test commands are fine.

test: ignore some slow tests on miri, speed up one test

---

profiling-ffi/src/profiles.rs
profiling-replayer/src/replayer.rs
profiling/src/api.rs
profiling/src/internal/function.rs
profiling/src/internal/profile/fuzz_tests.rs
profiling/src/internal/profile/mod.rs
profiling/src/pprof/proto.rs
profiling/tests/wordpress.rs

This removes `start_line` from all the different profile representations. This is a compatibility break, albeit probably a small one because most profilers did not use this field before.
This saves memory and a small number of CPU cycles. There is no business value for this field right now, with none planned, so let's claim this back.
It doesn't impact the in-wire size except for .NET, which was previously setting this field.
Remove `start_line` from your structs if needed, then test as normal. You will have to update tests if you have functions which differed only in their `start_line`, but otherwise no other changes should be necessary.

perf(profiling)!: remove Function.start_line

---

ipc/src/rate_limiter.rs
sidecar/src/shm_remote_config.rs
sidecar/src/tracer.rs

Works around https://github.com/mozilla/cbindgen/issues/993 in cbindgen 0.27+

Avoid struct<Generic = ()> in cbindgen-read definitions

---

data-pipeline/tests/snapshots/compare_v04_trace_snapshot_test.json
data-pipeline/tests/test_trace_exporter.rs
trace-utils/tests/snapshots/compare_v04_trace_snapshot_test.json
trace-utils/tests/test_send_data.rs

Add `span_links` and `span_events` in the integration test of the v04

Add span links and span events in the integration test

---

profiling-ffi/src/exporter.rs
profiling/src/exporter/mod.rs
profiling/tests/form.rs

This PR tweaks the `internal` metadata section that gets reported along with every profile to include the libdatadog profiling crate version (which matches the libdatadog version currently).
In incident 35390 I had to manually check which libdatadog version a given profiler version was reporting and I missed having a nice unified way to figure this out.
Arguably this could go in the `info` version instead, but I decided to keep it as internal info for now, and we can always change it later.
I've updated the unit tests and also validated this works with the Ruby profiler.

[NO-TICKET] Include libdatadog profiling crate version when reporting profiles

---

.github/workflows/miri.yml
Cargo.lock

This updates nextest to the latest version in the miri job and runs the miri tests in parallel, currently with 4 jobs.
It also updates the lock file which... I'm not sure how it ever got out of order to begin with.
The Miri job is up to 20+ minutes even after I skipped a handful of slow tests in a previous PR.
With this, it now takes ~7-8 minutes, which is better more in line with other jobs.
I tried using a larger runner in #955, that didn't work because it would have taken longer than 16 minutes just to get the runner. I don't know if this is because we aren't approved for them, or there aren't enough provisioned. Regardless, the net effect is it is too slow. Just use standard runners but more of them.
This PR is a bit wasteful in the sense that we rebuild everything in every job. I …

ci: use parallel jobs for Miri

---

Cargo.lock
ddcommon-ffi/src/handle.rs
ddcommon-ffi/src/result.rs
examples/ffi/exporter.cpp
examples/ffi/profiles.c
profiling-ffi/Cargo.toml
profiling-ffi/cbindgen.toml
profiling-ffi/src/exporter.rs
profiling-ffi/src/profiles.rs
profiling-replayer/src/main.rs
profiling/examples/profiles.rs
profiling/src/exporter/mod.rs
profiling/src/internal/profile/fuzz_tests.rs
profiling/src/internal/profile/mod.rs
profiling/tests/form.rs

Passes the `EncodedProfile` as a Rust object, rather than forcing it through the C-FFI straw.
We ended up having to make a new `Vec` and copy the bytes from the pprof in, even though they were already there.  This saves the allocation and copy (which can be several MB).
Existing tests

[profiling] Reduce copying and allocation in exporter

---

.github/workflows/lint.yml
Cargo.lock

Dependabot was suggesting bumping these two, and they seem to work fine.
Keep our dependencies up-to-date.
N/A
Our existing test coverage should be enough to cover these.

build: bump `protobuf` and `ring` as suggested by dependabot

---

trace-utils/Cargo.toml

Issuing cargo test without specifying any dependecies on trace-utils crate failed due to some needed hyper features.

Fix hyper development dependencies in trace-utils.

---

ddcommon/src/entity_id/unix/mod.rs

This reverts commit 9f66ffaf30376ef1b3c7677e255776e6176a9b5b.
There was a confusion with spec. The confirmed behavior is 
| Container ID Available | Inode Available     | `Datadog-Container-Id` | `Datadog-Entity-Id` |
|------------------------|---------------------|--------------------------|----------------------|
| ✅ Yes (`123`)         | —                   | `123`                    | `ci-123`             |
| ❌ No                  | ✅ Yes (`456`)       | _(skipped)_              | `in-456`             |
| ❌ No                  | ❌ No                | _(skipped)_              | _(skipped)_          |
- ✅ = available / known  
- ❌ = not available / unknown  
- `ci-` prefix stands for "container ID"  
- `in-` prefix stands for "inode ID"
We already have above logic in place.
None
There …

Revert "fix: update entity ID computation to support external environment prefixing (#953)"

---

.github/workflows/lint.yml
Cargo.lock
alloc/Cargo.toml
alloc/src/chain.rs
alloc/src/linear.rs
alloc/src/virtual_alloc.rs
ddcommon-ffi/Cargo.toml
ddcommon-ffi/src/array_queue.rs
profiling/Cargo.toml
profiling/src/api.rs
profiling/src/internal/label.rs
profiling/src/internal/observation/observations.rs
profiling/src/internal/owned_types/mod.rs
profiling/src/internal/profile/fuzz_tests.rs
profiling/src/internal/sample.rs
profiling/src/internal/stack_trace.rs
trace-utils/Cargo.toml

1. This update bolero from v0.10 to v0.13, and fixes the deprecation warnings about `gen` for 2024 edition compatibility.
2. Removes bolero-generator as a direct dependency, since it's part of the bolero crate and exposed there as `bolero::generator` (and at least currently it is not controlled by a feature, so it's always there).
3. This pins the version of cargo-bundle-licenses to v4.0.0. We pinned this in the past, not sure why it was unpinned.
I was fixing some fuzz tests on another branch realized this was a big enough chunk that I should split it out.
If there are any fuzz errors in profiling, we'll ignore them and force-merge if needed. Since I haven't fixed those in this PR, they may fail.
Everything should run the same, just updates.

chore: update bolero and pin cargo-bundle-licenses

---

Cargo.lock
ddcommon/Cargo.toml
ddcommon/src/lib.rs
ddcommon/src/tag.rs
profiling-ffi/src/exporter.rs
profiling/Cargo.toml
profiling/src/exporter/mod.rs
profiling/tests/form.rs

This PR adds the `runtime_platform` tag as per [Profiler common tags](https://docs.google.com/spreadsheets/d/1LOGMf4c4Avbtn36uZ2SWvhIGKRPLM1BoWkUP4JYj7hA/edit?gid=0#gid=0). It uses the target triple, which is a bit different from what Ruby did before, but close enough.
Up until now, only Ruby was reporting this tag, but in incident 35390 it would've been useful to have this information, and it seems easy enough to add.
We should probably talk to the Datadog platform team to figure out if there's a "standard" or "approved" tag name, but this one is already in use so let's not block on that. We can migrate later as needed.
I've added test coverage for this feature. I've also tested it with the Ruby profiler.

feat(profiling): add runtime_platform tag automatically

---

Cargo.lock

This updates the versions of the crates `cc` (to 1.2.17) and `ring` (to 0.17.14), and drops `spin`.
The ring crate has dependabot alert on it. It requires an updated `cc` crate, which has been problematic because the 1.2.x series has been incompatible with our *-alpine-linux-musl builds. They recently merged and releases a fix (or at least, it should be fixed) in v 1.2.17, so we can now update cc too.
These changes mean spin is no longer used, so it's dropped.
This PR is used in favor of #970 because it also adjusts the windows version _down_, which is wrong. Dependabot also doesn't know to regenerate the 3rd party license file.
Please verify that everything works in gitlab too before merging.
Everything should work as normal with regular testing.

build: update cc, ring, and remove spin

---

ddcommon/src/connector/mod.rs
ipc/src/platform/unix/mem_handle.rs

I was informed by the customer that they got a not supported error, but actually it's an ENOSYS ... :-)
Updating it to the right value to make it work for them.

fix: support both ENOTSUP and ENOSYS in shm_open fallback

---

live-debugger/src/redacted_names.rs

This flag is only to be set on the first usage of redacted names.
Regression introduced by b39c6ee1 (was noticed when integrating in dd-trace-php).

Fix REDACTED_NAMES_INITIALIZED

---

data-pipeline-ffi/src/trace_exporter.rs
data-pipeline/src/trace_exporter/mod.rs
trace-utils/src/trace_utils.rs

This PR changes the tokio runtime type used in the data-pipeline from `current_thread` to multi-threaded, with a single worker thread.
There is a big in how we run background tasks such as the info fetcher and the stats exporter in the trace exporter. We currently spawn them in the runtime held by the trace exporter. This runtime is a `current_thread`, which according to the tokio documentation only runs background task when the runtime is in a `block_on` https://docs.rs/tokio/latest/tokio/runtime/index.html#current-thread-runtime-behavior-at-the-time-of-writing.
This is called only when sending traces, which means that background tasks are paused in between traces submissions. So if the stats exporter is sending data for instance, and the runtime pauses the requests might be interrupted …

fix: tokio runtime should be multithread

---

ddcommon/src/connector/mod.rs

*Initialise the crypto provider even if without the `use_webpki_roots` feature
This has fallen though the crask of testing in the CI because running tests on the full workspace enables `use_webpki_roots` though feature unification. But depending only on data-pipeline makes it break.
From bisecting these tests staring being broken in #983, probably because the previous version of bollard we depended on for creating test containers was creating the crypto provider for us during testing...

fix(ddcommon_connector): the crypto provider also needs to be initialized with webpkis disabled

---

builder/Cargo.toml
ddcommon-ffi/src/lib.rs
ddcommon-ffi/src/tracer_metadata.rs
profiling-ffi/Cargo.toml
profiling-ffi/src/lib.rs

In dotnet we're gonna need to expose the FFI 
Related to 
https://datadoghq.atlassian.net/browse/APMAPI-1072
https://github.com/DataDog/libdatadog/pull/867
Integrated in the dotnet tracer locally, it's working for me under WSL, I can see and decode the linux file descriptor.

feat: Expose ddcommon memfd_create

---

.github/CODEOWNERS

Currently, bin_tests are universally owned by the core team, even though the overwhelming majority of the actual files are related to crashtracking.
This PR updates the ownership, but still allows core to own the non-crashtracking tests.
This was easy to do, but it might actually be cleaner to refactor the bin tests in order to propagate ownership in a more straightforward way.
Realign the PR review process mostly

Granularize CODEOWNERS

---

trace-utils/src/test_utils/datadog_test_agent.rs

It rarely happens, but it is possible for the container running the test agent for integration tests to reset the network connection even after the agent is ready. This PR adds retry logic for the http requests we send to the agent that aren't part of what's actually being tested. Currently that is starting a test session, validating test snapshots, and getting all the traces that the agent has received. This should _hopefully_ fix flakiness where you see an error like `Request failed: hyper_util::client::legacy::Error(SendRequest, hyper::Error(Io, Os { code: 104, kind: ConnectionReset, message: "Connection reset by peer" }))` 
Baklava should be flaky, not our tests
I tested the retry logic works by breaking a snapshot and observing that it retried the correct number of times. I don't …

APMSP-1930 add retry logic for test setup requests to test agent

---

data-pipeline/src/trace_exporter/mod.rs
tinybytes/src/bytes_string.rs
tinybytes/src/lib.rs
trace-utils/src/msgpack_decoder/decode/error.rs
trace-utils/src/msgpack_decoder/decode/map.rs
trace-utils/src/msgpack_decoder/decode/meta_struct.rs
trace-utils/src/msgpack_decoder/decode/metrics.rs
trace-utils/src/msgpack_decoder/decode/number.rs
trace-utils/src/msgpack_decoder/decode/span_event.rs
trace-utils/src/msgpack_decoder/decode/span_link.rs
trace-utils/src/msgpack_decoder/decode/string.rs
trace-utils/src/msgpack_decoder/v04/mod.rs
trace-utils/src/msgpack_decoder/v04/span.rs
trace-utils/src/msgpack_decoder/v05/mod.rs
trace-utils/src/span/mod.rs
trace-utils/src/tracer_payload.rs

Use &[u8] in the msgpack decoder instead of Bytes and produce a SpanSlice which contains &str instead of BytesString. This allows to parse non-owned buffer containing traces. It also provides a from_bytes wrapper which uses the same parsing logic but convert the &str to BytesString based on the given Bytes buffer.
The trace exporter needs to support reading traces from borrowed buffer.
This PR also refactors the string, map and number decoding logic to be moved to separate modules.

[APMSP-1764] Support borrowed buffer for msgpack decoding

---

Cargo.lock
bin_tests/Cargo.toml
crashtracker/Cargo.toml
ipc/Cargo.toml
ipc/src/platform/mem_handle.rs
ipc/src/platform/unix/channel.rs
ipc/src/platform/unix/mem_handle.rs
ipc/src/platform/unix/mem_handle_macos.rs
ipc/src/platform/unix/sockets.rs
ipc/src/platform/windows/mem_handle.rs
sidecar/Cargo.toml
spawn_worker/Cargo.toml

This upgrades nix from v0.27 to v0.29. There's an off-by-one error in the new `Backlog` type, so this lowers the backlog used for `listen` from 128 to 127.
Also pins simd-json to 0.14. I noticed v0.15 requires Rust 1.85 and I was editing this file anyway.
Version 0.29 was already in our tree, so this removes a duplicate dependency (everything is now on 0.29).
I tried to use Cursor to do this upgrade, and it failed, even when I provided the changelog for versions 0.29 and 0.28. Did it all manually.
Everything should test the same.

build: upgrade nix from 0.27 to 0.29

---

Cargo.lock

Bumps allocator-api2 from v0.2.18 to v0.2.21.
I hit a weird build error locally when doing `cargo bench -- --list` and it seemed like updating would fix it, and it did.
Everything should work as normal.

build: bump allocator-api2 to v0.2.21

---

profiling-ffi/src/profiles/datatypes.rs
profiling-ffi/src/profiles/interning_api.rs
profiling-replayer/src/replayer.rs
profiling/src/api.rs
profiling/src/internal/label.rs
profiling/src/internal/profile/fuzz_tests.rs
profiling/src/internal/profile/interning_api/mod.rs
profiling/src/internal/profile/mod.rs

Labels now have strings rather than `Option<T>` where T is some string type.
This supersedes #959, which got all tangled and also out-of-date from main.
The fuzzer can get into weird differences between `None` and `Some(0)`/`Some("")`/etc.
There is another issue with labels in the fuzzer, but I wanted to fix this issue independently so it's easier to review. This may need to be force-merged if the only failure is the profiling fuzzer.
Update your APIs to use strings directly instead of Option of strings, then run as normal.

refactor(prof): Labels have T directly, not Option<T>

---

.github/workflows/test.yml

This stops using the buildx bake cache.
This routinely seems to hang, possibly the same as this:
https://github.com/docker/buildx/issues/537
Caches are hard, some would say one of the hardest problems in computer science.
CI should run as normal, the buildx bake job should just be a bit slower, but shouldn't try to cache and hopefully 🤞🏻 the slowdown is acceptable.

ci: stop caching buildx bake

---

data-pipeline/src/trace_exporter/mod.rs
sidecar/src/service/sidecar_server.rs
trace-mini-agent/src/trace_processor.rs
trace-utils/benches/deserialization.rs
trace-utils/src/msgpack_decoder/v04/mod.rs
trace-utils/src/span/mod.rs
trace-utils/src/span/trace_utils.rs
trace-utils/src/span/v05/dict.rs
trace-utils/src/span/v05/mod.rs
trace-utils/src/test_utils/mod.rs
trace-utils/src/trace_utils.rs
trace-utils/src/tracer_payload.rs
trace-utils/tests/test_send_data.rs

This refactor splits the logic in `collect_trace_chunks` between the trace exporter spans (v04 and v05) and the mini agent spans (pb::Spans).
it completely removes usage of the `TraceCollection` struct from data-pipeline, and instead introduces the `TraceChunks` enum to differentiate between v04 and v05.
Currently the way the code is structured makes replacing ByteString with the slice harder due to shared lifetime.
Furthermore, the enums encodes two different codepaths, the spanBytes and span pb which never interact with each other. So having function that handle both span bytes and pb spans is pure complexity overhead.
This refactor also removes a bunch of panics and lines of code that were here because to handle the "fake" pb spans and trace exporter spans overlap, which is practice …

refactor: split collect_chunks into two methods

---

Cargo.lock
ddcommon/Cargo.toml

Updates rustls-native-certs to 0.8.1.
`connector::tests::test_missing_root_certificates_only_allow_http_connections` test fails when run from `ddcommon` directory.
```
--- STDERR:              ddcommon connector::tests::test_missing_root_certificates_only_allow_http_connections ---
thread 'connector::tests::test_missing_root_certificates_only_allow_http_connections' panicked at ddcommon/src/connector/mod.rs:231:9:
assertion failed: matches!(connector, Connector::Http(_))
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
PASS [   1.250s] ddcommon connector::tests::test_hyper_client_from_connector
------------
Summary [   1.286s] 58 tests run: 57 passed, 1 failed, 0 skipped
FAIL [   1.218s] ddcommon connector::tests::test_missing_root_certificates_only_allow_http_ …
```

fix(ddcommon): Update rustls-native-certs to 0.8.1

---

ddcommon/src/connector/mod.rs

Add ubuntu ssl cert directory for `test_missing_root_certificates_only_allow_http_connections`.
Test `test_missing_root_certificates_only_allow_http_connections` failing on ubuntu when ddcommon feature `use_webpki_roots` is disabled.
Follows https://github.com/DataDog/libdatadog/pull/1033
Since `trace-mini-agent` imports trace-utils with the [mini_agent feature](https://github.com/DataDog/libdatadog/blob/ac445fa8810d4a07f536e415fd00c92648ab8f85/trace-mini-agent/Cargo.toml#L26) enabled, the [use_webpki_roots feature](https://github.com/DataDog/libdatadog/blob/ac445fa8810d4a07f536e415fd00c92648ab8f85/trace-utils/Cargo.toml#L68) is enabled for test runs. This means that `test_missing_root_certificates_use_webpki_certificates` runs in CI while …

fix(ddcommon): Add ubuntu ssl cert directory for unit test

---

ipc/src/platform/channel/metadata.rs
ipc/src/platform/platform_handle.rs
ipc/src/transport/blocking.rs
ipc/src/transport/mod.rs
profiling-ffi/src/profiles/datatypes.rs
sidecar/src/entry.rs
sidecar/src/service/blocking.rs
tinybytes/src/bytes_string.rs

Fixes these lints on nightly clippy:
- `clippy::derivable_impls`
- `clippy::empty_line_after_outer_attr`
- `clippy::io_other_error`
I was working with nightly for another reason, and figured I'd run clippy to see what it surfaced. All of these changes look like improvements to me, so I figured I'd ship them.
One of the nightly lints, `clippy::ptr_eq`, seems wrong. That lint seems to _intend_ to warn when you have two references, and you turn them into pointers to compare the pointers, but in practice it just whines about every pointer comparison. I'll leave it for now.
Another one is `clippy::large_enum_variant`. I think it's legitimate, but I think best left for a different PR. There are two cases, the first being:
```
warning: large size difference between variants
--> …
```

style: fix some lints from nightly clippy

---

data-pipeline/src/agent_info/fetcher.rs

Add a wait loop in the test checking if data has been swapped
This test is still not 100% deterministic, but between the time the mock returns the response and we swap the atomic pointer holding the agent_info we only need to perform very few operations. We wait for a maximum of 1s before failing the test and that should give way more time than necessary.
@morrisonlevi  messaged me about a failing test in data-pipeline.

fix(data-pipeline): add a wait loop in the test checking if data has been swapped

---

Cargo.lock

See https://github.com/DataDog/libdatadog/security/dependabot/26.
I saw this in my console when pushing another branch:
```
remote: GitHub found 1 vulnerability on DataDog/libdatadog's default branch (1 low). To find out more, visit:
remote:      https://github.com/DataDog/libdatadog/security/dependabot/26
```
Nope, just a routine update for security reasons.
Should test as normal, just a routine upgrade.

build: upgrade tokio to avoid potential unsoundness

---

datadog-sidecar/src/service/tracing/trace_flusher.rs
datadog-trace-utils/src/test_utils/mod.rs
datadog-trace-utils/src/trace_utils.rs

- The `MAX_PAYLOAD_SIZE` used in trace_utils::coalesce_send_data() was 50mb. The agent drops payloads greater than > 25mb and returns a 413. So it was potentially combining payloads that would result in an error and drop. 
- In the sidecar's trace_flusher, payloads were being dropped if the queue's size exceeded the min drop size. The correct behavior is to check if the payload being enqueued exceeds min drop size, not the entire queue. Additionally, the default minimum drop size was 10mb. This has been changed to `trace_utils::MAX_PAYLOAD_SIZE`. 
- When the sidecar's trace_flusher was dropping a payload that was too large it was still adding that payload's size to the queue size. This could have lead to subsequent payloads being dropped, regardless of their size, due to an incorrectly …

APMSP-1969 fix dropped trace payloads for the sidecar

---

datadog-crashtracker/src/crash_info/error_data.rs

This PR creates a normalizer which caches VMA (Virtual Memory Addresses) to speed up normalization.
For each frame we call into blazesym. If we do not instruct blazesym to cache the VMA, it will parse them at each call.
Added also build_id caching. `build ids` are important thingy for remote symbolication (in datadog backend)
There is no caching in the blazesym rc2 for names resolution. We would need to upgrade blazesym to benefit from it.

fix(crashtracker) Cache virtual memory address to speed up normalization

---

Cargo.lock
build-profiling-ffi.sh
builder/Cargo.toml
builder/src/builder.rs
builder/src/lib.rs
builder/src/profiling.rs
datadog-crashtracker/Cargo.toml
datadog-profiling-ffi/Cargo.toml
windows/build-artifacts.ps1

This PR adds 'lib' to datadog-profiling-ffi crate type list so it symbols can be reexported in an external project.
Some SDKs were already integrating some parts of libdatadog using a language framework and profiling using the released artifacts. As a result there were two libraries, one generated by framework and another one for wrapping libdatadog-ffi functions. This led to symbol duplication across libraries. In order to overcome that issue, hence reducing the overall size, we decided to merge both libraries, for that we needed to compile profiling as a 'lib'.
As a side effect the builder and build scripts has been modified in order to overcome problems with LTO linkage where cargo build has some issues when adding 'lib' to the crate-type list.
Another side effect is that when …

Make datadog-profiling-ffi exportable in external projects.

---

data-pipeline-ffi/src/trace_exporter.rs

This pull request introduces support for a new `client_computed_stats` configuration in the `TraceExporterConfig` structure, enabling more flexible handling of stats computation in Datadog's trace exporter. The changes include updates to the configuration structure, a new method for setting the `client_computed_stats` flag, and corresponding logic and test cases to ensure proper functionality.
System tests are failing in .NET
https://dev.azure.com/datadoghq/dd-trace-dotnet/_build/results?buildId=177394&view=logs&j=b8b8344c-200f-58ee-939b-983868d59647&t=25e5ff76-b821-5391-6a6d-ead53dc1b1b4&l=631
A current use of this new API is ASM. When ASM is enabled and APM is disabled, tracers use this to make sure stats computation is skipped.
Test cases.

feat: add client_computed_stats to TraceExporterConfig and expose API to set it

---

Cargo.lock
Cargo.toml

This  prepares for the v18.0.0 release of libdatadog.
Bob asked me to release a new version for the PHP tracer to use in their own new release.
There is a known issue with crashtracking with forks on v17 that is still not fixed, to the best of my knowledge.

Prepare for libdatadog v18.0.0

---

datadog-remote-config/src/path.rs

Add `AGENT_CONFIG` and `AGENT_TASK` to the RemoteConfigProduct in the remote-config crate.
We need those products to use them in the tracer flare.
Also I reorder the enum in alphabetical order.

[APMSP-1973] Add products in the remote-config crate

---

tinybytes/src/lib.rs
tinybytes/src/test.rs

Allow to replace the refcounted type used in tinybytes, by using a custom dispatch table for clone a drop

feat(tinybytes): use a custom ref counted cell for Bytes with dynamic dispatch

---

builder/src/arch/apple.rs
datadog-live-debugger/src/probe_defs.rs
datadog-sidecar/src/shm_remote_config.rs
spawn_worker/src/unix/spawn.rs

Fixes new lints from the Rust 1.87 release.
A new release was made, so my CI now fails.
I fixed a bunch of these before the release dropped (#1038), so thankfully it's not too much work now.
The `allow(large_enum_variant)` was based on @bwoebi's recommendation. He doesn't feel these are problematic because it's not embedded in other data structures, and is used on the stack. Plus it's more invasive to fix, so even if we do fix it, the first step to unblock CI is to allow it. 
Should be the same, it's just style changes.

style: fix lints from Rust 1.87

---

ruby/Rakefile
ruby/lib/libdatadog/version.rb
ruby/spec/gem_packaging.rb

This PR includes the changes documented in the "Releasing a new version to rubygems.org" part of the README: https://github.com/datadog/libdatadog/tree/main/ruby#releasing-a-new-version-to-rubygemsorg
It also includes an updated to the `gem_packaging.rb` test to add the new `INTERNED_EMPTY_STRING` public symbol added in #917 .
Enable Ruby to use libdatadog v18.1.0. This includes A LOT of changes to profiling, crashtracking, configuration, process discovery etc that have been pending for Ruby for too long.
The `INTERNED_EMPTY_STRING` new symbol seems ok to have (e.g. I don't expect it to clash with other libraries), but just in case I will discuss with @danielsn prefixing it with `ddog_`.
Also it's cool to see our tests working! A new symbol that's not prefixed with the expected strings …

[PROF-11524] Package libdatadog v18.1.0 for Ruby

---

bin_tests/tests/crashtracker_bin_test.rs
datadog-crashtracker/src/collector/emitters.rs
datadog-crashtracker/src/crash_info/builder.rs

Filter (aka remove) the crashtracker from the stack trace reported. This is done by using the stack pointer we can extract from the `ucontext` passed to the signal handler (from the actual crash site) and only collect a frame if it's stack pointer is above or equal to that address. Everything below that stack pointer is part of the signal handler and unwinding code in the crash tracker and not relevant for troubleshooting. 
The crash tracker reports end up in the "Error tracking" product which [groups by](https://docs.datadoghq.com/tracing/error_tracking/error_grouping/?tab=android#default-grouping) (among other things)
> `error.stack`: The filename and function name of the top-most meaningful stack frame.
As we have the crash tracker itself in all PHP (and I think Ruby) stack traces, the …

remove the crashtracker itself from crash stack trace

---

ddcommon/src/unix_utils.rs

Avoids unused imports for macOS.
I don't like having warnings in my output when developing, very distracting.
Do people develop in Linux containers or how do they not hit these themselves?
No change, or shouldn't be. Regular testing applies.

style: fix unused imports for macOS

---

data-pipeline/src/agent_info/fetcher.rs

Fix flaky test in the info fetcher. The previous test only waited for the endpoint to be hit but the response parsing might take a little bit more depending on the scheduler so there was a chance that the content could be None

Fix flaky test.

---

data-pipeline/src/trace_exporter/mod.rs

CI runners can be slow sometimes and the shutdown test has been flaky. Sleep less, but poll more to minimize time impact. Observation window has been changed from 1s to 5s max.
[Flakiness observed in CI runs](https://github.com/DataDog/libdatadog/actions/runs/15482749290/job/43591458483?pr=1092)

increase polling window for trace exporter shutdown unit test

---

datadog-trace-utils/src/msgpack_decoder/decode/number.rs

Unit tests that cover msgpack decoding of integers was not properly setup to validate signed numbers with value of 0 are correctly decoded. 
Just updating tests, the underlying functionality works fine.

fix msgpack integer decoder tests to correctly test zero signed numbers

---

datadog-crashtracker/src/crash_info/telemetry.rs
ddtelemetry/src/data/payloads.rs
ddtelemetry/src/worker/mod.rs

Add `is_crash` to Log message
In this [PR](https://github.com/DataDog/libdatadog/pull/1005)  we do not fill the `Stacktrace` field of the log message to reduce the size of the message.
Except that in the backend, we use that field to recognize crash log and symbolize them.
In the backend code, I saw that the `Log` struct has a `IsCrash/is_crash` field.https://github.com/DataDog/dd-go/blob/prod/trace/apps/tracer-telemetry-intake/telemetry-payload/logs.go#L65

[Crashtracker][bug]Add `is_crash`  field to Log message

---

Cargo.lock
Cargo.toml

This PR bumps the libdatadog version from 18.1.0 to 19.0.0 in preparation for release. 
Use the new log subsystem in the current integrations.
The reason for bumping the major is that there is an API change in profiling.h:
```
diff --color /home/julio/Releases/libdatadog/v18.1.0/include/datadog/profiling.h release/include/datadog/profiling.h
21c21
< extern const ddog_prof_StringId INTERNED_EMPTY_STRING;
---
> extern const ddog_prof_StringId ddog_INTERNED_EMPTY_STRING;
```

Bump libdatadog version to 19.0.0 in preparation for release

---

datadog-sidecar/src/config.rs
datadog-sidecar/src/entry.rs
datadog-sidecar/src/watchdog.rs

With very heavy bursting of PHP processes (with distinct service names) the sidecar can currently run OOM.
Providing an escape hatch for those cases.

Make max memory of sidecar configurable

---

datadog-crashtracker/src/collector/crash_handler.rs

Uses the correct `max` function instead of `min` when updating the timeout.
We were getting spurious timeouts that were breaking macos tests.
Reading the code, the sense of the logic was flipped.
While I was in there, I noticed an unnecessary `clone`.  This is problematic inside a signal handler, so I removed it for the more correct `as_deref`.
Existing tests, plus run on macos.

[crashtracker] Fix timeout math

---

data-pipeline/src/agent_info/fetcher.rs
data-pipeline/src/agent_info/mod.rs
data-pipeline/src/trace_exporter/mod.rs
data-pipeline/tests/test_fetch_info.rs

Store the result of the agent_info fetcher in a `LazyLock` and provide a `get_agent_info()` function that returns `Option<Arc<AgentInfo>>`. This makes the `AgentInfo` globally static so it can be shared between parent and child processes when they are forked. `ArcSwapOption` is thread-safe.
The Trace Exporter supports the host language forking the process the exporter runs in. This prevents the need to re-fetch agent info on every fork, which if there is frequent enough forking, may never complete and client-side stats may never get enabled.  
Unit and integration tests have been updated.

statically cache agent info responses

---

repository.datadog.yml

Add `repository.datadog.yml` to repo for custom config of the mergequeue
For the repo, `merge`, `squash`, and `rebase` merge methods are enabled, but for the `main` branch `merge` is disabled by the `require linear history` setting. By default, when no merge method is specified by the user, the mergequeue will use the first enabled method in order of `merge`, `squash`, `rebase`. Mergequeue gets confused because it sees `merge` is enabled when, in reality, it's not and the mergequeue fails to merge the PR.
If you comment `/merge` your PR will be added to the mergequeue and `squash` will be used by default.
If you wish to use `rebase` use the command `/merge -m rebase` 

set squash as the default merge method for mergequeue

---

windows/build-artifacts.ps1

Enables the datadog-log-ffi feature for windows builds.
Missed to enable it when the feature was introduced.

Enable logging feature for windows builds.

---

Cargo.lock
bin_tests/src/bin/crashtracker_bin_test.rs
datadog-crashtracker-ffi/src/collector/datatypes.rs
datadog-crashtracker/src/collector/api.rs
datadog-crashtracker/src/collector/collector_manager.rs
datadog-crashtracker/src/collector/crash_handler.rs
datadog-crashtracker/src/collector/process_handle.rs
datadog-crashtracker/src/collector/receiver_manager.rs
datadog-crashtracker/src/receiver/mod.rs
datadog-crashtracker/src/shared/configuration.rs
datadog-crashtracker/src/shared/constants.rs
ddcommon/Cargo.toml
ddcommon/src/unix_utils.rs

1. Fixes a bug where we never actually waited on child processes
2. Introduces a `TimeoutManager` which enables easier reasoning about timeouts.
3. Fixes a bug where we failed to loop on the `poll` when we had a resumable error code
4. Uses static errors instead of `anyhow` in several places. Anyhow can allocate, and is not safe in a signal handler.
5. Various other cleanups
Make the crashtracker code easier to reason about as I try to debug some Ruby hangs.

[crashtracker] Try actually waiting on child processes

---

data-pipeline/src/agent_info/fetcher.rs
data-pipeline/src/agent_info/mod.rs
data-pipeline/src/trace_exporter/mod.rs
data-pipeline/tests/test_fetch_info.rs

Refresh agent info based on `Datadog-Agent-State` and delay fetch on AgentInfoFetcher if the state is not empty.
Provide faster update on agent state changes. Also it avoids querying the /info endpoint when a new exporter is created which currently spams the agent in heavy forking applications

Refresh info using agent state header

---

Cargo.lock
data-pipeline-ffi/Cargo.toml
data-pipeline-ffi/src/error.rs
data-pipeline-ffi/src/trace_exporter.rs

Prevent panics from unwindind in the host language so we can avoid UB. 
Currently there is no guarantee that the trace exporter methods are panic free so there is the possibility that unwinding in the host language can cause UB.
The wrapper is feature gated by "catch_unwind" feature and it's enabled by default. The aim of the feature is having a mechanism to disable the feature if the performance penalty is higher than expected.

Wrap ffi calls with catch_unwind.

---

data-pipeline-ffi/src/trace_exporter.rs
datadog-live-debugger-ffi/src/parse.rs
datadog-sidecar-ffi/src/lib.rs
ddcommon-ffi/src/error.rs
ddcommon-ffi/src/slice.rs
ddcommon-ffi/src/slice_mut.rs
ddcommon-ffi/src/string.rs

This makes some improvements to `AsBytes`:
- New `CharSlice::from_bytes` method to avoid ambiguous constructors.
- Uses `assume_utf8` in more places.
- Removes deduplicate `AsBytes` trait in `slice_mut.rs`.
I was working on some different FFI improvements and wanted to untangle this from my work.
`ddog_parse_live_debugger_json` is now properly marked unsafe. As far as I can tell it's only called from C, so it won't matter, but it's correctly documented now.
Everything should test the same, except possibly `ddog_parse_live_debugger_json` as mentioned before.

refactor(ddcommon-ffi): `AsBytes`/`CharSlice` improvements

---

bin_tests/tests/crashtracker_bin_test.rs
datadog-crashtracker-ffi/src/crash_info/builder.rs
datadog-crashtracker/src/receiver/receive_report.rs

This PR set the `error.message`  field in the crash report.
Today, the `error.message` is empty and in the backend (telemetry), we take the whole crash report to fill the `error.message` field.
In order to make it clean in the UI (crash tracking), we should set the `error.message` to something informational.
The backend will then use it.
For older version of the report, we'll try to generate the same kind of message.
Added assert in `bin_tests`.

[crashtracker] Generate and Set `error.message` field

---

data-pipeline/tests/snapshots/compare_exporter_v04_trace_snapshot_test.json
data-pipeline/tests/snapshots/compare_exporter_v04_trace_snapshot_uds_test.json
data-pipeline/tests/test_trace_exporter.rs
datadog-trace-utils/src/msgpack_decoder/decode/span_event.rs
datadog-trace-utils/src/span/mod.rs
datadog-trace-utils/tests/snapshots/compare_send_data_v04_trace_snapshot_test.json
datadog-trace-utils/tests/snapshots/compare_send_data_v04_trace_snapshot_uds_test.json
datadog-trace-utils/tests/test_send_data.rs

The latest version of the test-agent contains [changes to expectations of how span event should be formatted](https://github.com/DataDog/dd-apm-test-agent/pull/218). This broke the existing deserialization code in trace-utils and the snapshot tests. 
CI for main is broken
If you are testing the change locally you will need to delete your existing test agent docker image to ensure you pull the latest one.

fix span even deserialization to match test agent changes

---

datadog-trace-utils/src/send_data/mod.rs

Implements `set_target` to override the endpoint for a `SendData`.
Supporting dual shipping for traces in the Lambda Extension.

Implement set_target for SendData

---

data-pipeline/src/trace_exporter/error.rs

Add a getter for the error message to access it in the dd-trace-py bindings

feat(data-pipeline): Add getter for RequestError message

---

ddcommon/src/unix_utils/fork.rs

Build is broken on i686 due to `c_long` (return value from`syscall`) being an i32 instead of a i64 see [this job](https://github.com/DataDog/dd-trace-py/actions/runs/16276305502/job/45955939274?pr=13071#step:6:9216)

fix(ddcommon): fix build on i686

---

Cargo.lock
Cargo.toml

Bump version to v19.1.0
No breaking changes as far I could see.
API additions:
- `DDOG_TRACE_EXPORTER_ERROR_CODE_PANIC` to `ddog_TraceExporterErrorCode`
- `ddog_trace_exporter_config_set_rates_payload_version` to data-pipeline.h
- `ddog_trace_exporter_config_set_connection_timeout` to data-pipeline.h

Bump version in preparation for releasing v19.1.0

---

datadog-trace-utils/src/send_data/mod.rs

Add functions to `SendDataBuilder`:
- `with_api_key()`
- `with_retry_strategy()`
https://github.com/DataDog/datadog-lambda-extension/pull/732 We want to lazily set api key in the `target`, i.e. leave it empty at creation time then set it later.
As a result, we need to pass `SendDataBuilder` around in the codebase, instead of passing `SendData`. Wherever we need to set data on `SendData` right now, we need to do it on `SendDataBuilder` instead.
Using the added test

Add functions to SendDataBuilder

---

datadog-trace-utils/src/span/trace_utils.rs
datadog-trace-utils/src/test_utils/mod.rs
datadog-trace-utils/src/trace_utils.rs

Removes hardcoding of span type on all spans to Serverless.
https://datadoghq.atlassian.net/browse/SVLS-7218
While this may have been appropriate at the outset of the project where root spans had to manually be created for Azure Functions, it is no longer necessary due to the automatic instrumentation of http triggers and continuing work to auto instrument other types of triggers.
This also appears to not work correctly as the span type is `serverless` in the flame graph (note the `fx` icon). But the span type is still `custom` (or whatever else it was set to by the tracer) in the trace explorer.
Deployed to Azure Functions and confirmed that span types set by tracer are not overridden.
Current:
Following this change:

fix(datadog-trace-utils): [SVLS-7218] don't hardcode span type on all spans to serverless

---

repository.datadog.yml

We already have a github action that handles stale PRs that we like. The Devflow one isn't as flexible. The intention of the rule was to require branches not be too stale before merging.  This change gets rid of the old definition that auto-closed branches > 3 months old and adds a MergeGate rule that prevents merging branches that haven't been updated within the last 10 days.

Replace DevFlow stale branch auto-closer with MergeGate rule

---

datadog-sidecar-ffi/src/span.rs

Small follow-up to #994.
Otherwise can crash when reading strlen() on the input.

Fix ddog_free_charslice: CharSlice is not a CString

---

data-pipeline-ffi/src/trace_exporter.rs
data-pipeline/src/health_metrics.rs
data-pipeline/src/trace_exporter/builder.rs
data-pipeline/src/trace_exporter/mod.rs

Allow enabling / disabling of health metrics for the Trace Exporter
Health metrics are not enabled by default for most SDKs. We should emit them only when the SDKs tell us to.
Added a new test to verify no metrics are received

APMSP-2173 Make enabling health metrics configurable for the Trace Exporter

---

data-pipeline/src/trace_exporter/mod.rs
data-pipeline/src/trace_exporter/stats.rs

No functionality changes. Just moving the stats computation related functions to a separate module within the Trace Exporter.
Part of a larger effort to break up the Trace Exporter into smaller files ahead of a bigger rearchitecture. 

move trace exporter stats related functions to separate module

---

datadog-trace-utils/src/trace_utils.rs

Moves an error log to an info log
We use trace-utils as part of our agent pipeline, which means that some partial trace chunks are processed. This log gets noisy as an error log because for many cases it's expected often.
Left the log in just moved it to an info level
no functional change but we may begin returning the first span instead of the last to be consistent w/ go

feat: Move error log to debug when multiple root spans may exist in a batch

---

datadog-ipc-macros/src/lib.rs
datadog-ipc/benches/ipc.rs
datadog-ipc/src/handles.rs
datadog-ipc/src/platform/channel/metadata.rs
datadog-ipc/src/platform/mem_handle.rs
datadog-ipc/src/platform/message.rs
datadog-ipc/src/platform/platform_handle.rs
datadog-ipc/src/platform/unix/channel/metadata.rs
datadog-ipc/src/platform/windows/channel/metadata.rs
datadog-ipc/src/transport/blocking.rs
datadog-ipc/tests/blocking_client.rs
datadog-sidecar-ffi/src/lib.rs
datadog-sidecar/src/config.rs
datadog-sidecar/src/service/blocking.rs

And rename the move_handles to a more appropriate copy_handles, because that's what it does.
blocking.rs was a bit simplified to avoid cloning everything just to possibly reuse it upon reconnect.

Add sidecar transport reconnect functionality

---

datadog-live-debugger-ffi/src/send_data.rs
datadog-live-debugger/src/debugger_defs.rs

This also corrects the definition of SnapshotStackFrame, which apparently was just a copy of SnapshotEvaluationError. Oops.

Add FFI functions to push the stack to the debugger snapshot

---

datadog-profiling-ffi/src/profiles/datatypes.rs

- Ensure that the start time is mentioned as an optional field.
Avoid libdatadog users from having to compute a start time.
NA
This is just a doc change.

[PROFILING] comment update: ensure start time is mentioned as optional

---

datadog-sidecar-ffi/src/lib.rs
datadog-sidecar/src/service/sidecar_server.rs
datadog-sidecar/src/service/telemetry.rs

Submission of telemetry logs from the appsec helper happens directly with the TelemetryWorker

Fix in-process submission of telemetry

---

data-pipeline-ffi/src/response.rs
data-pipeline-ffi/src/trace_exporter.rs

The calling code will need to deserialize the response in order to get the sample rates for that it will need the length of the response which can be computed by iterating over the response looking for the NUL character. This results in extra computation in the calling code and this PR address this situation. Moreover the FFI layer was making an additional copy of the payload to turn it into a CString, this was also removed.
Avoid performance penalties while deserializing the response.

Return agent response length.

---

Cargo.lock
Cargo.toml

This PR bumps the libdatadog version to 20.0.0 in preparation for release.
This version bumps the major version due to the following changes:
- #1170 
- #1171 
Include new changes in the trace exporter in a release to be integrated in .NET tracer.

Bump version to 20.0.0

---

datadog-trace-utils/src/trace_utils.rs

Moves an error log to an info log, similar to https://github.com/DataDog/libdatadog/pull/1167
We use trace-utils as part of our agent pipeline, which means that some partial trace chunks are processed. This log gets noisy as an error log because for many cases it's expected often.
Left the log in just moved it to an info level
no functional change

feat: Move error log to debug when no root span exists in a batch

---

repository.datadog.yml

There is not consensus to enforce codeowner approval for all crates, so we don't want to enable the github rule for the entire repo. But the DevFlow MergeGate check supports subfolder enforcement, so team's can opt-in if they so chose. 
Also enabled the requirement that all files have a codeowner. We are already in compliance, so no changes were necessary. 

add mergegate rule to require codeowner approval for data pipeline owned crates

---

ddsketch-ffi/cbindgen.toml
examples/ffi/ddsketch.c

Update the cbindgen file for ddsketch-ffi to rename 
`ddsketch_VoidResult` -> `ddog_VoidResult`
`ddsketch_Error` -> `ddog_Error`
`ddsketch_Vec_U8` -> `ddog_Vec_U8`
These are types imported from `ddcommon-ffi` and should be named consistently across FFI crates. 
Example file has been updated

re-export ddcommon-ffi types correctly in ddsketch-ffi

---

.github/workflows/all-checks.yml

Per title
Some tests can takes ~30mn : https://github.com/DataDog/libdatadog/actions/runs/17307571226
So a 33 minutes timeout may be hit and cause a false positive : https://github.com/DataDog/libdatadog/actions/runs/17308401804/attempts/1 

Increase retries from 30 to 45 in all-checks.yml

---

datadog-trace-utils/src/test_utils/datadog_test_agent.rs
datadog-trace-utils/tests/test_send_data.rs

Add a method on the test agent client that sets the remote config response for a snapshot.
We'd like to have integration tests in dd-trace-rs for our dynamic sample rates. Thus we'd like to set be able to configure the test agent to answer with a certain rc config

feat(datadog-test-agent): add a method to set the remote config response

---

datadog-library-config-ffi/Cargo.toml
datadog-library-config-ffi/src/lib.rs
datadog-library-config/src/lib.rs
ddcommon-ffi/src/error.rs
examples/ffi/library_config.c

This PR causes some breaking changes with tracers using the FFI, see below.
This PR changes the library configuration system to collect debug messages in a buffer and return them with the result, instead of printing them directly using `eprintln!`. This addresses issues where debug output occurs too early in the tracer initialization process, particularly for .NET applications that don't have logging configured yet. So we want to be able to collect log messages that will be treated later on.
- **New `LoggedResult<T, E>` type**: A custom result enum that carries both the result data and a `Vec<String>` of debug messages
- **Updated function signatures**: `get_config`, `get_config_from_file`, `parse_stable_config_file`, and related functions now return `LoggedResult` instead of standard …

[HandsOffConfig] Remove eprintln and return debug messages inside Result

---

datadog-profiling-ffi/src/profiles/datatypes.rs
datadog-profiling-replayer/src/main.rs
datadog-profiling/examples/profiles.rs
datadog-profiling/src/collections/identifiable/mod.rs
datadog-profiling/src/collections/string_storage.rs
datadog-profiling/src/collections/string_table/error.rs
datadog-profiling/src/collections/string_table/mod.rs
datadog-profiling/src/internal/profile/fuzz_tests.rs
datadog-profiling/src/internal/profile/interning_api/mod.rs
datadog-profiling/src/internal/profile/mod.rs

[PROF-11119](https://datadoghq.atlassian.net/browse/PROF-11119)
This PR avoids some panic conditions by gracefully handling some error conditions, such as failing to reserve memory in some places. It does this for:
- Some public APIs that already return errors, so it wasn't difficult to change plumbing.
- Some private APIs that were used only in a few places, so again it wasn't difficult to change plumbing.
I was looking through PHP crash reports and found yet-another out-of-memory crash. I noticed that it would not be difficult to fix the specific issue in the PHP crash report and some adjacent ones.
This doesn't come close to handling all failed allocations and other error conditions. Doing so would require comprehensive changes including API-breaking changes. I'm already working on a …

fix: handle some allocation failures in profile building

---

bin_tests/Cargo.toml
bin_tests/src/bin/crashing_test_app.rs
bin_tests/tests/crashtracker_bin_test.rs
tools/docker/Dockerfile.build

This PR introduces a `crash_test_app` which does function calls, crashes. The crash tracker will collect the report and make sure that the crashing thread callstack contains certain frames.
Stability and quality: We want to make sure that crash tracker, more specifically the unwinder, accurately collects stack frames.
Currently, the test is enabled for:
- x86_64/glibc
- aarch64/glibc
- aarch64/musl-libc
But disabled for:
- x86_64 musl, due to missing CFI (unwinding information) in the libc library.
- macosx: we need to investigate why the report contains messages like `"resolve_names failed with failed to open proc maps file /proc/10282/maps: No such file or directory (os error 2)"`.  It seems that the application already died when we resolve names/normalize ips.

[crashtracker] Add test to check callstack

---

Cargo.lock

[PROF-12463](https://datadoghq.atlassian.net/browse/PROF-12463)
Updates tracing-subscriber from 0.3.19 to 0.3.20. This was done by running:
```sh
cargo update "tracing-subscriber" --precise "0.3.20"
```
See the security warning here: https://github.com/DataDog/libdatadog/security/dependabot/28.
The other dependency changes are related to this upgrade.
Everything should test the same.

fix: vulnerable tracing-subscriber 0.3.19

---

.devcontainer/alpine/devcontainer.json
.devcontainer/ubuntu/devcontainer.json
README.md

This pull request adds support for multiple Dev Container configurations (Ubuntu and Alpine) for the development environment, updates the documentation to reflect these options, and improves the setup instructions and dependencies for both containers. 
Developer experience improvement
- Readme updated
- tested in both dev containers with
```
cargo run --bin release --features profiling,telemetry,data-pipeline,symbolizer,crashtracker,library-config,log,ddsketch -- --out output-folder
```

feat(devcontainer): add Alpine dev container configuration

---

Cargo.lock
Cargo.toml

This PR bumps the libdatadog version to 21.0.0 in preparation for release.
This version bumps the major version due to the following changes:
https://github.com/DataDog/libdatadog/pull/1201
https://github.com/DataDog/libdatadog/pull/1211
To include `crash_ping` mechanism to track crash reports that fail to be emitted

Bump version to 21.0.0

---

datadog-profiling/src/api.rs

`api::ValueType` now derives `Hash` and `api::ValueType::new` is now a `const fn`.
The PHP profiler has its own `ValueType` with two `'static` strs but I realized if I made these changes then PHP could reuse this and have one less conversion. In other words, `const fn new` allows for writing `ValueType<'static>` and `Hash` is because PHP uses it in a hash map (although hopefully that piece will be gone soon).
I made these changes in my browser. It's a rare day to make such simple changes.
Everything works the same, but you can now have `ValueType<'static>` and you can hash `ValueType`s if you want to.

feat(profiling): `ValueType::new` is const and Hash

---

ruby/Rakefile
ruby/lib/libdatadog/version.rb
ruby/spec/gem_packaging.rb

Allows an update to the libdatadog ruby gem, a la https://github.com/DataDog/libdatadog/tree/main/ruby
DDSketch now has a ffi native library that I'd like to use in dd-trace-rb
There's a commit to make it so the standard.rb failure fixes
n/a

Update necessary files to release a new version of the rubygem

---

data-pipeline/src/telemetry/mod.rs
data-pipeline/src/trace_exporter/builder.rs

Add env to telemetry payloads.
Telemetry payloads sent by the exporter are missing env.

Add env to telemetry payload

---

datadog-library-config-ffi/src/tracer_metadata.rs

`0cc3f7` introduced a regression where service env could not be set. This commit re-introduce the service env field.

fix: add service env field back

---

datadog-remote-config/Cargo.toml
datadog-remote-config/src/fetch/fetcher.rs
datadog-remote-config/src/fetch/test_server.rs
datadog-remote-config/src/parse.rs
datadog-remote-config/src/path.rs
datadog-sidecar/Cargo.toml

Move live debugger remote configuration functionality behind a feature flag.
Avoid pulling in unnecessary dependencies for users that don't need live debugging.

chore(remote-config): make live debugger optional feature

---

Cargo.lock
data-pipeline-ffi/src/trace_exporter.rs
data-pipeline/Cargo.toml
data-pipeline/examples/send-traces-with-stats.rs
data-pipeline/src/trace_exporter/builder.rs
data-pipeline/src/trace_exporter/mod.rs
ddtelemetry/Cargo.toml
ddtelemetry/src/config.rs
ddtelemetry/src/lib.rs
ddtelemetry/src/worker/http_client.rs
ddtelemetry/src/worker/mod.rs
examples/ffi/README.md
examples/ffi/trace_exporter.c

- introduces improved logging and debugging capabilities across the telemetry and trace exporter modules
- refactors telemetry API for clarity
We don't get to see what happens in the telemetry crate.
None
- updated tests
- updated example apps (rust and C)

chore: improve logging in telemetry crate

---

builder/src/arch/musl.rs

Fix the missing `SONAME` on musl.
There might have been a change in version of patchelf but starting v20 of libdatadog, sofile does not have a `SONAME` which prevents (ex: .NET profiler/tracer ) linking to libdatadog.
Starting v21
```
readelf -d libdatadog-x86_64-alpine-linux-musl/lib/libdatadog_profiling.so
Dynamic section at offset 0x88c460 contains 27 entries:
Tag        Type                         Name/Value
0x0000000000000001 (NEEDED)             Shared library: [libgcc_s.so.1]
0x0000000000000001 (NEEDED)             Shared library: [libc.musl-x86_64.so.1]
```
before v21
```
readelf -d libdatadog-x86_64-alpine-linux-musl/lib/libdatadog_profiling.so
Dynamic section at offset 0x877340 contains 28 entries:
Tag        Type                         Name/Value
0x000000000000000e (SONAME) …
```

[build] Fix soname on musl
