ddcommon-ffi/Cargo.toml, ddcommon/Cargo.toml, ddtelemetry/Cargo.toml, profiling-ffi/Cargo.toml, profiling/Cargo.toml
Bumps crate versions to 0.8.0-rc.1.
I want to make a new release! We have quite a few changes.
=> Bump versions to 0.8.0-rc.1

Cargo.lock, ddcommon-ffi/Cargo.toml, ddcommon/Cargo.toml, ddtelemetry-ffi/Cargo.toml, ddtelemetry/Cargo.toml, profiling-ffi/Cargo.toml, profiling/Cargo.toml
=> Bump version to v0.9.0

Cargo.lock, ddcommon-ffi/Cargo.toml, ddcommon/Cargo.toml, ddtelemetry-ffi/Cargo.toml, ddtelemetry/Cargo.toml, profiling-ffi/Cargo.toml, profiling/Cargo.toml
=> Bump version to v1.0.0

build-profiling-ffi.sh
Adds support for the environment variable `CARGO_TARGET_DIR`, which controls where cargo places its target directory. The script currently assumes `CARGO_TARGET_DIR` isn't set, and fails when trying to copy things from `./target`.
I was building in a docker container with a mounted volume for libdatadog source. To speed up the build, I set `CARGO_TARGET_DIR` to `/tmp/cargo`, but noticed this script failed.
I wish Mac ASAN supported leak detection already, then I wouldn't have to build in a container 🙃 .
Also, the clippy lint failures are already PR'd in #99.
`export CARGO_TARGET_DIR=/some/path` before running `build-profiling-ffi.sh`. Or, don't and note it should work the same as it does today.
=> feat(build-profiling-ffi.sh): support CARGO_TARGET_DIR

ddtelemetry-ffi/src/sidecar/unix.rs, ddtelemetry/src/ipc/interface.rs, spawn_worker/src/unix/spawn.rs
At least AddConfig needs to happen before LifeCycle(AppStarted), to be picked up at all.
Hence, I'm just dequeuing it right before sending that.
=> Fix configuration in sidecar

Cargo.lock, ddtelemetry/Cargo.toml, ddtelemetry/examples/tm-worker-test.rs, ddtelemetry/src/ipc/sidecar/unix.rs, ipc/Cargo.toml
=> Disable tracing when its not necessary

profiling/src/profile/mod.rs
This PR fixes a rounding error when the scale is `2.7` for example.
Fix bug
=> Fix rounding error

.github/labeler.yml
=> Add dogstatsd to labeller

ipc/src/platform/unix/locks.rs, spawn_worker/src/unix/spawn.rs
Fixes two clippy lints
Clippy lints should be fixed when they make sense to
Can't think of any.
These are both syntax only changes.  Standard `cargo test` run
=> Fix clippy lints

examples/ffi/exporter.cpp, examples/ffi/profiles.c
Fixes the examples from my previous PR.
I realized I had uncommitted changes >.<
I'm sorry.
=> fix: example error handling

ddtelemetry/src/data/metrics.rs, ddtelemetry/src/metrics.rs, ddtelemetry/src/worker/mod.rs
=> Add a metric interval to telemetry metrics and set it to 10s

ddtelemetry/src/data/payloads.rs, ddtelemetry/src/worker/mod.rs
=> [ddtelemetry] Use log count property instead of modifying log message

.github/workflows/test.yml
=> CI fix - No space left

ddtelemetry/src/data/payloads.rs
=> [ddtelemetry][fix] Send configuration list even if it's empty

.github/workflows/test.yml
=> [ci] Don't fail fast on gh action tests

sidecar/Cargo.toml, sidecar/src/interface.rs
=> Ignore some PHP specific code on 32 bit, fixing CI

data-pipeline-ffi/src/trace_exporter.rs, data-pipeline/src/trace_exporter.rs
Make sure that the TraceExporter can be reused.
The TraceExporter was consumed and freed, so it couldn't be used more than one time.
🤷🏼‍♂️
=> [POC] Keep TraceExporter handle around so it can be reused

Cargo.lock, Cargo.toml
version 8
A new release for crashtracking
NA
Check CI.
=> Bump to v8.0.0

data-pipeline/src/trace_exporter.rs, ipc/tarpc/tarpc/src/client.rs, ipc/tarpc/tarpc/src/context.rs, ipc/tarpc/tarpc/src/lib.rs, ipc/tarpc/tarpc/tests/service_functional.rs, sidecar/src/config.rs, sidecar/src/interface.rs, trace-normalization/src/normalizer.rs
The new Rust release adds some new clippy lints. Fix them.
=> Fix clippy lints for 1.78

tools/src/bin/dedup_headers.rs
After d3f85442971ec6074e9912f4b9df578cb4817811 it broke cbindgen generation in dd-trace-php.
The previous /\*\*.*?\*/ parsing would match from a comment to the next typedef fulfilling the criteria, instead of matching just the comment itself.
This is fixed by matching against /\*\*([^*]|\*[^/])*\*/, where the */ sequence is disallowed within a comment. (Also saves us from needing the ungreedy match.)
=> Fix comments parsing in dedup_headers

data-pipeline/Cargo.toml, ddtelemetry/Cargo.toml, trace-mini-agent/Cargo.toml, trace-normalization/Cargo.toml, trace-obfuscation/Cargo.toml
Add descriptions to `cargo.toml` files.
Make the repo more discoverable
=> [Doc] Add descriptions to packages

.github/workflows/fuzz.yml
=> [profiling] Use actions matrix for fuzz

sidecar/src/service/tracing/trace_flusher.rs
This could lead to weird sequencing problems, at least in testing environments, when responses were raced.
=> Ensure responses from flushed traces are handled immediately instead of when all responses returned

trace-utils/src/send_data.rs
Introduced a bug in APMSP-1020 where we were setting `X-Datadog-Trace-Count` for msgpack requests and then throwing the header away and rebuilding the request. This PR now sets the header appropriately. 
Unit tests for msgpack requests now validate headers are correctly sent.
=> Fix bug introduced in APMSP-1020 that was not setting trace count header for msgpack requests to tracer

ddcommon/src/entity_id/fallback.rs
Should fix PHP build for windows.
@VianneyRuhlmann Please check
=> Fix Windows signature compatibility in entity_id functions

.github/workflows/all-checks.yml, profiling/src/internal/profile/fuzz_tests.rs
Adds a CI job to ensure that all checks pass on a PR.
Currently, marking checks "required" is manual, and hard to do for lots of tests.  This automates that.
https://github.com/marketplace/actions/allcheckspassed
=> [chore] Require all checks to pass on a PR

.github/workflows/lint.yml, .github/workflows/publish-serverless-agent.yml
Uses the actionlint CI action, and fixes issues it found.
Ironically, `actionlint` found an issue in this linting action!
```
╰─➤  actionlint                                                                         
../.github/workflows/lint.yml:33:27: property "version" is not defined in object type {platform: string; rust_version: string} [expression]
|
33 |       - name: Install ${{ matrix.version }} toolchain and clippy
```
None of these issues seemed serious, but worth fixing and checking in CI. 
There were a bunch of violations of proper quoting, enough that I'll leave them for a future PR
=> [chore] Add actionlint to CI, and fix issues it detects

.gitlab-ci.yml, .gitlab/benchmarks.yml, Cargo.lock, benchmark/run_benchmarks_ci.sh, trace-obfuscation/Cargo.toml, trace-obfuscation/benches/benchmarks/sql_obfuscation_bench.rs
This sets up a first version of PR benchmarking using the benchmarking platform running a single criterion benchmark.
We need to start measuring our code to find regressions early.
This only runs a single benchmark, since the analysis tools in the benchmarking platform only support the `Flat` sampling mode for Criterion. There is a tracking ticket to update this and run more benchmarks.
[APMS-1196]
[APMS-1196]: https://datadoghq.atlassian.net/browse/APMS-1196?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> PR Benchmarking using benchmarking platform

trace-normalization/src/normalize_utils.rs
* Fix ascii range
* Fix early exit in ascci case
* Make unicode handling faster by checking lowercase class before computing the lowercasing
=> Complete normalization 

.github/workflows/coverage.yml
Add action to free up space during codecov stage.
=> Add action to free space during codecov stage.

docs/RFCs/0001-delivering-different-features.md
What it says in the title
As we add more RFCs, having them numbered makes them easier to refer to.
=> [chore] Number RFCs so they're easier to reference

.codecov.yml
Add missing crates to code coverage support.
=> [APMSP-1391] Add missing crates to code coverage.

data-pipeline/src/agent_info/fetcher.rs
=> Increase test delay

data-pipeline/src/stats_exporter.rs
=> Increase delay for stats_exporter to send stats

sidecar/src/self_telemetry.rs
=> Fix telemetry metric name

trace-utils/src/send_data/mod.rs, trace-utils/src/tracer_header_tags.rs
The vendor header name in trace utils is not correct. 
=> Fix vendor header name

data-pipeline/src/trace_exporter.rs, sidecar-ffi/src/lib.rs, sidecar/src/service/serialized_tracer_header_tags.rs, trace-utils/src/send_data/mod.rs, trace-utils/src/tracer_header_tags.rs, trace-utils/tests/test_send_data.rs
Add `dropped-p0-traces` and `dropped-p0-spans`
=> [APMSP-1350] Add dropped-p0 headers

ruby/Rakefile, ruby/lib/libdatadog/version.rb
=> v14.0.0 release for Ruby

trace-obfuscation/Cargo.toml
Makes PHP compilation in CI pass...
=> Add bench path to trace-obfuscation

trace-utils/src/test_utils/datadog_test_agent.rs
improve error message
It took me a few minutes to figure out why these tests weren't running, this should help next time :)
=> Improve err message

Cargo.lock, Cargo.toml
Bump to v14.2.0. It does not look like there is interface changes. Nuget package is updated but not the interface used.
=> Bump v14.2.0

Cargo.lock, Cargo.toml
What it says on the tin.
Patch release with a fix for crashtracker.
=> Bump version to 14.3.1 in preperation for release

.github/labeler.yml
Add `crashtracker`  label
Identify PRs related to crashtracker tool
=> feat(ci) : Add crashracker label

builder/src/arch/apple.rs
What it says in the title
In the build script crate, a command is being run but never awaited so the script can succeed even if the command fails. This is not great for debuggability.
=> [builder] Wait on command result instead of slapping a clippy lint on it

dogstatsd/src/metric.rs
Change the order of the key and value for the metric resources in DogStatsD.
https://github.com/DataDog/datadog-lambda-extension/issues/494
https://docs.datadoghq.com/api/latest/metrics/#submit-metrics
- See https://datadoghq.atlassian.net/wiki/spaces/SLS/pages/2977497119/Serverless+Mini+Agent#Testing for Azure/GCP.
- Bottlecap: testing by @duncanista
=> [dogstatsd] Fix Key Value Resource Order

remote-config/src/path.rs
Add LFI remote config capability
=> Add rasp LFI remote config capability

spawn_worker/src/trampoline.c
This is apparently the case in google cloud run environments. We just retry with /proc/self then, and it works there.
=> Mitigate race conditions on environments where /proc/<pid> does not immediately appear in the procfs

sidecar/src/one_way_shared_memory.rs
Fixes a problem in the current protocol:
w1. writing <- true (seq cst)
w2. write data
w3. gen <- gen + 1 (seq cst)
w4. writing <- false (seq cst)
r1. read gen (acquire)
r2. read data
r3. read writing (seq cst)
r4. read gen (acquire)
if writing is true or gen has changed, retry
Partial or full data writes for the following generation are observed in practice on armv8.
This introduces a seqlock implemenation that, even if not [formally correct according to the C++ memory model](https://web.archive.org/web/20240225081806/https://www.hpl.hp.com/techreports/2012/HPL-2012-68.pdf) (the data reads/writes should likely be made with something equivalent to relaxed `__atomic_load/store_n`), this generates reasonable code on armv8:
* Non-atomic write is surrounded by ldaddal and ldaddl on the atomic …
=> Fix RC shmem synchronization protocol

ipc/src/platform/unix/mem_handle.rs
Otherwise we unwrap() with zero in some possible race conditions.
=> fix: handle a zero-sized file for `mmap()`ing

library-config-ffi/src/lib.rs, library-config/src/lib.rs
* Parse default host config with correct precedence between local and fleet managed files
* Add all product enablement configurations for phase 1 
* Refactor deserialization and applying config to reduce code duplications and memory allocations (in particular we were copying the file bytes twice before, which we aren't now)
=> Add host global config

Cargo.lock, Cargo.toml
Increase workspace version from  16.0.0 to 16.0.1
Prepare patch release 16.0.1, with minor bugs correction
=> Raise libdatadog to 16.0.1 in preparation for patch release

Cargo.lock, Cargo.toml
Bump workspace version to 16.0.2
We need a bug fix for the library-config crate
Prepare new patch release
=> Bump workspace version to 16.0.2

Cargo.lock, Cargo.toml
Increase patch version of the repo to prepare for a new bug fix
=> Bump patch version to 16.0.3

serverless/src/main.rs, trace-mini-agent/src/aggregator.rs, trace-mini-agent/src/lib.rs, trace-mini-agent/src/mini_agent.rs, trace-mini-agent/src/trace_flusher.rs
Adds a Trace Aggregator for the Trace Flusher.
There is a memory leak bc the buffer was growing without bounds.
There is still an unbounded queue, but its OK bc that will shrink in size on every batch.
Added tests for the aggregator.
=> [trace-mini-agent] add trace aggregator

Cargo.lock, Cargo.toml, profiling/src/api.rs, profiling/src/internal/profile/mod.rs, profiling/src/internal/upscaling.rs
Bump version to 15.1.0 in `v15.x` branch and cherry pick #908 into the release
see #908 
- Merge target for this is the `v15.x` branch not `main`
- the `v15.x` branch was created from the `v15.0.0` tag
=> Prepare v15.1.0 release

trace-utils/src/msgpack_decoder/decode/mod.rs, trace-utils/src/msgpack_decoder/decode/span_event.rs, trace-utils/src/msgpack_decoder/v04/mod.rs, trace-utils/src/msgpack_decoder/v04/span.rs, trace-utils/src/span/mod.rs, trace-utils/src/span/trace_utils.rs, trace-utils/src/span/v05/mod.rs, trace-utils/src/test_utils/mod.rs, trace-utils/src/tracer_payload.rs
Add the `span_events` field in the span model in Trace Exporter.
=> [ APMSP-1674] Support Span Events in Trace Exporter

profiling/src/internal/profile/mod.rs
What it says in the title
We do a bunch of runtime work to validate something that we get right nowadays.
=> [profiler] Only validate sample labels in debug mode

tools/docker/Dockerfile.build
=> style: fix dockerfile lint

bin_tests/tests/crashtracker_bin_test.rs, builder/src/bin/release.rs, live-debugger-ffi/src/data.rs, live-debugger-ffi/src/send_data.rs, profiling/src/internal/profile/mod.rs, sidecar/src/one_way_shared_memory.rs
=> chore:fix clippy errors and failing cross test

Cargo.lock, crashtracker/src/collector/api.rs, crashtracker/src/collector/crash_handler.rs, crashtracker/src/collector/mod.rs, crashtracker/src/collector/receiver_manager.rs, crashtracker/src/collector/signal_handler_manager.rs, ddcommon/Cargo.toml, ddcommon/src/lib.rs, ddcommon/src/unix_utils.rs
Refactors a messy file, and extracts common components to ddcommon.
Clean code is easier to read and reuse.
=> [crashtracker] Refactor receiver manager

data-pipeline-ffi/src/trace_exporter.rs, data-pipeline/examples/send-traces-with-stats.rs, data-pipeline/src/span_concentrator/aggregation.rs, data-pipeline/src/span_concentrator/mod.rs, data-pipeline/src/span_concentrator/tests.rs, data-pipeline/src/stats_exporter.rs, data-pipeline/src/trace_exporter/mod.rs, data-pipeline/tests/test_trace_exporter.rs
=> Switch from sending bytes to slice in TraceExporter

data-pipeline/src/health_metrics.rs, data-pipeline/src/trace_exporter/mod.rs, datadog-trace-utils/src/send_with_retry/mod.rs
Enhances logging in trace exporter.
We want better visibility on failures cases.
None
Usual logging macro usage, nothing to test except logs are flowing.
=> feat(logging): enhance logging in trace exporter

ddcommon-ffi/src/error.rs, ddcommon-ffi/src/string.rs
This changes the implementations of the FFI drop functions for `StringWrapper` and `Error` to be more safe.
I was working on something and noticed we dropped through a `&mut`, which I'm pretty sure is not allowed.
Miri wasn't whining about dropping through a `&mut` cast to a `*mut`, but I'm pretty sure it's yelled at me in the past. In any case, it's safer this way.
No change--just safer semantics if you mess up and use the value after the drop (such as mixing Rust and C code).
=> fix(ddcommon_ffi): StringWrapper and Error drop

data-pipeline-ffi/src/error.rs, data-pipeline-ffi/src/trace_exporter.rs, data-pipeline/src/agent_info/fetcher.rs, data-pipeline/src/span_concentrator/mod.rs, data-pipeline/src/span_concentrator/tests.rs, data-pipeline/src/telemetry/metrics.rs, data-pipeline/src/trace_exporter/mod.rs, datadog-sidecar-ffi/src/lib.rs, datadog-sidecar/src/service/telemetry/enqueued_telemetry_data.rs, ddtelemetry/src/config.rs, ddtelemetry/src/metrics.rs, ddtelemetry/src/worker/mod.rs, ddtelemetry/src/worker/store.rs
=> fix: typos in ddtelemetry and data-pipeline

datadog-crashtracker/src/crash_info/error_data.rs, datadog-crashtracker/src/crash_info/stacktrace.rs
Cache `ElfResolver` instance to avoid computing the same ones for all callstacks.
By caching the `ElfResolver` instances, the receiver overhead is divided by ~3 (CPU and memory)
I used Ruby crashtracker's tests and did the measurements.
=> [crashtracker] Cache ElfResolver instances

data-pipeline-ffi/src/trace_exporter.rs
Enabling rates payload versioning feature from the FFI layer.
=> Add function to enable/disable rates payload versioning.

datadog-crashtracker/benches/receiver_bench.rs, datadog-crashtracker/src/common.rs, datadog-crashtracker/src/crash_info/telemetry.rs, tools/src/lib.rs
What it says on the title
Clippy clean is the way to be
=> [chore] Fix clippy warnings

ruby/Rakefile, ruby/spec/gem_packaging.rb
=> Change the gem publishing such that it changes the executable permissions if they are incorrect

Cargo.lock, Cargo.toml
Bumping major due to at least one [change of API for datadog-library-config
](https://github.com/DataDog/libdatadog/pull/1226)
=> Bump version to 22.0.0
